local GennUI = ...
local LS = LibStub("AceAddon-3.0")
GennUI = LS:GetAddon("GennUI", "AceConsole-3.0", "AceHook-3.0")

function GennUI:LoadBGEProfile()
	BetterBlizzFramesDB = {
		["rpNamesFirst"] = true,
		["customCode"] = "-- Enter custom code below here. Feel free to contact me @bodify",
		["queueTimerWarningTime"] = 6,
		["targetEnlargeAuraFriendly"] = true,
		["hideHitIndicator"] = true,
		["hideActionBarCastAnimation"] = true,
		["partyFrameRangeAlpha"] = 0.55,
		["petCastBarWidth"] = 103,
		["targetCompactAura"] = true,
		["increaseAuraStrata"] = true,
		["powerColorENERGY"] = {
			1,
			1,
			0,
			1,
		},
		["hideFocusLeaderIcon"] = true,
		["targetToTYPos"] = 10,
		["allIngameFont"] = "GennUI",
		["petCastBarScale"] = 1,
		["powerColorSTAGGER"] = {
			0.52,
			1,
			0.52,
			1,
		},
		["focusCastbarIconYPos"] = 0,
		["enemyHealthColor"] = {
			1,
			0,
			0,
			1,
		},
		["targetAbsorbAnchor"] = "TOP",
		["classColorTargetNames"] = true,
		["queueTimerWarning"] = false,
		["useOnePowerColor"] = false,
		["targetCastBarXPosXPos"] = -10,
		["hideTargetReputationColor"] = true,
		["enableBigDebuffs"] = true,
		["targetDetachCastbar"] = true,
		["updates"] = "v1.9.0",
		["purgeTextureColorRGB"] = {
			0,
			0.92,
			1,
			0.85,
		},
		["unitframeCastBarNoTextBorder"] = false,
		["playerCastBarTimer"] = true,
		["printAuraSpellIds"] = false,
		["customColorsUnitFrames"] = true,
		["queueTimerID"] = 567458,
		["partyFrameStatusFontSize"] = "12",
		["targetBuffFilterBlacklist"] = true,
		["enablePlayerBuffFiltering"] = true,
		["powerColorLUNAR_POWER"] = {
			0.3,
			0.52,
			0.9,
			1,
		},
		["opBarriersOn"] = true,
		["focusdeBuffEnable"] = true,
		["targetAndFocusHorizontalGap"] = 3,
		["changeUnitFrameFont"] = true,
		["combatIndicatorShowSap"] = false,
		["queueTimer"] = true,
		["changeRaidFrameManabarTexture"] = true,
		["playerCastBarScale"] = 1,
		["unitFrameFont"] = "GennUI",
		["classColorWARRIOR"] = {
			0.78,
			0.61,
			0.43,
			1,
		},
		["focusToTAdjustmentOffsetY"] = 0,
		["combatIndicatorXPos"] = -50,
		["targetAndFocusSmallAuraScale"] = 1,
		["partyRaidFrameBackgroundManaColor"] = {
			0,
			0,
			0,
			0.5,
		},
		["playerCastBarWidth"] = 210,
		["auraCdTextSize"] = 0.7,
		["targetToTAdjustmentOffsetY"] = 0,
		["changePartyFrameRangeAlpha"] = true,
		["reopenOptions"] = false,
		["hasSaved"] = true,
		["powerColorEBON_MIGHT"] = {
			0.9,
			0.55,
			0.3,
			1,
		},
		["powerColorINSANITY"] = {
			0.4,
			0,
			0.8,
			1,
		},
		["hasCheckedUi"] = true,
		["targetCombatIndicator"] = true,
		["actionBarFontColorRGB"] = {
			1,
			1,
			1,
			1,
		},
		["hideFocusReputationColor"] = true,
		["petCastBarHeight"] = 10,
		["racialIndicatorScale"] = 1,
		["raidFrameHealthbarTexture"] = "GennUI B",
		["auraWhitelist"] = {
			["example aura :3 (delete me)"] = {
				["name"] = "Example Aura :3 (delete me)",
			},
		},
		["hidePlayerRestGlow"] = true,
		["changeUnitFrameHealthbarTexture"] = true,
		["allowLargeAuraFirst"] = true,
		["absorbIndicator"] = false,
		["queueTimerAudio"] = true,
		["hideCombatIcon"] = true,
		["maxDebuffFrameDebuffs"] = 16,
		["showPartyCastBarIcon"] = true,
		["absorbIndicatorScale"] = 1,
		["fadeMicroMenuExceptQueue"] = true,
		["cdManagerCenterIcons"] = true,
		["focusdeBuffFilterAll"] = false,
		["partyCastBarIconScale"] = 1,
		["overShieldsCompact"] = true,
		["frameAuraRowAmount"] = 0,
		["targetdeBuffEnable"] = true,
		["partyCastBarTimer"] = false,
		["overShieldsUnitFrames"] = true,
		["enlargedAuraSize"] = 1.4,
		["focusCombatIndicator"] = true,
		["focusCastBarScale"] = 1,
		["partyCastBarYPos"] = 0,
		["targetdeBuffFilterLessMinite"] = false,
		["partyCastBarHeight"] = 12,
		["hideThreatOnFrame"] = true,
		["focusdeBuffFilterBlacklist"] = true,
		["hidePlayerRoleIcon"] = true,
		["playerBuffFilterBlacklist"] = true,
		["targetAbsorbYPos"] = 0,
		["playerAbsorbYPos"] = 0,
		["targetRacialIndicator"] = true,
		["targetBuffFilterAll"] = true,
		["partyCastbarIconXPos"] = 0,
		["druidAlwaysShowCombos"] = true,
		["changeUnitFrameManaBarTextureKeepFancy"] = false,
		["hideTalkingHeads"] = true,
		["classColorFrames"] = true,
		["focusCastBarTimer"] = false,
		["classColorLevelText"] = false,
		["filterGladiusSpam"] = true,
		["focusToTCastbarAdjustment"] = true,
		["targetCastBarHeight"] = 10,
		["changeRaidFrameHealthbarTexture"] = true,
		["moveResourceToTargetPaladinBG"] = true,
		["hideFocusToTDebuffs"] = true,
		["noPortraitModes"] = false,
		["targetCastBarYPosYPos"] = -70,
		["powerColorMANA"] = {
			0,
			0,
			1,
			1,
		},
		["focusImportantAuraGlow"] = true,
		["classicFrames"] = false,
		["playerReputationClassColor"] = true,
		["classColorTargetReputationTexture"] = false,
		["targetdeBuffFilterWatchList"] = false,
		["classColorMONK"] = {
			0,
			1,
			0.59,
			1,
		},
		["fixActionBarCDsAlwaysHideCD"] = false,
		["combatIndicatorShowSwords"] = true,
		["healerIndicatorYPos"] = 0,
		["castBarInterruptIconAnchor"] = "RIGHT",
		["targetCastbarIconYPosYPos"] = 0,
		["petCastBarXPos"] = 0,
		["racialIndicatorHuman"] = true,
		["focusBuffFilterLessMinite"] = false,
		["hidePlayerGuideIcon"] = true,
		["unitFrameBgTexture"] = "Solid",
		["petCastBarYPos"] = 0,
		["changeAllFontsIngame"] = true,
		["gladWinTracker"] = true,
		["darkModeCastbars"] = true,
		["partyFrameFont"] = "GennUI",
		["playerFrameOCD"] = true,
		["legacyComboYPos"] = -25,
		["targetAbsorbXPos"] = 0,
		["partyCastBarTestMode"] = false,
		["queueStatusButtonPosition"] = {
			"TOPRIGHT",
			nil,
			"TOPRIGHT",
			-30.94112205505371,
			-180.6582794189453,
		},
		["targetdeBuffFilterAll"] = false,
		["partyCastbarIconYPos"] = 0,
		["focusCastbarIconXPos"] = 0,
		["focusToTXPosXPos"] = -36,
		["focusEnlargeAuraFriendly"] = true,
		["changeUnitFrameManabarTexture"] = true,
		["combatIndicatorAnchor"] = "RIGHT",
		["classPortraitsUseSpecIcons"] = true,
		["auraBlacklist"] = {
			[186403] = {
				["name"] = "Sign of Battle",
				["id"] = 186403,
			},
			["guild champion"] = {
				["name"] = "Guild Champion",
			},
			["sign of the scourge"] = {
				["name"] = "Sign of the Scourge",
			},
			["sign of the skirmisher"] = {
				["name"] = "Sign of the Skirmisher",
			},
			["stormwind champion"] = {
				["name"] = "Stormwind Champion",
			},
			["sign of iron"] = {
				["name"] = "Sign of Iron",
			},
			[397734] = {
				["name"] = "Word of a Worthy Ally",
				["id"] = 397734,
			},
			[32727] = {
				["name"] = "Arena Preparation",
				["id"] = 32727,
			},
			[93805] = {
				["name"] = "Ironforge Champion",
				["id"] = 93805,
			},
			["honorless target"] = {
				["name"] = "Honorless Target",
			},
			["enlisted"] = {
				["name"] = "Enlisted",
			},
		},
		["legacyComboXPos"] = -28,
		["castBarNoInterruptColor"] = {
			1,
			0,
			0.01568627543747425,
		},
		["castBarInterruptIconDisplayCD"] = true,
		["focusCastBarIconScale"] = 1,
		["racialIndicatorYPos"] = 0,
		["targetdeBuffFilterBlizzard"] = true,
		["playerCastBarWidthScale"] = 210,
		["raidFrameBgTexture"] = "Solid",
		["targetStaticCastbar"] = false,
		["unitFrameFontSize"] = "12",
		["zoomActionBarIcons"] = true,
		["normalCastbarForEmpoweredCasts"] = true,
		["hideMinimapButtons"] = false,
		["partyCastBarWidth"] = 100,
		["petCastBarIconScale"] = 1,
		["unitFrameBgTextureManaColor"] = {
			0,
			0,
			0,
			0.5,
		},
		["hideObjectiveTracker"] = true,
		["targetAndFocusAuraOffsetY"] = 0,
		["focusEnlargeAuraEnemy"] = true,
		["showPetCastBarIcon"] = true,
		["hidePetText"] = true,
		["pixelBorderAuras"] = false,
		["frameAurasYPos"] = 0,
		["hideResourceTooltip"] = true,
		["racialIndicatorXPos"] = 0,
		["racialIndicatorOrc"] = true,
		["unitFrameFontOutline"] = "THINOUTLINE",
		["targetCastBarWidth"] = 150,
		["customHealthbarColors"] = false,
		["filterMiscInfo"] = true,
		["petCastBarTestMode"] = false,
		["darkModeUi"] = false,
		["focusToTScaleScale"] = 1,
		["unitFrameHealthbarTexture"] = "GennUI B",
		["darkModeActionBars"] = true,
		["hideRaidFrameContainerBorder"] = true,
		["unitFrameValueFontOutline"] = "THINOUTLINE",
		["hiddenIconDirection"] = "BOTTOM",
		["newRaidFrameRoleIcons"] = true,
		["racialIndicatorDwarf"] = true,
		["rpNames"] = true,
		["customColorsRaidFrames"] = true,
		["playerAbsorbAnchor"] = "TOP",
		["hidePlayerCornerIcon"] = true,
		["playerCombatIndicator"] = true,
		["powerColorFURY"] = {
			0.788,
			0.259,
			0.992,
			1,
		},
		["powerColorSOUL_FRAGMENTS"] = {
			0.35,
			0.25,
			0.73,
			1,
		},
		["classColorFrameTexture"] = false,
		["playerCastBarTimerCentered"] = false,
		["optimizedAuraLists"] = true,
		["targetAndFocusArenaNamePartyOverride"] = true,
		["singlePowerColor"] = {
			1,
			1,
			1,
			1,
		},
		["version"] = "1.00",
		["changePartyFrameFont"] = true,
		["castBarInterruptHighlighterDontInterruptRGB"] = {
			1,
			0,
			0,
		},
		["playerCastBarIconScale"] = 1,
		["targetToTXPos"] = -36,
		["targetEnlargeAuraEnemy"] = true,
		["formatStatusBarText"] = true,
		["combatIndicatorScaleScale"] = 0.6000000238418579,
		["minimizeObjectiveTracker"] = true,
		["normalizeGameMenu"] = true,
		["focusdeBuffFilterLessMinite"] = false,
		["uiWidgetPowerBarScale"] = 1,
		["partyFrameFontOutline"] = "THINOUTLINE",
		["playerCastBarTimerCenter"] = false,
		["useOneClassColor"] = false,
		["maxAurasOnFrame"] = 0,
		["classColorROGUE"] = {
			1,
			0.96,
			0.41,
			1,
		},
		["playerAuraSpacingY"] = 0,
		["targetCastbarIconXPosXPos"] = 175,
		["recolorCastbars"] = true,
		["targetCastBarYPos"] = -70,
		["castbarChannelColor"] = {
			0.1294117718935013,
			0.4666666984558106,
			0.6392157077789307,
			1,
		},
		["targetToTYPosYPos"] = 10,
		["cdManagerPriorityList"] = {
		},
		["focusToTScale"] = 1,
		["neutralHealthColor"] = {
			1,
			1,
			0,
			1,
		},
		["legacyBlueComboPoints"] = true,
		["focusToTAnchor"] = "BOTTOMRIGHT",
		["targetCastbarIconYPos"] = 0,
		["partyCastBarXPos"] = 0,
		["combatIndicatorYPos"] = 40,
		["hidePrestigeBadge"] = true,
		["targetBuffFilterLessMinite"] = false,
		["healerIndicator"] = true,
		["focusCastBarYPos"] = 0,
		["partyCastBarScale"] = 1,
		["targetEnlargeAura"] = true,
		["castBarInterruptIconScale"] = 1,
		["targetBuffFilterPurgeable"] = false,
		["customPowerColors"] = false,
		["changeUnitFrameValueFont"] = false,
		["compactedAuraSize"] = 0.7,
		["targetToTAnchor"] = "BOTTOMRIGHT",
		["hideExpAndHonorBar"] = true,
		["frameAuraWidthGap"] = 0,
		["playerAuraFiltering"] = true,
		["focusdeBuffFilterOnlyMe"] = false,
		["onlyPandemicAuraMine"] = true,
		["hidePvpTimerText"] = true,
		["unitFrameBgTextureColor"] = {
			0,
			0,
			0,
			0.5,
		},
		["classColorSHAMAN"] = {
			0,
			0.44,
			0.87,
			1,
		},
		["hideRareDragonTexture"] = true,
		["focusToTYPos"] = 10,
		["castBarInterruptHighlighterInterruptRGB"] = {
			0,
			1,
			0,
		},
		["showPetCastBarTimer"] = false,
		["classColorDRUID"] = {
			1,
			0.49,
			0.04,
			1,
		},
		["powerColorRAGE"] = {
			1,
			0,
			0,
			1,
		},
		["unitFrameFontColorRGB"] = {
			1,
			1,
			1,
			1,
		},
		["castBarInterruptIconShowActiveOnly"] = false,
		["racialIndicator"] = false,
		["absorbIndicatorTestMode"] = false,
		["darkModeUiAura"] = true,
		["combatIndicatorXPosXPos"] = -50,
		["auraTypeGap"] = 4,
		["targetBuffFilterOnlyMe"] = false,
		["hidePartyRangeIcon"] = true,
		["hidePetHitIndicator"] = true,
		["darkModeColor"] = 0.2,
		["displayDispelGlowAlways"] = false,
		["racialIndicatorUndead"] = true,
		["cleanedAuraBlacklist"] = true,
		["targetCastBarIconScale"] = 1,
		["targetCastBarTimer"] = false,
		["playerCastBarShowIcon"] = true,
		["raidFrameManabarTexture"] = "GennUI B",
		["classColorPartyNames"] = false,
		["lossOfControlScale"] = 1,
		["classColorPALADIN"] = {
			0.96,
			0.55,
			0.73,
			1,
		},
		["targetCastbarIconXPos"] = 175,
		["classColorEVOKER"] = {
			0.2,
			0.58,
			0.5,
			1,
		},
		["removeRealmNames"] = true,
		["healerIndicatorXPos"] = 0,
		["healerIndicatorScale"] = 1,
		["focusToTXPos"] = -36,
		["moveQueueStatusEye"] = true,
		["focusBuffFilterOnlyMe"] = false,
		["partyRaidFrameBackgroundHealthColor"] = {
			0,
			0,
			0,
			0.5,
		},
		["petCastbar"] = false,
		["enablePlayerDebuffFiltering"] = false,
		["unitFrameValueFontColorRGB"] = {
			1,
			1,
			1,
			1,
		},
		["hidePetName"] = true,
		["customImportantAuraSorting"] = true,
		["castbarUninterruptableColor"] = {
			0.8431373238563538,
			0,
			0.08235294371843338,
			1,
		},
		["wasOnLoadingScreen"] = false,
		["racialIndicatorNelf"] = true,
		["focusCastBarXPos"] = 0,
		["maxTargetBuffs"] = 32,
		["targetAndFocusAuraScale"] = 1,
		["auraImportantDispelIcon"] = true,
		["darkModeVigor"] = false,
		["auraToggleIconTexture"] = 134430,
		["classColorPRIEST"] = {
			1,
			1,
			1,
			1,
		},
		["targetdeBuffPandemicGlow"] = true,
		["removeAddonListCategories"] = true,
		["overShields"] = true,
		["playerCastbarIconYPos"] = 0,
		["targetdeBuffFilterOnlyMe"] = false,
		["focusCastBarWidth"] = 150,
		["cdManagerBlacklist"] = {
		},
		["auraCdTextSizeScale"] = 0.699999988079071,
		["targetToTXPosXPos"] = -36,
		["powerColorCHI"] = {
			0.71,
			1,
			0.92,
			1,
		},
		["playerAbsorbAmount"] = true,
		["hidePetFrame"] = false,
		["hidePlayerRestAnimation"] = true,
		["focusRacialIndicator"] = true,
		["combatIndicatorScale"] = 0.6,
		["focusAbsorbIcon"] = true,
		["auraStackSize"] = 1,
		["targetAbsorbAmount"] = true,
		["targetAndFocusAuraOffsetX"] = 0,
		["classColorFriendlist"] = true,
		["castBarDelayedInterruptColor"] = {
			1,
			0.4784314036369324,
			0.9568628072738647,
		},
		["castBarInterruptIconFocus"] = true,
		["healerIndicatorYPosYPos"] = 0,
		["darkModeMinimap"] = false,
		["surrenderArena"] = true,
		["powerColorFOCUS"] = {
			1,
			0.5,
			0.25,
			1,
		},
		["unitFrameManabarTexture"] = "GennUI B",
		["focusdeBuffFilterWatchList"] = false,
		["targetToTCastbarAdjustment"] = true,
		["darkModeObjectiveFrame"] = true,
		["focusAbsorbAmount"] = true,
		["PlayerAuraFrameBuffEnable"] = true,
		["classColorDEMONHUNTER"] = {
			0.64,
			0.19,
			0.79,
			1,
		},
		["partyFrameRangeAlphaSolidBackground"] = true,
		["PlayerAuraFramedeBuffFilterWatchList"] = false,
		["playerAuraSpacingX"] = 5,
		["classColorMAGE"] = {
			0.25,
			0.78,
			0.92,
			1,
		},
		["centerNames"] = true,
		["targetCastBarXPos"] = -10,
		["PlayerAuraFrameBuffFilterWatchList"] = false,
		["frameAurasXPos"] = 0,
		["targetAuraGlows"] = true,
		["maxBuffFrameBuffs"] = 32,
		["focusEnlargeAura"] = true,
		["focusBuffEnable"] = true,
		["fixActionBarCDs"] = true,
		["focusBuffFilterBlacklist"] = true,
		["targetBuffFilterWatchList"] = false,
		["powerColorRUNIC_POWER"] = {
			0,
			0.82,
			1,
			1,
		},
		["createAltManaBarDruid"] = true,
		["healerIndicatorAnchor"] = "CENTER",
		["castBarInterruptHighlighterStartTime"] = 0.8,
		["focusBuffFilterPurgeable"] = false,
		["legacyComboScale"] = 0.85,
		["healerIndicatorPortrait"] = false,
		["classColorDEATHKNIGHT"] = {
			0.77,
			0.12,
			0.23,
			1,
		},
		["focusBuffFilterWatchList"] = false,
		["hideFocusCombatGlow"] = false,
		["powerColorMAELSTROM"] = {
			0,
			0.5,
			1,
			1,
		},
		["combatIndicator"] = true,
		["targetAndFocusVerticalGap"] = 4,
		["filterTalentSpam"] = true,
		["combatIndicatorYPosYPos"] = 40,
		["classColorWARLOCK"] = {
			0.53,
			0.53,
			0.93,
			1,
		},
		["friendlyHealthColor"] = {
			0,
			1,
			0,
			1,
		},
		["targetdeBuffFilterBlacklist"] = true,
		["partyFrameScale"] = 1,
		["castBarInterruptIconTarget"] = true,
		["unitFrameValueFont"] = "GennUI",
		["focusCastBarHeight"] = 10,
		["playerCastBarHeight"] = 11,
		["playerCastbarIconXPos"] = 0,
		["castBarInterruptIconYPos"] = 0,
		["showPartyCastbar"] = true,
		["raidFramePixelBorder"] = false,
		["showAuraCdText"] = true,
		["overrideClassColors"] = false,
		["targetAndFocusAurasPerRow"] = 6,
		["castBarInterruptHighlighterEndTime"] = 0.6,
		["racialIndicatorDarkIronDwarf"] = true,
		["focusBuffFilterAll"] = true,
		["playerAbsorbIcon"] = true,
		["playerEliteFrameMode"] = 1,
		["castbarCastColor"] = {
			0.4313725829124451,
			0.4666666984558106,
			0.4705882668495178,
			1,
		},
		["healerIndicatorIcon"] = true,
		["focusCompactAura"] = true,
		["targetAbsorbIcon"] = true,
		["classicCastbarsPlayer"] = false,
		["classicCastbarsPlayerBorder"] = true,
		["skipCustomColorNames"] = false,
		["targetToTScale"] = 1,
		["hideGroupIndicator"] = false,
		["PlayerAuraFramedeBuffEnable"] = true,
		["maxTargetDebuffs"] = 16,
		["playerAbsorbXPos"] = 0,
		["playerdeBuffFilterBlacklist"] = true,
		["targetImportantAuraGlow"] = true,
		["druidOverstacks"] = true,
		["frameAuraHeightGap"] = 0,
		["classColorHUNTER"] = {
			0.67,
			0.83,
			0.45,
			1,
		},
		["castBarInterruptIconXPos"] = 0,
		["focusToTYPosYPos"] = 10,
		["overShieldsCompactUnitFrames"] = true,
		["noPortraitPixelBorder"] = false,
		["frameAuraScale"] = 0,
		["customLargeSmallAuraSorting"] = true,
		["hideDragonFlying"] = true,
		["showHiddenAurasIcon"] = true,
		["singleClassColor"] = {
			1,
			1,
			1,
			1,
		},
		["focusdeBuffFilterBlizzard"] = true,
		["hidePartyFrameTitle"] = true,
		["focusdeBuffPandemicGlow"] = true,
		["targetBuffEnable"] = true,
		["targetCastBarScale"] = 1,
		["singleValueStatusBarText"] = true,
		["partyFrameFontColorRGB"] = {
			1,
			1,
			1,
			1,
		},
		["focusAuraGlows"] = true,
		["partyFrameFontSize"] = "12",
	}
end
