local GennUI = ...
local LS = LibStub("AceAddon-3.0")
GennUI = LS:GetAddon("GennUI", "AceConsole-3.0", "AceHook-3.0")

function GennUI:LoadBBPProfile()
	BetterBlizzPlatesDB = {
		["npBgColorRGB"] = {
			1,
			1,
			1,
			1,
		},
		["classIndicatorFriendlyScale"] = 1.45,
		["otherNpdeBuffFilterCC"] = false,
		["ccIconXPos"] = 0,
		["totemIndicatorScale"] = 1,
		["nameplateKeyAuraScale"] = 1,
		["executeIndicatorPercentSymbol"] = false,
		["hideNPCHideSecondaryPets"] = true,
		["nameplateAuraBuffScale"] = 1,
		["friendlyNpdeBuffFilterLessMinite"] = false,
		["friendlyNpBuffFilterLessMinite"] = false,
		["otherNpdeBuffFilterWatchList"] = true,
		["castBarInterruptHighlighterColorDontInterrupt"] = false,
		["enableNameplateAuraCustomisation"] = true,
		["nameplateHorizontalPosition"] = 0,
		["classIndicatorXPos"] = 0,
		["fixedFriendlyHealthbarHide"] = true,
		["hideCastbarWhitelist"] = {
		},
		["colorNPCName"] = false,
		["questIndicatorTestMode"] = false,
		["targetIndicatorYPos"] = 0,
		["executeIndicatorScale"] = 1,
		["petIndicatorColorHealthbarRGB"] = {
			0.03,
			0.35,
			0,
		},
		["focusTargetIndicatorTexture"] = "Shattered DF (BBP)",
		["defaultFadeOutNPCsList"] = {
			{
				["id"] = 165189,
				["name"] = "Hunter Pet (they all have same ID)",
				["comment"] = "",
			},
			{
				["id"] = 26125,
				["name"] = "DK Pet",
				["comment"] = "",
			},
			{
				["id"] = 148797,
				["name"] = "Magus(Army of the Dead)",
				["comment"] = "",
			},
			{
				["id"] = 163366,
				["name"] = "Magus(Army of the Dead)",
				["comment"] = "",
			},
			{
				["id"] = 24207,
				["name"] = "Army of the Dead",
				["comment"] = "",
			},
			{
				["id"] = 17252,
				["name"] = "Felguard (Demo Pet)",
				["comment"] = "",
			},
			{
				["id"] = 29264,
				["name"] = "Spirit Wolves (Enha Shaman)",
				["comment"] = "",
			},
			{
				["id"] = 95072,
				["name"] = "Earth Elemental (Shaman)",
				["comment"] = "",
			},
			{
				["id"] = 95061,
				["name"] = "Greater Fire Elemental (Shaman)",
				["comment"] = "",
			},
			{
				["id"] = 77936,
				["name"] = "Greater Storm Elemental (Shaman)",
				["comment"] = "",
			},
			{
				["id"] = 31216,
				["name"] = "Mirror Images (Mage)",
				["comment"] = "",
			},
			{
				["id"] = 62005,
				["name"] = "Beast (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 228224,
				["name"] = "Fenryr (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 228226,
				["name"] = "Hati (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 228226,
				["name"] = "Dark Hound (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 69791,
				["name"] = "Monk SEF Image (Red)",
				["comment"] = "",
			},
			{
				["id"] = 69792,
				["name"] = "Monk SEF Image (Green)",
				["comment"] = "",
			},
			{
				["id"] = 135816,
				["name"] = "Vilefiend (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 226268,
				["name"] = "Gloomhound (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 226269,
				["name"] = "Charhound (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 103822,
				["name"] = "Treant",
				["comment"] = "",
			},
			{
				["id"] = 221633,
				["name"] = "Whitemane (DK)",
				["comment"] = "",
			},
			{
				["id"] = 221632,
				["name"] = "Mograine (DK)",
				["comment"] = "",
			},
			{
				["id"] = 221634,
				["name"] = "Nazgrim (DK)",
				["comment"] = "",
			},
			{
				["id"] = 221635,
				["name"] = "Trollbane (DK)",
				["comment"] = "",
			},
			{
				["id"] = 208441,
				["name"] = "Water Elemental (Mage)",
				["comment"] = "",
			},
			{
				["id"] = 105419,
				["name"] = "Dire Basilisk (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 192337,
				["name"] = "Void Tendril (Spriest)",
				["comment"] = "",
			},
			{
				["id"] = 136398,
				["name"] = "Illidari Satyr",
				["comment"] = "",
			},
			{
				["id"] = 136408,
				["name"] = "Darkhound",
				["comment"] = "",
			},
			{
				["id"] = 136403,
				["name"] = "Void Terror",
				["comment"] = "",
			},
			{
				["id"] = 54983,
				["name"] = "Treant",
				["comment"] = "",
			},
		},
		["friendlyClassColorName"] = true,
		["castbarAlwaysOnTop"] = false,
		["enemyNeutralHealthBarColorRGB"] = {
			1,
			1,
			0,
		},
		["targetIndicatorScale"] = 1,
		["changeNameplateBorderColor"] = false,
		["disableCompactedAurasOnSelf"] = false,
		["old_defaultLargeFontSize"] = 12,
		["questIndicatorAnchor"] = "LEFT",
		["otherNpBuffFilterPurgeable"] = false,
		["partyPointerTextureScale"] = 3,
		["otherNpdeBuffEnable"] = true,
		["otherNpBuffBlueBorder"] = false,
		["combatIndicatorXPos"] = 0,
		["npBorderFocusColorRGB"] = {
			0,
			0,
			0,
			1,
		},
		["bgIndicatorShowFlags"] = true,
		["hideCastbarList"] = {
		},
		["nameplateAuraRectangleSize"] = false,
		["classIndicatorScale"] = 1,
		["hpHeightSelfMana"] = 10.8,
		["showNpcTitle"] = true,
		["partyPointerCCAuras"] = true,
		["arenaIdAnchor"] = "TOP",
		["importantCCDisarm"] = true,
		["hideNameplateAuraTooltip"] = false,
		["nameplateAurasPersonalYPos"] = 0,
		["castBarNoninterruptibleColor"] = {
			0.4,
			0.4,
			0.4,
		},
		["npAuraDiseaseRGB"] = {
			1,
			0.53,
			0.14,
		},
		["healthNumbersUseMillions"] = true,
		["focusTargetIndicatorTestMode"] = false,
		["disableCVarForceOnLogin"] = false,
		["old_defaultFontSize"] = 9,
		["targetIndicatorTestMode"] = false,
		["importantBuffsDefensives"] = true,
		["absorbIndicatorAnchor"] = "LEFT",
		["arenaIndicatorModeOff"] = false,
		["nameplateAuraRightToLeft"] = false,
		["friendlyNpBuffBlueBorder"] = false,
		["nameplateShowEnemyGuardians"] = "0",
		["castBarEmphasisSparkHeight"] = 35,
		["castBarPixelBorder"] = true,
		["nameplateEnemyHeight"] = 17.1875,
		["targetIndicatorChangeTexture"] = false,
		["fixedNameplateMotion"] = true,
		["nameplateAurasYPos"] = 0,
		["castBarEmphasisColor"] = false,
		["petIndicatorHideSecondaryPets"] = true,
		["defaultNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
		["enableMidnightNameplateTweaks"] = true,
		["nameplateAurasNoNameYPos"] = 0,
		["classIconReactionBorder"] = false,
		["targetIndicatorColorNameplateRGB"] = {
			1,
			0,
			0.44,
		},
		["bgIndicatorShowOrbs"] = true,
		["enemyHealthBarColor"] = false,
		["arenaIdXPos"] = 0,
		["ccIconScale"] = 1.35,
		["arenaIndicatorModeThree"] = false,
		["hideNPCsWhitelist"] = {
			{
				["id"] = 165189,
				["name"] = "Hunter Pet (they all have same ID)",
				["comment"] = "",
			},
			{
				["id"] = 59764,
				["name"] = "Healing Tide Totem",
				["comment"] = "",
			},
			{
				["id"] = 5925,
				["name"] = "Grounding Totem",
				["comment"] = "",
			},
			{
				["id"] = 53006,
				["name"] = "Spirit Link Totem",
				["comment"] = "",
			},
			{
				["id"] = 5913,
				["name"] = "Tremor Totem",
				["comment"] = "",
			},
			{
				["id"] = 104818,
				["name"] = "Ancestral Protection Totem",
				["comment"] = "",
			},
			{
				["id"] = 119052,
				["name"] = "War Banner",
				["comment"] = "",
			},
			{
				["id"] = 61245,
				["name"] = "Capacitor Totem",
				["comment"] = "",
			},
			{
				["id"] = 105451,
				["name"] = "Counterstrike Totem",
				["comment"] = "",
			},
			{
				["id"] = 101398,
				["name"] = "Psyfiend (Spriest)",
				["comment"] = "",
			},
			{
				["id"] = 100943,
				["name"] = "Earthen Wall Totem",
				["comment"] = "",
			},
			{
				["id"] = 107100,
				["name"] = "Observer (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 135002,
				["name"] = "Tyrant (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 114565,
				["name"] = "Guardian Queen (prot pala)",
				["comment"] = "",
			},
			{
				["id"] = 3527,
				["name"] = "Healing Stream Totem",
				["comment"] = "",
			},
			{
				["id"] = 78001,
				["name"] = "Cloudburst Totem",
				["comment"] = "",
			},
			{
				["id"] = 10467,
				["name"] = "Mana Tide Totem",
				["comment"] = "",
			},
			{
				["id"] = 97285,
				["name"] = "Wind Rush Totem",
				["comment"] = "",
			},
			{
				["id"] = 60561,
				["name"] = "Earthgrab Totem",
				["comment"] = "",
			},
			{
				["id"] = 2630,
				["name"] = "Earthbind Totem",
				["comment"] = "",
			},
			{
				["id"] = 105427,
				["name"] = "Totem of Wrath",
				["comment"] = "",
			},
			{
				["id"] = 97369,
				["name"] = "Liquid Magma Totem",
				["comment"] = "",
			},
			{
				["id"] = 62982,
				["name"] = "Mindbender",
				["comment"] = "",
			},
			{
				["id"] = 179867,
				["name"] = "Static Field Totem",
				["comment"] = "",
			},
			{
				["id"] = 194117,
				["name"] = "Stoneskin Totem",
				["comment"] = "",
			},
			{
				["id"] = 5923,
				["name"] = "Poison Cleansing Totem",
				["comment"] = "",
			},
			{
				["id"] = 194118,
				["name"] = "Tranquil Air Totem",
				["comment"] = "",
			},
			{
				["id"] = 17252,
				["name"] = "Felguard (Demo Pet)",
				["comment"] = "",
			},
			{
				["id"] = 417,
				["name"] = "Felhunter (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 1863,
				["name"] = "Succubus (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 89,
				["name"] = "Infernal (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 59712,
				["name"] = "Stone Bulwark Totem",
				["comment"] = "",
			},
			{
				["id"] = 225672,
				["name"] = "Shadow (Priest Re-Fear)",
				["comment"] = "",
			},
			{
				["id"] = 224466,
				["name"] = "Voidwraith (Priest)",
				["comment"] = "",
			},
			{
				["id"] = 19668,
				["name"] = "Shadowfiend",
				["comment"] = "",
			},
			{
				["id"] = 225409,
				["name"] = "Surging Totem",
				["comment"] = "",
			},
		},
		["fakeNameYPosYPos"] = -4,
		["castBarTextScale"] = 1,
		["otherNpdeBuffFilterAll"] = false,
		["colorNPC"] = true,
		["classIndicatorAnchor"] = "TOP",
		["druidAlwaysShowCombos"] = false,
		["healthNumbersXPos"] = 0,
		["arenaSpecAnchor"] = "TOP",
		["questIndicator"] = true,
		["executeIndicatorXPos"] = 0,
		["partySpecScale"] = 1,
		["nameplateMinScale"] = 1,
		["otherNpBuffEmphasisedBorder"] = false,
		["personalNpBuffFilterImportantBuffs"] = false,
		["castBarIconScale"] = 1.3,
		["totemIndicatorHideNameAndShiftIconDown"] = false,
		["nameplateAuraKeyAuraPositionFriendly"] = false,
		["nameplateAuraRowAmount"] = 5,
		["dpsOrHealNoAggroColorRGB"] = {
			1,
			0,
			0,
			1,
		},
		["nameplateExtraClickWidth"] = 0,
		["castBarInterruptHighlighterEndTime"] = 0.6,
		["nameplateAuraRelativeAnchor"] = "TOPLEFT",
		["combatIndicatorEnemyOnly"] = false,
		["partyPointerArenaOnly"] = true,
		["ccIconAnchor"] = "RIGHT",
		["healerIndicatorYPos"] = 0,
		["npBorderNpcColorRGB"] = {
			0,
			0,
			0,
			1,
		},
		["partyPointerHideAll"] = false,
		["targetIndicatorAnchor"] = "TOP",
		["hideEnemyNameText"] = false,
		["darkModeNameplateColor"] = 0.2,
		["npBorderEnemyColorRGB"] = {
			1,
			0,
			0,
			1,
		},
		["hideRaidmarkIndicator"] = false,
		["nameplateMaxAlpha"] = "1",
		["useCustomFont"] = true,
		["npAuraBuffsRGB"] = {
			0,
			0.67,
			1,
		},
		["otherNpdeBuffFilterLessMinite"] = false,
		["healthNumbersNotOnFullHp"] = false,
		["enableCustomFontOutline"] = true,
		["defaultOutlinedFontSize"] = 9,
		["castBarInterruptHighlighterInterruptRGB"] = {
			0,
			1,
			0,
		},
		["nameplateBorderSize"] = 1,
		["partyPointerWidth"] = 36,
		["nameplateResourceScale"] = 1,
		["raidmarkerPvPOnly"] = false,
		["healerIndicatorEnemyOnly"] = true,
		["hideNpcMurlocScale"] = 1,
		["old_defaultLargeNamePlateFontFlags"] = "",
		["npBorderFriendFoeColor"] = false,
		["healthNumbersFontOutline"] = "OUTLINE",
		["npAuraCurseRGB"] = {
			0.47,
			0,
			0.78,
		},
		["hidePersonalBarManaFrame"] = false,
		["arenaIndicatorBg"] = true,
		["arenaSpecScale"] = 1,
		["focusTargetIndicatorChangeTexture"] = false,
		["classIndicatorHideRaidMarker"] = true,
		["partyPointerXPos"] = 0,
		["classIconArenaOnly"] = false,
		["classIconAlwaysShowTank"] = false,
		["castBarEmphasisText"] = false,
		["nameplateFriendlyWidth"] = 180,
		["classicNameplates"] = false,
		["classIndicatorBackgroundSize"] = 1,
		["enlargeAllCC"] = true,
		["friendlyColorNameRGB"] = {
			1,
			1,
			1,
		},
		["otherNpBuffFilterImportantBuffs"] = false,
		["fakeNameRaiseStrata"] = false,
		["nameplateAuraDebuffSelfScale"] = 1,
		["totemIndicatorScaleUpImportant"] = false,
		["defaultNamePlateOutlinedFont"] = "Fonts\\FRIZQT__.TTF",
		["npBorderFriendlyColorRGB"] = {
			0,
			1,
			0,
			1,
		},
		["interruptedByIndicator"] = true,
		["tankFullAggroColorRGB"] = {
			1,
			0,
			0,
			1,
		},
		["healerIndicatorScale"] = 1,
		["castBarEmphasisOnlyInterruptable"] = false,
		["nameplateShowFriendlyPlayerGuardians"] = "0",
		["arenaSpecXPos"] = 0,
		["castEmphasisList"] = {
			{
				["name"] = "Cyclone",
			},
			{
				["name"] = "Polymorph",
			},
			{
				["name"] = "Sleep Walk",
			},
			{
				["name"] = "Fear",
			},
			{
				["name"] = "Repentance",
			},
			{
				["name"] = "Hex",
			},
			{
				["name"] = "Ring of Frost",
			},
			{
				["name"] = "Mass Polymorph",
			},
			{
				["name"] = "Shadowfury",
			},
			{
				["name"] = "Haymaker",
			},
			{
				["name"] = "Mind Control",
			},
			{
				["name"] = "Hibernate",
			},
			{
				["name"] = "Scare Beast",
			},
			{
				["name"] = "Lightning Lasso",
			},
			{
				["name"] = "Song of Chi-Ji",
			},
			{
				["name"] = "Ring of Fire",
			},
		},
		["nameplateShowEnemyMinus"] = "0",
		["shortArenaSpecName"] = false,
		["importantBuffsMobilityGlowRGB"] = {
			["a"] = 1,
			["b"] = 1,
			["g"] = 1,
			["r"] = 0,
		},
		["darkModeNameplateResource"] = false,
		["tankOffTankAggroColorRGB"] = {
			0.5372549295425415,
			0.250980406999588,
			0,
			1,
		},
		["fadeOutNPC"] = false,
		["otherNpdeBuffFilterOnlyMe"] = false,
		["enemyColorThreatCombatOnlyPlayer"] = false,
		["smallPetsWidth"] = 20,
		["importantCCSilence"] = true,
		["auraColorList"] = {
		},
		["personalNpBuffFilterOnlyMe"] = false,
		["separateAuraBuffRow"] = true,
		["healthNumbersYPosYPos"] = 0,
		["castBarEmphasisIcon"] = false,
		["healerIndicatorAnchor"] = "TOPRIGHT",
		["executeIndicatorShowDecimal"] = true,
		["castBarEmphasisIconScale"] = 2,
		["alwaysHideFriendlyCastbar"] = true,
		["nameplateShowFriendlyNPCs"] = "0",
		["healthNumbersShowDecimal"] = false,
		["hideNPCsList"] = {
			{
				["id"] = 31216,
				["name"] = "Mirror Images (Mage)",
				["comment"] = "",
			},
			{
				["id"] = 55659,
				["name"] = "Wild Imp (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 143622,
				["name"] = "Wild Imp (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 29264,
				["flags"] = {
					["murloc"] = true,
				},
				["comment"] = "",
				["name"] = "Spirit Wolves (Shaman)",
			},
			{
				["id"] = 69791,
				["flags"] = {
					["murloc"] = true,
				},
				["comment"] = "",
				["name"] = "Monk SEF Image (Red)",
			},
			{
				["id"] = 69792,
				["flags"] = {
					["murloc"] = true,
				},
				["comment"] = "",
				["name"] = "Monk SEF Image (Green)",
			},
			{
				["id"] = 208441,
				["flags"] = {
					["murloc"] = true,
				},
				["comment"] = "",
				["name"] = "Water Elemental (Mage)",
			},
		},
		["customCastbarBGTexture"] = "GennUI B",
		["partyIndicatorModeOne"] = false,
		["hpHeightSelf"] = 10.8,
		["petIndicatorShowMurloc"] = true,
		["castBarEmphasisHeightValue"] = 24,
		["questIndicatorXPos"] = 0,
		["otherNpdeBuffFilterBlacklist"] = true,
		["castBarIconXPos"] = 0,
		["classIndicatorFriendly"] = true,
		["disableEnlargedAurasOnSelf"] = false,
		["sortCompactedAurasFirst"] = false,
		["totemIndicatorNpcList"] = {
			[105427] = {
				["important"] = false,
				["name"] = "Totem of Wrath",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.27,
					0.59,
				},
				["duration"] = 15,
				["icon"] = 1385914,
				["size"] = 24,
			},
			[5913] = {
				["important"] = true,
				["name"] = "Tremor Totem",
				["hideIcon"] = false,
				["color"] = {
					0.49,
					0.9,
					0.08,
				},
				["duration"] = 13,
				["icon"] = 136108,
				["size"] = 30,
			},
			[105451] = {
				["important"] = true,
				["name"] = "Counterstrike Totem",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.27,
					0.59,
				},
				["duration"] = 15,
				["icon"] = 511726,
				["size"] = 30,
			},
			[59764] = {
				["important"] = true,
				["name"] = "Healing Tide Totem",
				["hideIcon"] = false,
				["color"] = {
					0,
					1,
					0.39,
				},
				["duration"] = 10,
				["icon"] = 538569,
				["size"] = 30,
			},
			[97285] = {
				["important"] = false,
				["name"] = "Wind Rush Totem",
				["hideIcon"] = false,
				["color"] = {
					0.08,
					0.82,
					0.78,
				},
				["duration"] = 18,
				["icon"] = 538576,
				["size"] = 24,
			},
			[100943] = {
				["important"] = true,
				["name"] = "Earthen Wall Totem",
				["hideIcon"] = false,
				["color"] = {
					0.78,
					0.49,
					0.35,
				},
				["duration"] = 18,
				["icon"] = 136098,
				["size"] = 30,
			},
			[225409] = {
				["important"] = false,
				["name"] = "Surging Totem",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.36,
					0,
				},
				["duration"] = 24,
				["icon"] = 5927655,
				["size"] = 24,
			},
			[104818] = {
				["important"] = true,
				["name"] = "Ancestral Protection Totem",
				["hideIcon"] = false,
				["color"] = {
					0,
					1,
					0.78,
				},
				["duration"] = 33,
				["icon"] = 136080,
				["size"] = 30,
			},
			[61245] = {
				["important"] = true,
				["name"] = "Capacitor Totem",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.69,
					0,
				},
				["duration"] = 2,
				["icon"] = 136013,
				["size"] = 30,
			},
			[3527] = {
				["important"] = false,
				["name"] = "Healing Stream Totem",
				["hideIcon"] = false,
				["color"] = {
					0,
					1,
					0.78,
				},
				["duration"] = 18,
				["icon"] = 135127,
				["size"] = 24,
			},
			[53006] = {
				["important"] = true,
				["name"] = "Spirit Link Totem",
				["hideIcon"] = false,
				["color"] = {
					0,
					1,
					0.78,
				},
				["duration"] = 6,
				["icon"] = 237586,
				["size"] = 30,
			},
			[97369] = {
				["important"] = false,
				["name"] = "Liquid Magma Totem",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.69,
					0,
				},
				["duration"] = 6,
				["icon"] = 971079,
				["size"] = 24,
			},
			[2630] = {
				["important"] = false,
				["name"] = "Earthbind Totem",
				["hideIcon"] = false,
				["color"] = {
					0.78,
					0.51,
					0.39,
				},
				["duration"] = 30,
				["icon"] = 136102,
				["size"] = 24,
			},
			[224466] = {
				["important"] = false,
				["name"] = "Voidwraith",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.69,
					0,
				},
				["duration"] = 15,
				["icon"] = 615099,
				["size"] = 24,
			},
			[107024] = {
				["important"] = true,
				["name"] = "Fel Lord",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.69,
					0,
				},
				["duration"] = 15,
				["icon"] = 1113433,
				["size"] = 30,
			},
			[185800] = {
				["important"] = false,
				["name"] = "Past Self",
				["hideIcon"] = false,
				["color"] = {
					1,
					0,
					0,
				},
				["duration"] = 8,
				["icon"] = 4622470,
				["size"] = 24,
			},
			[78001] = {
				["name"] = "Cloudburst Totem",
				["hideIcon"] = false,
				["color"] = {
					0,
					1,
					0.39,
				},
				["important"] = false,
				["duration"] = 15,
				["size"] = 24,
			},
			[62982] = {
				["important"] = false,
				["name"] = "Mindbender",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.69,
					0,
				},
				["duration"] = 15,
				["icon"] = 136214,
				["size"] = 24,
			},
			[5923] = {
				["important"] = false,
				["name"] = "Poison Cleansing Totem",
				["hideIcon"] = false,
				["color"] = {
					0.49,
					0.9,
					0.08,
				},
				["duration"] = 9,
				["icon"] = 136070,
				["size"] = 24,
			},
			[225672] = {
				["important"] = true,
				["name"] = "Shadow",
				["hideIcon"] = false,
				["color"] = {
					0.78,
					0.48,
					1,
				},
				["duration"] = 4,
				["icon"] = 136184,
				["size"] = 35,
			},
			[59712] = {
				["important"] = true,
				["name"] = "Stone Bulwark Totem",
				["hideIcon"] = false,
				["color"] = {
					0.98,
					0.75,
					0.17,
				},
				["duration"] = 30,
				["icon"] = 538572,
				["size"] = 30,
			},
			[101398] = {
				["important"] = true,
				["name"] = "Psyfiend",
				["hideIcon"] = false,
				["color"] = {
					0.49,
					0,
					1,
				},
				["duration"] = 12,
				["icon"] = 537021,
				["size"] = 35,
			},
			[179867] = {
				["important"] = false,
				["name"] = "Static Field Totem",
				["hideIcon"] = false,
				["color"] = {
					0,
					1,
					0.78,
				},
				["duration"] = 6,
				["icon"] = 1020304,
				["size"] = 24,
			},
			[194117] = {
				["important"] = false,
				["name"] = "Stoneskin Totem",
				["hideIcon"] = false,
				["color"] = {
					0.78,
					0.49,
					0.35,
				},
				["duration"] = 15,
				["icon"] = 4667425,
				["size"] = 24,
			},
			[5925] = {
				["important"] = true,
				["name"] = "Grounding Totem",
				["hideIcon"] = false,
				["color"] = {
					1,
					0,
					1,
				},
				["duration"] = 3,
				["icon"] = 136039,
				["size"] = 30,
			},
			[114565] = {
				["important"] = true,
				["name"] = "Guardian of the Forgotten Queen",
				["hideIcon"] = false,
				["color"] = {
					1,
					0,
					1,
				},
				["duration"] = 10,
				["icon"] = 135919,
				["size"] = 30,
			},
			[194118] = {
				["important"] = false,
				["name"] = "Tranquil Air Totem",
				["hideIcon"] = false,
				["color"] = {
					0,
					1,
					0.78,
				},
				["duration"] = 20,
				["icon"] = 538575,
				["size"] = 24,
			},
			[65282] = {
				["name"] = "Void Tendril",
				["hideIcon"] = false,
				["color"] = {
					0.33,
					0.35,
					1,
				},
				["important"] = false,
				["duration"] = 6,
				["size"] = 24,
			},
			[14465] = {
				["name"] = "Alliance Battle Standard",
				["hideIcon"] = false,
				["color"] = {
					0,
					0.22,
					1,
				},
				["important"] = true,
				["icon"] = 132486,
				["size"] = 24,
			},
			[89] = {
				["important"] = false,
				["name"] = "Infernal",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.69,
					0,
				},
				["duration"] = 30,
				["icon"] = 136219,
				["size"] = 24,
			},
			[196111] = {
				["important"] = false,
				["name"] = "Pit Lord",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.69,
					0,
				},
				["duration"] = 10,
				["icon"] = 236423,
				["size"] = 24,
			},
			[14466] = {
				["name"] = "Horde Battle Standard",
				["hideIcon"] = false,
				["color"] = {
					1,
					0,
					0,
				},
				["important"] = true,
				["icon"] = 132485,
				["size"] = 24,
			},
			[19668] = {
				["important"] = false,
				["name"] = "Shadowfiend",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.69,
					0,
				},
				["duration"] = 15,
				["icon"] = 136199,
				["size"] = 24,
			},
			[60561] = {
				["important"] = false,
				["name"] = "Earthgrab Totem",
				["hideIcon"] = false,
				["color"] = {
					0.75,
					0.31,
					0.1,
				},
				["duration"] = 30,
				["icon"] = 136100,
				["size"] = 24,
			},
			[135002] = {
				["important"] = true,
				["name"] = "Tyrant",
				["hideIcon"] = false,
				["color"] = {
					1,
					0.69,
					0,
				},
				["duration"] = 15,
				["icon"] = 2065628,
				["size"] = 30,
			},
		},
		["classIconColorBorder"] = true,
		["enemyNeutralColorNameRGB"] = {
			1,
			1,
			0,
		},
		["targetIndicatorColorName"] = false,
		["classIconHealthNumbers"] = false,
		["partyPointerHealerOnly"] = false,
		["nameplateAuraRowAbove"] = true,
		["nameplateEnemyWidth"] = 180,
		["classIndicatorShowPet"] = true,
		["nameplateAuraCompactedSquare"] = true,
		["nameplateShowAll"] = "1",
		["absorbIndicatorOnPlayersOnly"] = true,
		["healthNumbersYPos"] = 0,
		["raidmarkIndicatorXPos"] = 0,
		["bgIndicator"] = true,
		["targetNameplateAuraScaleEnabled"] = false,
		["castBarDelayedInterruptColor"] = {
			1,
			0.4784314036369324,
			0.9568628072738647,
		},
		["friendlyNpdeBuffFilterCC"] = true,
		["otherNpBuffFilterLessMinite"] = false,
		["hideResourceOnFriend"] = false,
		["skipAdjustingFixedFonts"] = false,
		["buffIconScale"] = 1.1,
		["friendlyNpBuffFilterWatchList"] = false,
		["showCastbarIfTarget"] = false,
		["partyPointerAlwaysShowPet"] = false,
		["sortEnlargedAurasFirst"] = true,
		["castBarIconPosReset"] = true,
		["classIndicatorFrameStrataHigh"] = false,
		["absorbIndicatorXPos"] = 0,
		["partyIndicatorModeFive"] = false,
		["showGuildNames"] = false,
		["healerIndicatorEnemyXPos"] = 0,
		["hpHeightFriendly"] = 1,
		["importantCCSilenceGlow"] = true,
		["nameplateShowClassColor"] = "1",
		["nameplateDefaultLargeFriendlyHeight"] = 64.125,
		["importantCCFullGlow"] = true,
		["classIconAlwaysShowBgObj"] = true,
		["hideCastbarText"] = false,
		["hpHeightEnemy"] = 16,
		["arenaIndicatorModeTwo"] = false,
		["nameplateEnemyWidthScale"] = 180,
		["castBarEmphasisHeight"] = false,
		["otherNpBuffFilterAll"] = false,
		["castBarIconYPos"] = 0,
		["hideFriendlyNameText"] = false,
		["fakeNameAnchor"] = "BOTTOM",
		["nameplateDefaultEnemyWidth"] = 110,
		["classIconBgOnly"] = false,
		["nameplateAuraTypeGap"] = 0,
		["hideDefaultPersonalNameplateAuras"] = false,
		["npcTitleColor"] = false,
		["partyPointerTestMode"] = false,
		["personalNpBuffFilterBlizzard"] = true,
		["petIndicatorTestMode"] = false,
		["personalNpBuffFilterLessMinite"] = false,
		["questIndicatorScale"] = 1.2,
		["nameplateResourceYPos"] = 0,
		["nameplateSelectedScale"] = 1.1,
		["castBarBackgroundColor"] = {
			0.33,
			0.33,
			0.33,
			1,
		},
		["friendlyNameplatesOnlyInRaids"] = false,
		["nameplateAuraSelfScale"] = 1,
		["friendlyHealthBarColorPlayer"] = false,
		["castBarNoInterruptColor"] = {
			1,
			0,
			0.01568627543747425,
		},
		["guildNameScale"] = 0.9,
		["partyPointerShowOthersPets"] = false,
		["friendlyHealthBarColorRGB"] = {
			0,
			1,
			0,
		},
		["classIndicatorHealer"] = true,
		["hideNPCWhitelistOn"] = false,
		["nameplateAuraTaller"] = false,
		["classIndicatorOnlyFriends"] = false,
		["petIndicatorYPos"] = 0,
		["changeResourceStrata"] = false,
		["raidmarkIndicator"] = false,
		["defaultLargeNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
		["nameplateVerticalPosition"] = 0,
		["npcTitleColorRGB"] = {
			1,
			0.85,
			0,
		},
		["arenaIdYPos"] = 0,
		["dpsOrHealFullAggroColorRGB"] = {
			1,
			0.4705882668495178,
			0,
			1,
		},
		["classIndicatorHighlight"] = true,
		["nameplateFriendlyWidthScale"] = 180,
		["castBarHeight"] = 16,
		["npBorderTargetColorRGB"] = {
			1,
			1,
			1,
			1,
		},
		["classIndicatorSpecIcon"] = false,
		["castBarEmphasisSelfColorRGB"] = {
			1,
			0,
			0,
		},
		["totemIndicatorColorName"] = true,
		["npcColorRareElite"] = {
			0.49,
			1,
			0.74,
			1,
		},
		["customFontSizeEnabled"] = false,
		["partyPointerHideRaidmarker"] = true,
		["alwaysShowPurgeTexture"] = true,
		["friendlyNpBuffFilterBlacklist"] = true,
		["castBarInterruptHighlighter"] = false,
		["fakeNameScaleWithParent"] = false,
		["targetIndicatorColorNameplate"] = false,
		["updates"] = "v1.9.7c",
		["classIndicatorFriendlyAnchor"] = "TOP",
		["personalNpdeBuffEnable"] = false,
		["hideNpcMurlocYPos"] = 0,
		["nameplateDefaultEnemyHeight"] = 45,
		["useCustomCastbarTexture"] = true,
		["otherNpBuffFilterWatchList"] = true,
		["nameplateAuraPixelBorder"] = false,
		["nameplateShowEnemyTotems"] = "1",
		["nameplateShadowRGB"] = {
			0,
			0,
			0,
			1,
		},
		["nameplateTargetBorderSize"] = 3,
		["showNameplateCastbarTimer"] = false,
		["levelFrameFontSize"] = 12,
		["partyPointerShowPet"] = false,
		["partyIndicatorModeOff"] = false,
		["otherNpdeBuffPandemicGlow"] = false,
		["useCustomTextureForSelf"] = false,
		["useCustomTextureForFriendly"] = true,
		["castBarShieldAnchor"] = "LEFT",
		["showNameplateShadowOnlyTarget"] = false,
		["enableNpNonTargetAlpha"] = false,
		["partyPointerHighlightRGB"] = {
			1,
			0.71,
			0,
		},
		["classIndicatorBackgroundRGB"] = {
			0,
			0,
			0,
			1,
		},
		["nameplateMinAlpha"] = "0.6",
		["targetNameplateAuraScale"] = 1,
		["showDefaultCooldownNumbersOnNpAuras"] = false,
		["focusTargetIndicatorColorNameplate"] = false,
		["reopenOptions"] = false,
		["ccIconYPos"] = 0,
		["nameplateAuraWidthGap"] = 4,
		["otherNpdeBuffFilterBlizzard"] = true,
		["friendIndicator"] = false,
		["defaultLargeFontSize"] = 12,
		["keyAurasImportantBuffsEnabled"] = true,
		["useFakeNameAnchorBottom"] = false,
		["customFontSizeScale"] = 12,
		["disableDefaultBlizzardOutline"] = false,
		["old_defaultLargeNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
		["enemyColorName"] = false,
		["npcColorMiniboss"] = {
			1,
			0,
			1,
			1,
		},
		["hpHeightFriendlyScale"] = 1,
		["importantCCRootGlowRGB"] = {
			["a"] = 1,
			["b"] = 0,
			["g"] = 0.874,
			["r"] = 1,
		},
		["auraWhitelist"] = {
			{
				["name"] = "Example Aura :3 (delete me)",
				["entryColors"] = {
					["text"] = {
						["r"] = 0,
						["g"] = 1,
						["b"] = 0,
					},
				},
			},
		},
		["npcColorMelee"] = {
			0.760784387588501,
			0.6000000238418579,
			0.4196078777313232,
			1,
		},
		["castBarHeightHeight"] = 16,
		["nameplateShowFriendlyPlayerMinions"] = "0",
		["nameplateShadowHighlightRGB"] = {
			1,
			1,
			1,
			1,
		},
		["nameplateDefaultFriendlyHeight"] = 45,
		["nameplateOverlapHScale"] = 0.8,
		["importantBuffsOffensives"] = true,
		["bgIndicatorYPos"] = 0,
		["nameplateMotion"] = "1",
		["classIndicatorFriendlyXPos"] = 0,
		["nameplateAurasXPos"] = 0,
		["customFontShadowOff"] = true,
		["nameplateShowEnemyPets"] = "1",
		["absorbIndicatorScale"] = 1,
		["friendlyNpBuffFilterAll"] = false,
		["arenaIndicatorModeFour"] = false,
		["nameplateAuraSquare"] = false,
		["nameplateAuraDebuffScale"] = 1,
		["hidePersonalBarExtraFrame"] = false,
		["executeIndicator"] = false,
		["classIndicatorTank"] = true,
		["enableNpVerticalPos"] = false,
		["absorbIndicatorYPos"] = 0,
		["npBorderClassColor"] = false,
		["castBarEmphasisHealthbarColor"] = false,
		["healerIndicatorEnemyYPos"] = 0,
		["personalBarPosition"] = 0.5,
		["healthNumbersOnlyInCombat"] = false,
		["castBarEmphasisTextScale"] = 2,
		["druidOverstacks"] = true,
		["keepNpShadowTargetHighlighted"] = false,
		["customTextureSelfMana"] = "Solid",
		["customFontSize"] = 12,
		["hideEliteDragon"] = true,
		["hidePersonalManaFX"] = false,
		["nameplateResourceUnderCastbar"] = false,
		["npBorderTargetColor"] = false,
		["friendlyNpdeBuffFilterWatchList"] = false,
		["targetIndicator"] = false,
		["cleanedScaleScale"] = true,
		["personalBarTweaks"] = false,
		["healthNumbersCombined"] = false,
		["friendlyNpBuffPurgeGlow"] = false,
		["absorbIndicator"] = false,
		["castBarIconPixelBorder"] = true,
		["customTexture"] = "GennUI B",
		["healthNumbersScale"] = 1.1,
		["castBarShieldYPos"] = 0,
		["totemIndicatorHideAuras"] = false,
		["showCastBarIconWhenNoninterruptible"] = false,
		["nameplateDefaultLargeEnemyHeight"] = 64.125,
		["instantComboPoints"] = false,
		["disableImportantAurasOnSelf"] = false,
		["nameplateCastbarTestMode"] = false,
		["raidmarkIndicatorRaiseStrata"] = false,
		["removeRealmNames"] = true,
		["castBarDragonflightShield"] = true,
		["importantBuffsMobilityGlow"] = true,
		["nameplateAurasFriendlyCenteredAnchor"] = false,
		["tankNoAggroColorRGB"] = {
			1,
			0,
			0,
			1,
		},
		["executeIndicatorThreshold"] = 40,
		["hideTempHpLoss"] = false,
		["customFontOutline"] = "THINOUTLINE",
		["nameplateAurasPersonalCenteredAnchor"] = false,
		["classIndicatorHighlightColor"] = false,
		["buffIconYPos"] = 0,
		["fadeOutNPCsList"] = {
			{
				["id"] = 165189,
				["name"] = "Hunter Pet (they all have same ID)",
				["comment"] = "",
			},
			{
				["id"] = 26125,
				["name"] = "DK Pet",
				["comment"] = "",
			},
			{
				["id"] = 148797,
				["name"] = "Magus(Army of the Dead)",
				["comment"] = "",
			},
			{
				["id"] = 163366,
				["name"] = "Magus(Army of the Dead)",
				["comment"] = "",
			},
			{
				["id"] = 24207,
				["name"] = "Army of the Dead",
				["comment"] = "",
			},
			{
				["id"] = 17252,
				["name"] = "Felguard (Demo Pet)",
				["comment"] = "",
			},
			{
				["id"] = 29264,
				["name"] = "Spirit Wolves (Enha Shaman)",
				["comment"] = "",
			},
			{
				["id"] = 95072,
				["name"] = "Earth Elemental (Shaman)",
				["comment"] = "",
			},
			{
				["id"] = 95061,
				["name"] = "Greater Fire Elemental (Shaman)",
				["comment"] = "",
			},
			{
				["id"] = 77936,
				["name"] = "Greater Storm Elemental (Shaman)",
				["comment"] = "",
			},
			{
				["id"] = 31216,
				["name"] = "Mirror Images (Mage)",
				["comment"] = "",
			},
			{
				["id"] = 62005,
				["name"] = "Beast (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 228224,
				["name"] = "Fenryr (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 228226,
				["name"] = "Hati (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 228226,
				["name"] = "Dark Hound (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 69791,
				["name"] = "Monk SEF Image (Red)",
				["comment"] = "",
			},
			{
				["id"] = 69792,
				["name"] = "Monk SEF Image (Green)",
				["comment"] = "",
			},
			{
				["id"] = 135816,
				["name"] = "Vilefiend (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 226268,
				["name"] = "Gloomhound (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 226269,
				["name"] = "Charhound (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 103822,
				["name"] = "Treant",
				["comment"] = "",
			},
			{
				["id"] = 221633,
				["name"] = "Whitemane (DK)",
				["comment"] = "",
			},
			{
				["id"] = 221632,
				["name"] = "Mograine (DK)",
				["comment"] = "",
			},
			{
				["id"] = 221634,
				["name"] = "Nazgrim (DK)",
				["comment"] = "",
			},
			{
				["id"] = 221635,
				["name"] = "Trollbane (DK)",
				["comment"] = "",
			},
			{
				["id"] = 208441,
				["name"] = "Water Elemental (Mage)",
				["comment"] = "",
			},
			{
				["id"] = 105419,
				["name"] = "Dire Basilisk (Hunter)",
				["comment"] = "",
			},
			{
				["id"] = 192337,
				["name"] = "Void Tendril (Spriest)",
				["comment"] = "",
			},
			{
				["id"] = 136398,
				["name"] = "Illidari Satyr",
				["comment"] = "",
			},
			{
				["id"] = 136408,
				["name"] = "Darkhound",
				["comment"] = "",
			},
			{
				["id"] = 136403,
				["name"] = "Void Terror",
				["comment"] = "",
			},
			{
				["id"] = 54983,
				["name"] = "Treant",
				["comment"] = "",
			},
		},
		["enemyColorThreatHideSolo"] = false,
		["useCustomTextureForBars"] = true,
		["useCustomTextureForExtraBars"] = true,
		["nameplateCenterAllRows"] = false,
		["showNameplateTargetText"] = true,
		["classIndicatorBackground"] = false,
		["personalNpdeBuffFilterLessMinite"] = false,
		["nameplateGeneralHpHeight"] = 18,
		["friendlyNpdeBuffFilterAll"] = false,
		["blizzardDefaultFilterOnlyMine"] = false,
		["partyIDScale"] = 1,
		["threatColorAlwaysOn"] = false,
		["npColorAuraBorder"] = false,
		["arenaIdAnchorRaiseStrata"] = false,
		["buffIconXPos"] = 0,
		["petIndicator"] = false,
		["enemyNameplateHealthbarHeight"] = 10.8,
		["enemyColorThreatCombatOnly"] = false,
		["customFont"] = "GennUI",
		["nameplateSelfHeight"] = 17.1875,
		["fadeOutNPCsWhitelist"] = {
			{
				["id"] = 165189,
				["name"] = "Hunter Pet (they all have same ID)",
				["comment"] = "",
			},
			{
				["id"] = 59764,
				["name"] = "Healing Tide Totem",
				["comment"] = "",
			},
			{
				["id"] = 5925,
				["name"] = "Grounding Totem",
				["comment"] = "",
			},
			{
				["id"] = 53006,
				["name"] = "Spirit Link Totem",
				["comment"] = "",
			},
			{
				["id"] = 5913,
				["name"] = "Tremor Totem",
				["comment"] = "",
			},
			{
				["id"] = 104818,
				["name"] = "Ancestral Protection Totem",
				["comment"] = "",
			},
			{
				["id"] = 119052,
				["name"] = "War Banner",
				["comment"] = "",
			},
			{
				["id"] = 61245,
				["name"] = "Capacitor Totem",
				["comment"] = "",
			},
			{
				["id"] = 105451,
				["name"] = "Counterstrike Totem",
				["comment"] = "",
			},
			{
				["id"] = 101398,
				["name"] = "Psyfiend (Spriest)",
				["comment"] = "",
			},
			{
				["id"] = 100943,
				["name"] = "Earthen Wall Totem",
				["comment"] = "",
			},
			{
				["id"] = 107100,
				["name"] = "Observer (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 135002,
				["name"] = "Tyrant (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 114565,
				["name"] = "Guardian Queen (prot pala)",
				["comment"] = "",
			},
			{
				["id"] = 3527,
				["name"] = "Healing Stream Totem",
				["comment"] = "",
			},
			{
				["id"] = 78001,
				["name"] = "Cloudburst Totem",
				["comment"] = "",
			},
			{
				["id"] = 10467,
				["name"] = "Mana Tide Totem",
				["comment"] = "",
			},
			{
				["id"] = 97285,
				["name"] = "Wind Rush Totem",
				["comment"] = "",
			},
			{
				["id"] = 60561,
				["name"] = "Earthgrab Totem",
				["comment"] = "",
			},
			{
				["id"] = 2630,
				["name"] = "Earthbind Totem",
				["comment"] = "",
			},
			{
				["id"] = 105427,
				["name"] = "Totem of Wrath",
				["comment"] = "",
			},
			{
				["id"] = 97369,
				["name"] = "Liquid Magma Totem",
				["comment"] = "",
			},
			{
				["id"] = 62982,
				["name"] = "Mindbender",
				["comment"] = "",
			},
			{
				["id"] = 179867,
				["name"] = "Static Field Totem",
				["comment"] = "",
			},
			{
				["id"] = 194117,
				["name"] = "Stoneskin Totem",
				["comment"] = "",
			},
			{
				["id"] = 5923,
				["name"] = "Poison Cleansing Totem",
				["comment"] = "",
			},
			{
				["id"] = 194118,
				["name"] = "Tranquil Air Totem",
				["comment"] = "",
			},
			{
				["id"] = 17252,
				["name"] = "Felguard (Demo Pet)",
				["comment"] = "",
			},
			{
				["id"] = 417,
				["name"] = "Felhunter (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 1863,
				["name"] = "Succubus (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 89,
				["name"] = "Infernal (Warlock)",
				["comment"] = "",
			},
			{
				["id"] = 59712,
				["name"] = "Stone Bulwark Totem",
				["comment"] = "",
			},
			{
				["id"] = 225672,
				["name"] = "Shadow (Priest Re-Fear)",
				["comment"] = "",
			},
			{
				["id"] = 224466,
				["name"] = "Voidwraith (Priest)",
				["comment"] = "",
			},
			{
				["id"] = 19668,
				["name"] = "Shadowfiend",
				["comment"] = "",
			},
			{
				["id"] = 225409,
				["name"] = "Surging Totem",
				["comment"] = "",
			},
		},
		["fakeNameAnchorRelative"] = "TOP",
		["raidmarkIndicatorAnchor"] = "LEFT",
		["importantCCFullGlowRGB"] = {
			["a"] = 1,
			["b"] = 0,
			["g"] = 0.874,
			["r"] = 1,
		},
		["npBorderNonTargetColorRGB"] = {
			0,
			0,
			0,
			1,
		},
		["focusTargetIndicator"] = false,
		["personalNpBuffEnable"] = true,
		["healthNumbersHideSelf"] = false,
		["nameplateAurasPersonalXPos"] = 0,
		["classIndicator"] = false,
		["changeHealthbarHeight"] = true,
		["old_defaultNamePlateFontFlags"] = "SLUG",
		["executeIndicatorInRangeColor"] = false,
		["tankLosingAggroColorRGB"] = {
			1,
			0.47,
			0,
			1,
		},
		["totemIndicatorAnchor"] = "TOP",
		["partyPointerHealerReplace"] = true,
		["totemIndicatorYPos"] = 0,
		["friendlyHideHealthBar"] = true,
		["hideCastbarIcon"] = false,
		["nameplateAuraCompactedScale"] = 1,
		["healerIndicatorRedCrossEnemy"] = false,
		["bgIndicatorScale"] = 1,
		["defaultNamePlateFontFlags"] = "SLUG",
		["fadeOutNPCsAlpha"] = 0.2,
		["nameplateExtraClickHeight"] = 0,
		["castBarRecolor"] = false,
		["castBarChanneledColor"] = {
			0.4862745404243469,
			1,
			0.294117659330368,
		},
		["otherNpBuffFilterBlacklist"] = true,
		["combatIndicator"] = false,
		["nameplateShowFriendlyPlayerPets"] = "0",
		["partyPointerYPos"] = 0,
		["npAuraOtherRGB"] = {
			0,
			0,
			0,
		},
		["nameplateAuraEnlargedScale"] = 1,
		["nameplateStyle"] = "0",
		["nameplateAuraHideCooldownNumbers"] = false,
		["classicRetailNameplates"] = true,
		["classIndicatorFriendlyYPos"] = 0,
		["friendlyColorName"] = false,
		["useCustomTextureForSelfMana"] = false,
		["classIndicatorHideFriendlyHealthbar"] = false,
		["classIndicatorYPos"] = 0,
		["bgIndicatorAnchor"] = "BOTTOM",
		["bgIndicatorXPos"] = 0,
		["auraBlacklist"] = {
		},
		["customTextureSelf"] = "Solid",
		["absorbIndicatorTestMode"] = false,
		["defaultFontSize"] = 9,
		["combatIndicatorAnchor"] = "CENTER",
		["nameplateAuraHeightGap"] = 4,
		["nameplateNonTargetAlpha"] = 0.5,
		["hideNPC"] = false,
		["nameplateFriendlyHeight"] = 17.1875,
		["classIndicatorEnemy"] = false,
		["executeIndicatorYPos"] = 0,
		["hideNameplateAuras"] = false,
		["normalCastbarForEmpoweredCasts"] = true,
		["enemyColorNameRGB"] = {
			1,
			0,
			0,
		},
		["enableNpNonTargetAlphaFullAlphaCasting"] = false,
		["npcColorCaster"] = {
			0,
			0.749,
			1,
			1,
		},
		["executeIndicatorFriendly"] = false,
		["smallPetsInPvP"] = true,
		["nameplateMinAlphaDistance"] = "-100000",
		["overShields"] = false,
		["showInterruptsOnNameplateAuras"] = true,
		["combatIndicatorPlayersOnly"] = true,
		["highlightNpShadowOnMouseover"] = false,
		["friendlyNameplatesOnlyInWorld"] = false,
		["totemIndicatorXPos"] = 0,
		["totemIndicatorDefaultCooldownTextSize"] = 0.85,
		["classColorPersonalNameplate"] = true,
		["guildNameColorRGB"] = {
			0,
			1,
			0,
		},
		["healerIndicatorBgOnly"] = false,
		["nameplateAurasEnemyCenteredAnchor"] = false,
		["hideNPCArenaOnly"] = false,
		["personalNpdeBuffFilterBlacklist"] = true,
		["combatIndicatorArenaOnly"] = false,
		["bgIndicatorEnemyOnly"] = true,
		["nameplateDefaultLargeEnemyWidth"] = 154,
		["focusTargetIndicatorYPos"] = 0,
		["friendlyNameplatesOnlyInEpicBgs"] = false,
		["executeIndicatorInRangeColorRGB"] = {
			0,
			1,
			0.8,
			1,
		},
		["healerIndicatorEnemyScale"] = 1,
		["classIndicatorOnlyParty"] = false,
		["useCustomCastbarBGTexture"] = true,
		["healerIndicatorArenaOnly"] = false,
		["nameplateMaxScale"] = 1,
		["nameplateKeyAurasHorizontalGap"] = 5,
		["bitfields"] = {
			["nameplateFriendlyPlayerAuraDisplay"] = {
				["1"] = false,
				["3"] = true,
				["2"] = false,
			},
			["nameplateSimplifiedTypes"] = {
				["1"] = true,
				["4"] = true,
				["3"] = false,
				["2"] = true,
			},
			["nameplateStackingTypes"] = {
				["1"] = true,
				["2"] = false,
			},
			["nameplateEnemyPlayerAuraDisplay"] = {
				["1"] = true,
				["3"] = true,
				["2"] = true,
			},
			["nameplateEnemyNpcAuraDisplay"] = {
				["1"] = true,
				["3"] = true,
				["2"] = true,
			},
			["nameplateInfoDisplay"] = {
				["1"] = false,
				["3"] = false,
				["2"] = false,
			},
			["nameplateThreatDisplay"] = {
				["1"] = false,
				["3"] = false,
				["2"] = true,
			},
			["nameplateCastBarDisplay"] = {
				["1"] = true,
				["3"] = true,
				["2"] = true,
				["5"] = true,
				["4"] = true,
			},
		},
		["castBarFullTextWidth"] = false,
		["fakeNameYPos"] = -4,
		["personalNpdeBuffFilterAll"] = false,
		["alwaysHideEnemyCastbar"] = false,
		["healthNumbersNpcs"] = true,
		["importantBuffsOffensivesGlowRGB"] = {
			["a"] = 1,
			["b"] = 0,
			["g"] = 0.5,
			["r"] = 1,
		},
		["friendlyHideHealthBarNpc"] = true,
		["healthNumbersFriendly"] = false,
		["importantBuffsDefensivesGlow"] = true,
		["petIndicatorColorHealthbar"] = false,
		["nameplateAuraScale"] = "1",
		["npBorderNeutralColorRGB"] = {
			1,
			1,
			0,
			1,
		},
		["bgIndicatorTestMode"] = false,
		["targetIndicatorXPos"] = 0,
		["importantBuffsOffensivesGlow"] = true,
		["fakeNameXPos"] = 0,
		["partyPointerHighlight"] = false,
		["keyAurasImportantGlowOn"] = true,
		["sortDurationAuras"] = false,
		["focusTargetIndicatorColorName"] = false,
		["nameplateResourcePositionFix"] = true,
		["nameplateKeyAurasXPos"] = 0,
		["combatIndicatorScale"] = 1,
		["personalNpBuffFilterAll"] = false,
		["castbarQuickHide"] = false,
		["partyPointerHighlightScale"] = 1,
		["guildNameColor"] = false,
		["hideTargetHighlight"] = false,
		["nameplateAuraEnlargedSquare"] = true,
		["changeNameplateBorderSize"] = false,
		["anonMode"] = false,
		["npAuraPoisonRGB"] = {
			0,
			0.52,
			0.031,
		},
		["classIconHealerIconType"] = 2,
		["focusTargetIndicatorXPos"] = 0,
		["nameplatePersonalBorderSize"] = 1,
		["partyIndicatorModeFour"] = false,
		["colorNpcList"] = {
		},
		["partyPointerTargetIndicator"] = false,
		["friendlyNpdeBuffEnable"] = true,
		["arenaIndicatorModeFive"] = false,
		["npcTitleScale"] = 0.9,
		["combatIndicatorYPos"] = 0,
		["useCustomTextureForEnemy"] = true,
		["enableCastbarEmphasis"] = false,
		["healerIndicator"] = true,
		["partyPointerHealer"] = false,
		["useFakeName"] = true,
		["hideResourceFrame"] = false,
		["targetIndicatorTexture"] = "Checkered (BBP)",
		["ghostAuras"] = {
		},
		["importantCCRoot"] = true,
		["healerIndicatorEnemyAnchor"] = "TOPRIGHT",
		["nameplateShowFriendlyPlayerTotems"] = "0",
		["castBarRecolorInterrupt"] = false,
		["healthNumbersTargetOnly"] = false,
		["healthNumbersPercentSymbol"] = false,
		["totemIndicatorColorHealthBar"] = true,
		["npcColorBoss"] = {
			0.3607843220233917,
			0.03921568766236305,
			0.7882353663444519,
			1,
		},
		["arenaIndicatorTestMode"] = false,
		["nameplateAuraBuffSelfScale"] = 1,
		["castBarInterruptHighlighterDontInterruptRGB"] = {
			0,
			0,
			0,
		},
		["healthNumbersClassColor"] = false,
		["nameplateDefaultLargeFriendlyWidth"] = 154,
		["importantBuffsMobility"] = true,
		["personalNpdeBuffFilterWatchList"] = true,
		["totemIndicatorEnemyOnly"] = true,
		["fakeNameFriendlyYPos"] = 0,
		["nameplateSelfAlpha"] = "0.75",
		["npAuraMagicRGB"] = {
			0.13,
			0.44,
			1,
		},
		["nameplateAurasCenteredAnchor"] = false,
		["classIndicatorAlpha"] = 1,
		["castBarShieldXPos"] = 0,
		["largeNameplates"] = true,
		["absorbIndicatorEnemyOnly"] = false,
		["executeIndicatorTargetOnly"] = false,
		["friendlyNameplateClickthrough"] = false,
		["nameplateOverlapH"] = 0.8,
		["healthNumbers"] = true,
		["showLastNameNpc"] = false,
		["onlyPandemicAuraMine"] = true,
		["nameplateShowEnemyMinions"] = "0",
		["questIndicatorYPos"] = 0,
		["raidmarkIndicatorFullAlpha"] = false,
		["wasOnLoadingScreen"] = false,
		["petIndicatorAnchor"] = "CENTER",
		["enlargeAllImportantBuffs"] = true,
		["importantCCFull"] = true,
		["friendlyNameScale"] = 1,
		["classIconSquareBorderFriendly"] = false,
		["importantBuffsDefensivesGlowRGB"] = {
			["a"] = 1,
			["b"] = 0.945,
			["g"] = 0.662,
			["r"] = 1,
		},
		["castBarShieldScale"] = 1,
		["testAllEnabledFeatures"] = false,
		["hideNPCSecondaryShowMurloc"] = true,
		["executeIndicatorAlwaysOn"] = false,
		["healerIndicatorXPos"] = 0,
		["enemyNameScale"] = 1,
		["totemIndicatorTestMode"] = false,
		["hideLevelFrame"] = true,
		["friendlyNpdeBuffFilterBlacklist"] = true,
		["defaultLargeNamePlateFontFlags"] = "",
		["raidmarkIndicatorScale"] = 1,
		["partyPointerHealerScale"] = 1.1,
		["nameplateAuraTestMode"] = false,
		["nameplateAuraCountScale"] = 1,
		["combatIndicatorSap"] = false,
		["executeIndicatorNotOnFullHp"] = false,
		["focusTargetIndicatorAnchor"] = "TOPRIGHT",
		["nameplateDebuffPadding"] = 12,
		["nameplateAuraPlayersOnlyShowTarget"] = false,
		["enableNpNonTargetAlphaTargetOnly"] = true,
		["focusTargetIndicatorScale"] = 1,
		["defaultNamePlateOutlinedFontFlags"] = "OUTLINE, SLUG",
		["healthNumbersAnchor"] = "CENTER",
		["customTextureFriendly"] = "GennUI B",
		["friendlyNpBuffFilterImportantBuffs"] = false,
		["nameplateDefaultFriendlyWidth"] = 110,
		["setCVarAcrossAllCharacters"] = true,
		["nameplateKeyAurasYPos"] = 0,
		["healerIndicatorTestMode"] = false,
		["recolorTempHpLoss"] = false,
		["partyIndicatorModeThree"] = false,
		["partyPointerOnlyParty"] = false,
		["enemyHealthBarColorRGB"] = {
			1,
			0,
			0,
		},
		["hideNpAuraSwipe"] = false,
		["totemIndicator"] = false,
		["castBarInterruptHighlighterStartTime"] = 0.8,
		["customCastbarNonInterruptibleTexture"] = "GennUI B",
		["castBarCastColor"] = {
			1,
			0.8431373238563538,
			0.2000000178813934,
		},
		["personalNpBuffFilterBlacklist"] = true,
		["classIndicatorAlwaysShowPet"] = false,
		["nameplateOverlapVScale"] = 1.1,
		["enemyColorThreat"] = false,
		["healthNumbersTestMode"] = false,
		["raidmarkIndicatorYPos"] = 0,
		["partyIndicatorModeTwo"] = false,
		["personalNpdeBuffFilterCC"] = false,
		["nameplateShowFriendlyClassColor"] = "1",
		["friendlyNameplatesOnlyInBgs"] = false,
		["showTotemIndicatorCooldownSwipe"] = true,
		["nameplateResourceXPos"] = 0,
		["friendlyNameplatesOnlyInDungeons"] = false,
		["classIndicatorUpdated2"] = true,
		["hideNPCHideOthersPets"] = true,
		["partyPointerAnchor"] = "TOP",
		["partyPointer"] = true,
		["partyPointerTexture"] = 3,
		["enemyClassColorName"] = false,
		["healthNumbersPlayers"] = true,
		["fakeNameFriendlyXPos"] = 0,
		["old_defaultNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
		["nameplateOverlapV"] = 1.1,
		["dpsOrHealTargetAggroColorRGB"] = {
			1,
			0.4705882668495178,
			0,
			1,
		},
		["personalNpBuffFilterWatchList"] = true,
		["executeIndicatorUseTexture"] = false,
		["classIconSquareBorder"] = false,
		["showCircleOnArenaID"] = false,
		["petIndicatorScale"] = 1,
		["friendlyHealthBarColor"] = false,
		["importantCCSilenceGlowRGB"] = {
			["a"] = 1,
			["b"] = 0,
			["g"] = 0.874,
			["r"] = 1,
		},
		["partyPointerBgOnly"] = false,
		["classIndicatorOnlyHealer"] = false,
		["otherNpBuffEnable"] = false,
		["healthNumbersPercentage"] = false,
		["classIconAlwaysShowHealer"] = false,
		["healthNumbersJustify"] = "CENTER",
		["classIndicatorHideName"] = false,
		["friendlyNameplateNonstackable"] = true,
		["executeIndicatorAnchor"] = "LEFT",
		["nameplateSelfWidth"] = 185,
		["nameplateMotionSpeedScale"] = 0.03,
		["enableCastbarCustomization"] = true,
		["friendlyNpBuffEmphasisedBorder"] = false,
		["nameplateOccludedAlphaMult"] = "0.4",
		["healthNumbersCurrentFull"] = false,
		["targetIndicatorHideIcon"] = false,
		["classIndicatorCCAuras"] = true,
		["friendlyNpBuffFilterOnlyMe"] = false,
		["arenaIDScale"] = 1,
		["enemyHealthBarColorNpcOnly"] = false,
		["hideNameDuringCast"] = false,
		["classIndicatorPinMode"] = false,
		["executeIndicatorTestMode"] = false,
		["healthNumbersSwapped"] = false,
		["friendlyNpdeBuffFilterOnlyMe"] = false,
		["nameplateKeyAurasAnchor"] = "RIGHT",
		["nameplateAuraKeyAuraPositionEnabled"] = false,
		["importantCCDisarmGlowRGB"] = {
			["a"] = 1,
			["b"] = 0,
			["g"] = 0.874,
			["r"] = 1,
		},
		["partyPointerScale"] = 1.3,
		["arenaSpecYPos"] = 0,
		["exportVersion"] = "BBP: v1.9.7 WoW: 12.0.1",
		["hideCastbarBorderShield"] = false,
		["otherNpBuffPurgeGlow"] = false,
		["friendlyNpBuffEnable"] = false,
		["version"] = "1.00",
		["nameplateAuraPlayersOnly"] = false,
		["onlyShowHighlightedNpShadow"] = false,
		["petIndicatorXPos"] = 0,
		["personalNpTRP3Color"] = false,
		["toggleNamesOffDuringPVE"] = false,
		["enableNpNonFocusAlpha"] = false,
		["castbarEventsOn"] = false,
		["showNameplateShadow"] = false,
		["doNotHideFriendlyHealthbarInPve"] = false,
		["fadeOutNPCOnlyFadeSecondaryPets"] = true,
		["nameplateMotionSpeed"] = 0.025,
		["friendlyHealthBarColorNpc"] = false,
		["defaultNpAuraCdSize"] = 0.5,
		["focusTargetIndicatorColorNameplateRGB"] = {
			1,
			1,
			1,
		},
		["nameplateAuraAnchor"] = "BOTTOMLEFT",
		["customCastbarTexture"] = "GennUI B",
		["targetHighlightFix"] = false,
		["nameplateAuraRowFriendlyAmount"] = 5,
		["nameplateMaxAlphaDistance"] = "40",
		["changeNpHpBgColor"] = false,
		["partyPointerClassColor"] = true,
		["buffIconAnchor"] = "LEFT",
		["castBarIconAnchor"] = "LEFT",
		["nameplateGeneralHpHeightScale"] = 18,
		["hpHeightEnemyScale"] = 16,
		["nameplateResourceDoNotRaiseAuras"] = false,
		["classIconEnemyHealIcon"] = true,
		["friendlyNpdeBuffFilterBlizzard"] = false,
		["arenaIndicatorModeOne"] = false,
		["hasSaved"] = true,
		["nameplateDebuffPaddingScale"] = 12,
		["npcColorTrivial"] = {
			0.37,
			0.12,
			0.1,
			1,
		},
		["npcColorMinus"] = {
			0.63,
			0.28,
			0.17,
			1,
		},
		["maxAurasOnNameplate"] = 12,
		["friendlyNameplatesOnlyInArena"] = false,
		["firstSaveComplete"] = true,
		["colorNPCEverywhere"] = false,
	}
end
