local GennUI = ...
local LS = LibStub("AceAddon-3.0")
GennUI = LS:GetAddon("GennUI", "AceConsole-3.0", "AceHook-3.0")

function GennUI:LoadDBMProfile()
    local profileName = "GennUI"
    if (DBM_AllSavedOptions and DBM_AllSavedOptions[profileName]) and (DBT_AllPersistentOptions and DBT_AllPersistentOptions[profileName]) then
        DBM:ApplyProfile('GennUI')
    else
        DBM:CreateProfile('GennUI')
        DBM_AllSavedOptions = {
            ["Default"] = {
                ["DontShowFarWarnings"] = true,
                ["SpamSpecRolestack"] = false,
                ["DontRestoreIcons"] = false,
                ["EnableTooltip"] = false,
                ["DontShowNameplateIcons"] = false,
                ["SpecialWarningFlash5"] = true,
                ["PrivateAurasCoTankWidth"] = 60,
                ["NPIconTextMaxLen"] = 7,
                ["EnableModels"] = true,
                ["PrivateAurasPlayerGrowDirection"] = "RIGHT",
                ["DontPlayTrivialSpecialWarningSound"] = true,
                ["SWarnNameInNote"] = true,
                ["SpecialWarningSound2"] = 543587,
                ["InfoFramePoint"] = "LEFT",
                ["EventSoundMusicCombined"] = false,
                ["LogDelves"] = false,
                ["PrivateAurasPlayerUpscaleDuration"] = true,
                ["LatencyPosition"] = {
                    "RIGHT",
                    -150,
                    0,
                },
                ["WorldBossAlert"] = false,
                ["PrivateAurasPlayerHideBorder"] = false,
                ["SpamSpecInformationalOnly"] = false,
                ["WorldBuffAlert"] = false,
                ["SpamSpecRoledispel"] = false,
                ["DisableMusic"] = false,
                ["ShowGuildMessages"] = true,
                ["RaidDifficultyChangedAlertRaidOnly"] = true,
                ["WarningPoint"] = "CENTER",
                ["SpecialWarningSound3"] = "Interface\\AddOns\\DBM-Core\\sounds\\AirHorn.ogg",
                ["DontShowTargetAnnouncements"] = true,
                ["ShowWarningsInChat"] = true,
                ["InfoFrameFontStyle"] = "None",
                ["WarningFontStyle"] = "None",
                ["ChatFrame"] = "DEFAULT_CHAT_FRAME",
                ["CastNPIconGlowBehavior"] = 1,
                ["PrivateAurasCoTankHideTooltip"] = false,
                ["RangeFrameRadarX"] = 458.2907409667969,
                ["LogCurrentRaids"] = true,
                ["InfoFrameCols"] = 0,
                ["PrivateAurasCoTankYOffset"] = 150,
                ["NPIconTimerEnabled"] = true,
                ["LatencyThreshold"] = 250,
                ["ShowGuildMessagesPlus"] = false,
                ["LFDEnhance"] = true,
                ["PrivateAurasCoTankAnchor"] = "CENTER",
                ["LogCurrentMythicRaids"] = true,
                ["PrivateAurasPlayerHideTooltip"] = false,
                ["DontPlayPrivateAuraSound"] = false,
                ["HideBossEmoteFrame2"] = true,
                ["DisableChatBubbles"] = false,
                ["HideObjectivesFrame"] = true,
                ["SpecialWarningShortText"] = true,
                ["DontShowPTText"] = false,
                ["FilterBInterruptHealer"] = false,
                ["SpecialWarningFontSize2"] = 35,
                ["SpecialWarningFlashCol5"] = {
                    0.2,
                    1,
                    1,
                },
                ["NewsMessageShown2"] = 2,
                ["NPIconTextFont"] = "standardFont",
                ["EventSoundPullTimer"] = "None",
                ["DungeonDifficultyChangedAlert"] = false,
                ["NPIconTimerFontStyle"] = "None",
                ["SpecialWarningVibrate2"] = false,
                ["SpecialWarningFlashCount2"] = 1,
                ["NPAuraText"] = true,
                ["EventSoundDungeonBGM"] = "None",
                ["DisableRaidIcons"] = false,
                ["SpecialWarningFlashDura3"] = 1,
                ["WarningShortText"] = true,
                ["SpecialWarningFlash4"] = true,
                ["DisableSFX"] = false,
                ["SpecialWarningFlashDura4"] = 0.7,
                ["SpecialWarningFlashCol3"] = {
                    1,
                    0,
                    0,
                },
                ["ModelSoundValue"] = "Short",
                ["SpecialWarningY"] = 75,
                ["ReplaceMyConfigOnOverride"] = false,
                ["LogTrivialDungeons"] = false,
                ["RaidWarningSound"] = 566558,
                ["CustomSounds"] = 0,
                ["ShortTimerText"] = true,
                ["LogCurrentMPlus"] = true,
                ["DontPlayPTCountdown"] = false,
                ["HideDBMWarnings"] = false,
                ["DoNotLogLFG"] = true,
                ["WarningIconLeft"] = true,
                ["RangeFrameLocked"] = false,
                ["HealthWarningLow"] = false,
                ["SpamSpecRolegtfo"] = false,
                ["SpecialWarningFlashDura2"] = 0.4,
                ["LogTrivialRaids"] = false,
                ["HideDBMBars"] = false,
                ["EnableTooltipHeader"] = true,
                ["VPReplacesSADefault"] = true,
                ["IgnoreBlizzAPI"] = false,
                ["GroupOptionsExcludeIcon"] = false,
                ["FilterBTargetFocus"] = true,
                ["RecordOnlyBosses"] = false,
                ["PrivateAurasCoTankUpscaleDuration"] = true,
                ["ShowBerserkWarnings"] = true,
                ["DontPlayCountdowns"] = false,
                ["OverrideBossIcon"] = false,
                ["SpecialWarningFlashAlph1"] = 0.3,
                ["ShowDefeatMessage"] = true,
                ["FilterCrowdControl"] = true,
                ["InfoFrameShowSelf"] = false,
                ["WarningFontShadow"] = true,
                ["PrivateAurasPlayerSpacing"] = -1,
                ["DontShowBossTimers"] = false,
                ["SpecialWarningFontStyle"] = "THICKOUTLINE",
                ["InfoFrameLines"] = 0,
                ["PrivateAurasPlayerAnchor"] = "CENTER",
                ["WarningIconChat"] = true,
                ["HideGuildChallengeUpdates"] = true,
                ["ShowPizzaMessage"] = true,
                ["RangeFrameSound2"] = "none",
                ["HideTooltips"] = false,
                ["LogCurrentMythicZero"] = false,
                ["HasShownMidnightPopup"] = true,
                ["PrivateAurasCoTankSpacing"] = -1,
                ["GUIWidth"] = 800,
                ["NPIconTextFontSize"] = 10,
                ["EventSoundMusic"] = "None",
                ["LogTWRaids"] = false,
                ["NoTimerOverridee"] = true,
                ["HelpMessageVersion"] = 3,
                ["PrivateAurasTextAnchorEnabled"] = true,
                ["SpecialWarningFlashAlph2"] = 0.3,
                ["DontShowHudMap2"] = false,
                ["SpecialWarningFlashCount4"] = 2,
                ["ShowSWarningsInChat"] = true,
                ["HideMovieDuringFight"] = true,
                ["RangeFrameRadarY"] = -226.9063720703125,
                ["OverrideBossAnnounce"] = false,
                ["CoreSavedRevision"] = 20260226080850,
                ["RangeFrameX"] = 50,
                ["NPIconGrowthDirection"] = "CENTER",
                ["RangeFrameY"] = -50,
                ["SpecialWarningFlashAlph3"] = 0.4,
                ["FilterTInterruptHealer"] = false,
                ["FakeBWVersion"] = false,
                ["ZoneCombatSyncing"] = false,
                ["WarningAlphabetical"] = true,
                ["SpecialWarningPoint"] = "CENTER",
                ["FilterBInterruptCooldown"] = true,
                ["CheckGear"] = true,
                ["NPIconTextEnabled"] = true,
                ["SpecialWarningX"] = 0,
                ["DontShowPT2"] = false,
                ["PrivateAurasPlayerRelativeTo"] = "CENTER",
                ["MoviesSeen"] = {
                },
                ["ShowQueuePop"] = true,
                ["SpecialWarningFlashCol4"] = {
                    1,
                    0,
                    1,
                },
                ["DebugMode"] = false,
                ["DisableGuildStatus"] = false,
                ["ShowReminders"] = true,
                ["ChosenVoicePack2"] = "VEM",
                ["NPIconTimerFont"] = "standardFont",
                ["AFKHealthWarning2"] = false,
                ["SpecialWarningVibrate1"] = false,
                ["EventSoundEngage2"] = "None",
                ["InfoFrameY"] = -199.7179107666016,
                ["SpecialWarningSound"] = 569200,
                ["WarningIconRight"] = true,
                ["UseSoundChannel"] = "Master",
                ["ShowRespawn"] = true,
                ["HideMovieNonInstanceAnywhere"] = false,
                ["DontAutoGossip"] = false,
                ["PrivateAurasCoTankRelativeTo"] = "CENTER",
                ["LeavingCombatAlert"] = false,
                ["AlwaysKeepNPs"] = true,
                ["AlwaysShowSpeedKillTimer2"] = false,
                ["NoAnnounceOverride"] = true,
                ["DisableSWSound"] = false,
                ["DebugLevel"] = 1,
                ["FilterTrashWarnings2"] = true,
                ["BadTimerAlert"] = false,
                ["KeystonesPosition"] = {
                    "LEFT",
                    30,
                    0,
                },
                ["HideGarrisonToasts"] = true,
                ["RangeFramePoint"] = "CENTER",
                ["SpecialWarningFlashDura1"] = 0.3,
                ["SpecialWarningFontShadow"] = false,
                ["NPIconTimerFontSize"] = 18,
                ["HideMovieInstanceAnywhere"] = true,
                ["DontShowPrivateAuraFrame"] = false,
                ["DontShowPTNoID"] = false,
                ["RoleSpecAlert"] = true,
                ["SpecialWarningFlashCol1"] = {
                    1,
                    1,
                    0,
                },
                ["PrivateAurasPlayerWidth"] = 60,
                ["SpecialWarningFont"] = "standardFont",
                ["PrivateAurasCoTankGrowDirection"] = "LEFT",
                ["SpecialWarningVibrate4"] = true,
                ["SWarnClassColor"] = true,
                ["FilterDispel"] = true,
                ["UseNameplateHandoff"] = true,
                ["DontShowNameplateIconsCast"] = false,
                ["CastNPIconGlowType2"] = 4,
                ["DontShowEventTimers"] = false,
                ["PrivateAurasCoTankEnabled"] = true,
                ["EventMusicMythicFilter"] = true,
                ["RaidDifficultyChangedAlert"] = true,
                ["RangeFrameUpdates"] = "Average",
                ["OverrideBossSay"] = false,
                ["PTCountThreshold2"] = 5,
                ["CountdownVoice2"] = "Kolt",
                ["VPReplacesAnnounce"] = true,
                ["LogChallenges"] = false,
                ["oRA3AnnounceConsumables"] = false,
                ["PrivateAurasTextAnchorXOffset"] = 0,
                ["NPIconAnchorPoint"] = "TOP",
                ["EnableWBSharing"] = true,
                ["ArrowPosX"] = 0,
                ["FilterTInterruptCooldown"] = true,
                ["NPIconGlowBehavior"] = 1,
                ["LogTWDungeons"] = false,
                ["DurabilityPosition"] = {
                    "RIGHT",
                    -150,
                    0,
                },
                ["SpecialWarningFlash2"] = true,
                ["PrivateAurasTextAnchorAnchor"] = "TOP",
                ["NPIconSize"] = 30,
                ["PrivateAurasPlayerHeight"] = 60,
                ["PrivateAurasPlayerLimit"] = 5,
                ["DontShowTrashTimers"] = false,
                ["GUIX"] = 0,
                ["LogCurrentHeroic"] = false,
                ["WarningY"] = 260,
                ["PrivateAurasPlayerScale"] = 3,
                ["HideMovieOnlyAfterSeen"] = true,
                ["WarningColors"] = {
                    {
                        ["r"] = 0.41,
                        ["g"] = 0.8,
                        ["b"] = 0.94,
                    },
                    {
                        ["r"] = 0.95,
                        ["g"] = 0.95,
                        ["b"] = 0,
                    },
                    {
                        ["r"] = 1,
                        ["g"] = 0.5,
                        ["b"] = 0,
                    },
                    {
                        ["r"] = 1,
                        ["g"] = 0.1,
                        ["b"] = 0.1,
                    },
                },
                ["RLReadyCheckSound"] = true,
                ["SWarningAlphabetical"] = true,
                ["AutoReplySound"] = true,
                ["BlockNoteShare"] = false,
                ["DisableAmbiance"] = false,
                ["DontPlaySpecialWarningSound"] = false,
                ["PrivateAurasCoTankHideBorder"] = false,
                ["SpecialWarningFlashDura5"] = 1,
                ["SpecialWarningSound4"] = 552035,
                ["DontSendBossGUIDs"] = false,
                ["WarningFont"] = "standardFont",
                ["GroupOptionsExcludePA"] = false,
                ["DontShowInfoFrame"] = false,
                ["DontShowNameplateIconsCD"] = false,
                ["SpecialWarningFontCol"] = {
                    1,
                    0.7,
                    0,
                },
                ["DontDoSpecialWarningVibrate"] = false,
                ["CDNPIconGlowType"] = 1,
                ["PrivateAurasCoTankScale"] = 3,
                ["PrivateAurasTextAnchorScale"] = 1.8,
                ["DontRestoreRange"] = false,
                ["SpecialWarningVibrate3"] = true,
                ["SpecialWarningFlashCount3"] = 3,
                ["DontShowSpecialWarningText"] = false,
                ["WhisperStats"] = false,
                ["SilentMode"] = false,
                ["FilterInterruptNoteName"] = false,
                ["DontShowBossAnnounces"] = false,
                ["SpecialWarningFlashAlph5"] = 0.5,
                ["SpecialWarningDuration2"] = 1.5,
                ["ArrowPoint"] = "TOP",
                ["InfoFrameX"] = 342.2388916015625,
                ["ShowEngageMessage"] = true,
                ["RangeFrameSound1"] = "none",
                ["FilterTTargetFocus"] = true,
                ["WarningFontSize"] = 20,
                ["EventSoundVictory2"] = "Interface\\AddOns\\DBM-Core\\sounds\\Victory\\SmoothMcGroove_Fanfare.ogg",
                ["AutoExpandSpellGroups"] = false,
                ["LastRevision"] = 0,
                ["PrivateAurasPlayerXOffset"] = 0,
                ["SettingsMessageShown"] = true,
                ["ArrowPosY"] = -150,
                ["EnableTooltipInCombat"] = true,
                ["SpecialWarningFlashAlph4"] = 0.4,
                ["SpecialWarningFlash1"] = true,
                ["DontSetIcons"] = false,
                ["EnteringCombatAlert"] = false,
                ["PrivateAurasTextAnchorRelativeTo"] = "TOP",
                ["CountdownVoice"] = "Corsica",
                ["SpamSpecRoledefensive"] = false,
                ["SpecialWarningVibrate5"] = true,
                ["CountdownVoice3"] = "Smooth",
                ["AutoRespond"] = true,
                ["NPIconSpacing"] = 0,
                ["DisableStatusWhisper"] = false,
                ["EventDungMusicMythicFilter"] = true,
                ["GUIY"] = 31.72655296325684,
                ["RangeFrameFrames"] = "radar",
                ["SpecialWarningFlashCount5"] = 3,
                ["WarningDuration2"] = 1.5,
                ["SpecialWarningIcon"] = true,
                ["InfoFrameFont"] = "standardFont",
                ["RangeFrameRadarPoint"] = "LEFT",
                ["WarningX"] = 0,
                ["GUIPoint"] = "LEFT",
                ["SpamSpecRoletaunt"] = false,
                ["SpamSpecRolesoak"] = false,
                ["ShowAllVersions"] = true,
                ["SpamSpecRoleswitch"] = false,
                ["DontShowUserTimers"] = false,
                ["DontShowRangeFrame"] = false,
                ["EventSoundWipe"] = "None",
                ["AutologBosses"] = false,
                ["DontShowSpecialWarningFlash"] = false,
                ["InfoFrameFontSize"] = 12,
                ["NPIconOffsetX"] = 0,
                ["WorldBossNearAlert"] = false,
                ["ShowWAKeys"] = true,
                ["GUIHeight"] = 600,
                ["DebugSound"] = true,
                ["AutoAcceptFriendInvite"] = false,
                ["NPIconOffsetY"] = 20,
                ["SpecialWarningFlashCount1"] = 1,
                ["PullVoice"] = "Corsica",
                ["SpecialWarningSound5"] = 554236,
                ["DontSendYells"] = false,
                ["SpamSpecRoleinterrupt"] = false,
                ["AdvancedAutologBosses"] = false,
                ["NPIconTextFontStyle"] = "None",
                ["SpecialWarningFlash3"] = true,
                ["HideBlizzardTimeline"] = true,
                ["Enabled"] = true,
                ["OverrideBossTimer"] = false,
                ["AutoExpandSpellGroups2"] = true,
                ["FilterVoidFormSay2"] = false,
                ["EventMusicNoBuiltIn"] = false,
                ["PrivateAurasTextAnchorYOffset"] = -200,
                ["PrivateAurasCoTankXOffset"] = -150,
                ["PrivateAurasCoTankHeight"] = 60,
                ["StripServerName"] = true,
                ["NoCombatScanningFeatures"] = false,
                ["PrivateAurasPlayerYOffset"] = 150,
                ["PrivateAurasCoTankLimit"] = 5,
                ["PrivateAurasPlayerEnabled"] = true,
                ["InfoFrameLocked"] = false,
                ["AutoAcceptGuildInvite"] = false,
                ["SpecialWarningFlashCol2"] = {
                    1,
                    0.5,
                    0,
                },
            },
            ["GennUI"] = {
                ["DontShowFarWarnings"] = true,
                ["SpamSpecRolestack"] = false,
                ["DontRestoreIcons"] = false,
                ["EnableTooltip"] = false,
                ["DontShowNameplateIcons"] = false,
                ["SpecialWarningFlash5"] = true,
                ["PrivateAurasCoTankWidth"] = 50,
                ["NPIconTextMaxLen"] = 7,
                ["SpecialWarningFlash1"] = true,
                ["PrivateAurasPlayerGrowDirection"] = "RIGHT",
                ["DontPlayTrivialSpecialWarningSound"] = true,
                ["FilterTInterruptCooldown"] = true,
                ["SpecialWarningSound2"] = 543587,
                ["InfoFramePoint"] = "LEFT",
                ["OverrideBossSay"] = false,
                ["LogDelves"] = false,
                ["PrivateAurasPlayerUpscaleDuration"] = true,
                ["LatencyPosition"] = {
                    "RIGHT",
                    -150,
                    0,
                },
                ["WorldBossAlert"] = false,
                ["PrivateAurasPlayerHideBorder"] = false,
                ["SpamSpecInformationalOnly"] = false,
                ["WorldBuffAlert"] = false,
                ["SpamSpecRoledispel"] = false,
                ["DisableMusic"] = false,
                ["ShowGuildMessages"] = true,
                ["RaidDifficultyChangedAlertRaidOnly"] = true,
                ["ShowAllVersions"] = true,
                ["SpecialWarningSound3"] = "Interface\\AddOns\\DBM-Core\\sounds\\AirHorn.ogg",
                ["SpamSpecRolesoak"] = false,
                ["ShowWarningsInChat"] = true,
                ["InfoFrameFontStyle"] = "None",
                ["WarningFontStyle"] = "OUTLINE",
                ["ChatFrame"] = "DEFAULT_CHAT_FRAME",
                ["CastNPIconGlowBehavior"] = 1,
                ["PrivateAurasCoTankHideTooltip"] = false,
                ["RangeFrameRadarX"] = 458.2907409667969,
                ["LogCurrentRaids"] = true,
                ["InfoFrameCols"] = 0,
                ["PrivateAurasCoTankYOffset"] = -22,
                ["NPIconTimerEnabled"] = true,
                ["LatencyThreshold"] = 250,
                ["ShowGuildMessagesPlus"] = false,
                ["LFDEnhance"] = true,
                ["PrivateAurasCoTankAnchor"] = "CENTER",
                ["LogCurrentMythicRaids"] = true,
                ["PrivateAurasPlayerHideTooltip"] = false,
                ["DontPlayPrivateAuraSound"] = false,
                ["RLReadyCheckSound"] = true,
                ["DisableChatBubbles"] = false,
                ["ShowWAKeys"] = true,
                ["SpecialWarningShortText"] = true,
                ["DontShowPTText"] = false,
                ["FilterBInterruptHealer"] = false,
                ["SpecialWarningFontSize2"] = 35,
                ["SpecialWarningFlashCol5"] = {
                    0.2,
                    1,
                    1,
                },
                ["NewsMessageShown2"] = 2,
                ["NPIconTextFont"] = "standardFont",
                ["EventSoundPullTimer"] = "None",
                ["DungeonDifficultyChangedAlert"] = false,
                ["NPIconTimerFontStyle"] = "None",
                ["SpecialWarningVibrate2"] = false,
                ["SpecialWarningFlashCount2"] = 1,
                ["NPAuraText"] = true,
                ["EventSoundDungeonBGM"] = "None",
                ["AutoAcceptGuildInvite"] = false,
                ["SpecialWarningFlashDura3"] = 1,
                ["WarningShortText"] = true,
                ["SpecialWarningFlash4"] = true,
                ["DisableSFX"] = false,
                ["SpecialWarningFlashDura4"] = 0.7,
                ["SpecialWarningFlashCol3"] = {
                    1,
                    0,
                    0,
                },
                ["ModelSoundValue"] = "Short",
                ["SpecialWarningY"] = 75,
                ["RangeFrameUpdates"] = "Average",
                ["LogTrivialDungeons"] = false,
                ["RaidWarningSound"] = 566558,
                ["CustomSounds"] = 0,
                ["ShortTimerText"] = true,
                ["LogCurrentMPlus"] = true,
                ["DontPlayPTCountdown"] = false,
                ["HideDBMWarnings"] = false,
                ["DoNotLogLFG"] = true,
                ["WarningIconLeft"] = true,
                ["RangeFrameLocked"] = false,
                ["HealthWarningLow"] = false,
                ["SpamSpecRolegtfo"] = false,
                ["SpecialWarningFlashDura2"] = 0.4,
                ["LogTrivialRaids"] = false,
                ["HideDBMBars"] = false,
                ["EnableTooltipHeader"] = true,
                ["VPReplacesSADefault"] = true,
                ["IgnoreBlizzAPI"] = false,
                ["GroupOptionsExcludeIcon"] = false,
                ["FilterBTargetFocus"] = true,
                ["RecordOnlyBosses"] = false,
                ["PrivateAurasCoTankUpscaleDuration"] = true,
                ["ShowBerserkWarnings"] = true,
                ["DontPlayCountdowns"] = false,
                ["OverrideBossIcon"] = false,
                ["SpecialWarningFlashAlph1"] = 0.3,
                ["ShowDefeatMessage"] = true,
                ["FilterCrowdControl"] = true,
                ["InfoFrameShowSelf"] = false,
                ["WarningFontShadow"] = true,
                ["PrivateAurasPlayerSpacing"] = -1,
                ["DontShowBossTimers"] = false,
                ["SpecialWarningFontStyle"] = "OUTLINE",
                ["InfoFrameLines"] = 0,
                ["PrivateAurasPlayerAnchor"] = "CENTER",
                ["WarningIconChat"] = true,
                ["HideGuildChallengeUpdates"] = true,
                ["ShowPizzaMessage"] = true,
                ["RangeFrameSound2"] = "none",
                ["HideTooltips"] = false,
                ["LogCurrentMythicZero"] = false,
                ["HasShownMidnightPopup"] = true,
                ["PrivateAurasCoTankSpacing"] = -1,
                ["GUIWidth"] = 800,
                ["NPIconTextFontSize"] = 10,
                ["EventSoundMusic"] = "None",
                ["LogTWRaids"] = false,
                ["NoTimerOverridee"] = true,
                ["HelpMessageVersion"] = 3,
                ["PrivateAurasTextAnchorEnabled"] = true,
                ["SpecialWarningFlashAlph2"] = 0.3,
                ["DontShowHudMap2"] = false,
                ["SpecialWarningFlashCount4"] = 2,
                ["ShowSWarningsInChat"] = true,
                ["SpamSpecRoledefensive"] = false,
                ["RangeFrameRadarY"] = -226.9063720703125,
                ["OverrideBossAnnounce"] = false,
                ["CoreSavedRevision"] = 20260226080850,
                ["RangeFrameX"] = 50,
                ["NPIconGrowthDirection"] = "CENTER",
                ["RangeFrameY"] = -50,
                ["SpecialWarningFlashAlph3"] = 0.4,
                ["FilterTInterruptHealer"] = false,
                ["FakeBWVersion"] = false,
                ["ZoneCombatSyncing"] = false,
                ["WarningAlphabetical"] = true,
                ["SpamSpecRoletaunt"] = false,
                ["FilterBInterruptCooldown"] = true,
                ["CheckGear"] = true,
                ["NPIconTextEnabled"] = true,
                ["SpecialWarningX"] = 0,
                ["DontShowPT2"] = false,
                ["PrivateAurasPlayerRelativeTo"] = "CENTER",
                ["MoviesSeen"] = {
                    ["2238Heart of Amirdrassil"] = true,
                    ["2233Throne of the Firelord"] = true,
                    [1003] = true,
                },
                ["ShowQueuePop"] = true,
                ["SpecialWarningFlashCol4"] = {
                    1,
                    0,
                    1,
                },
                ["DebugMode"] = false,
                ["DisableGuildStatus"] = false,
                ["ShowReminders"] = true,
                ["SpecialWarningFontCol"] = {
                    1,
                    0.7,
                    0,
                },
                ["NPIconTimerFont"] = "standardFont",
                ["AFKHealthWarning2"] = false,
                ["SpecialWarningVibrate1"] = false,
                ["EventSoundEngage2"] = "None",
                ["InfoFrameY"] = -199.7179107666016,
                ["SpecialWarningSound"] = 569200,
                ["OverrideBossTimer"] = false,
                ["UseSoundChannel"] = "Master",
                ["ShowRespawn"] = true,
                ["HideMovieNonInstanceAnywhere"] = false,
                ["EventSoundWipe"] = "None",
                ["PrivateAurasCoTankRelativeTo"] = "CENTER",
                ["LeavingCombatAlert"] = false,
                ["AlwaysKeepNPs"] = true,
                ["AlwaysShowSpeedKillTimer2"] = false,
                ["NoAnnounceOverride"] = true,
                ["FilterDispel"] = true,
                ["DebugLevel"] = 1,
                ["AutoReplySound"] = true,
                ["SpecialWarningFlashDura1"] = 0.3,
                ["KeystonesPosition"] = {
                    "LEFT",
                    30,
                    0,
                },
                ["HideGarrisonToasts"] = true,
                ["RangeFramePoint"] = "CENTER",
                ["WarningIconRight"] = true,
                ["SpecialWarningFontShadow"] = false,
                ["NPIconTimerFontSize"] = 18,
                ["NPIconOffsetX"] = 0,
                ["DontShowPrivateAuraFrame"] = false,
                ["PrivateAurasPlayerEnabled"] = true,
                ["DontShowRangeFrame"] = false,
                ["SpecialWarningFlashCol1"] = {
                    1,
                    1,
                    0,
                },
                ["PrivateAurasPlayerWidth"] = 50.68853759765625,
                ["PrivateAurasPlayerYOffset"] = 113,
                ["PrivateAurasCoTankEnabled"] = true,
                ["DontShowNameplateIconsCD"] = false,
                ["SWarnClassColor"] = true,
                ["SpamSpecRoleswitch"] = false,
                ["UseNameplateHandoff"] = true,
                ["DontShowNameplateIconsCast"] = false,
                ["DisableRaidIcons"] = false,
                ["SpecialWarningVibrate4"] = true,
                ["HideObjectivesFrame"] = true,
                ["HideBossEmoteFrame2"] = true,
                ["RaidDifficultyChangedAlert"] = true,
                ["DisableSWSound"] = false,
                ["HideMovieOnlyAfterSeen"] = true,
                ["PTCountThreshold2"] = 5,
                ["CountdownVoice2"] = "Kolt",
                ["VPReplacesAnnounce"] = true,
                ["LogChallenges"] = false,
                ["oRA3AnnounceConsumables"] = false,
                ["PrivateAurasTextAnchorXOffset"] = 0,
                ["WarningX"] = 0,
                ["NPIconAnchorPoint"] = "TOP",
                ["ArrowPosX"] = 0,
                ["HideMovieInstanceAnywhere"] = true,
                ["RoleSpecAlert"] = true,
                ["LogTWDungeons"] = false,
                ["DurabilityPosition"] = {
                    "RIGHT",
                    -150,
                    0,
                },
                ["AdvancedAutologBosses"] = false,
                ["PrivateAurasTextAnchorAnchor"] = "TOP",
                ["NPIconSize"] = 30,
                ["DontShowUserTimers"] = false,
                ["PrivateAurasPlayerLimit"] = 5,
                ["PrivateAurasPlayerHeight"] = 50.68853759765625,
                ["GUIX"] = -266.6662292480469,
                ["LogCurrentHeroic"] = false,
                ["DisableAmbiance"] = false,
                ["PrivateAurasPlayerScale"] = 3,
                ["CastNPIconGlowType2"] = 4,
                ["WarningColors"] = {
                    {
                        ["b"] = 0.94,
                        ["g"] = 0.8,
                        ["r"] = 0.41,
                    },
                    {
                        ["b"] = 0,
                        ["g"] = 0.95,
                        ["r"] = 0.95,
                    },
                    {
                        ["b"] = 0,
                        ["g"] = 0.5,
                        ["r"] = 1,
                    },
                    {
                        ["b"] = 0.1,
                        ["g"] = 0.1,
                        ["r"] = 1,
                    },
                },
                ["NPIconGlowBehavior"] = 1,
                ["SWarningAlphabetical"] = true,
                ["EnableWBSharing"] = true,
                ["BlockNoteShare"] = false,
                ["DontShowEventTimers"] = false,
                ["DontPlaySpecialWarningSound"] = false,
                ["PrivateAurasCoTankHideBorder"] = false,
                ["EventMusicNoBuiltIn"] = false,
                ["SpecialWarningPoint"] = "CENTER",
                ["WorldBossNearAlert"] = false,
                ["SpecialWarningFlashCount5"] = 3,
                ["RangeFrameRadarPoint"] = "LEFT",
                ["DontShowInfoFrame"] = false,
                ["DontDoSpecialWarningVibrate"] = false,
                ["DontAutoGossip"] = false,
                ["SWarnNameInNote"] = true,
                ["EnableModels"] = true,
                ["PrivateAurasCoTankScale"] = 3,
                ["PrivateAurasTextAnchorScale"] = 1.8,
                ["DontRestoreRange"] = false,
                ["FilterVoidFormSay2"] = false,
                ["SpecialWarningFlashCount3"] = 3,
                ["ArrowPosY"] = -150,
                ["WhisperStats"] = false,
                ["SilentMode"] = false,
                ["HideMovieDuringFight"] = true,
                ["InfoFrameX"] = 342.2388916015625,
                ["SpecialWarningFlashAlph5"] = 0.5,
                ["SpecialWarningDuration2"] = 1.5,
                ["ArrowPoint"] = "TOP",
                ["DontShowBossAnnounces"] = false,
                ["ShowEngageMessage"] = true,
                ["RangeFrameSound1"] = "none",
                ["FilterTTargetFocus"] = true,
                ["WarningFontSize"] = 20,
                ["EventSoundVictory2"] = "Interface\\AddOns\\DBM-Core\\sounds\\Victory\\SmoothMcGroove_Fanfare.ogg",
                ["AutoExpandSpellGroups"] = false,
                ["LastRevision"] = 0,
                ["GUIPoint"] = "TOPRIGHT",
                ["SettingsMessageShown"] = true,
                ["FilterInterruptNoteName"] = false,
                ["EnableTooltipInCombat"] = true,
                ["WarningFont"] = "Interface\\AddOns\\GennUI\\media\\fonts\\GennUI.ttf",
                ["SpecialWarningFlashCol2"] = {
                    1,
                    0.5,
                    0,
                },
                ["DontSetIcons"] = false,
                ["EnteringCombatAlert"] = false,
                ["PrivateAurasTextAnchorRelativeTo"] = "TOP",
                ["CountdownVoice"] = "Corsica",
                ["DontShowSpecialWarningText"] = false,
                ["SpecialWarningVibrate3"] = true,
                ["CountdownVoice3"] = "Smooth",
                ["AutoRespond"] = true,
                ["EventDungMusicMythicFilter"] = false,
                ["DisableStatusWhisper"] = false,
                ["NPIconSpacing"] = 0,
                ["GUIY"] = -85.09408569335938,
                ["RangeFrameFrames"] = "radar",
                ["CDNPIconGlowType"] = 1,
                ["SpecialWarningVibrate5"] = true,
                ["SpecialWarningIcon"] = true,
                ["InfoFrameFont"] = "Interface\\AddOns\\GennUI\\media\\fonts\\GennUI.ttf",
                ["GroupOptionsExcludePA"] = false,
                ["SpecialWarningSound4"] = 552035,
                ["PrivateAurasPlayerXOffset"] = 1,
                ["SpecialWarningFlashDura5"] = 1,
                ["WarningDuration2"] = 1.5,
                ["AutologBosses"] = false,
                ["WarningPoint"] = "CENTER",
                ["DontShowTargetAnnouncements"] = true,
                ["HideBlizzardTimeline"] = true,
                ["ChosenVoicePack2"] = "VEM",
                ["DontShowTrashTimers"] = false,
                ["DontShowSpecialWarningFlash"] = false,
                ["InfoFrameFontSize"] = 11.26818084716797,
                ["WarningY"] = 260,
                ["DontSendBossGUIDs"] = false,
                ["EventMusicMythicFilter"] = false,
                ["BadTimerAlert"] = false,
                ["DebugSound"] = true,
                ["AutoAcceptFriendInvite"] = false,
                ["NPIconOffsetY"] = 20,
                ["SpecialWarningFlashCount1"] = 1,
                ["PullVoice"] = "Corsica",
                ["SpecialWarningSound5"] = 554236,
                ["DontSendYells"] = false,
                ["SpamSpecRoleinterrupt"] = false,
                ["SpecialWarningFlash2"] = true,
                ["NPIconTextFontStyle"] = "None",
                ["SpecialWarningFlash3"] = true,
                ["GUIHeight"] = 600,
                ["Enabled"] = true,
                ["FilterTrashWarnings2"] = true,
                ["AutoExpandSpellGroups2"] = true,
                ["SpecialWarningFlashAlph4"] = 0.4,
                ["PrivateAurasTextAnchorYOffset"] = -200,
                ["PrivateAurasCoTankXOffset"] = -136,
                ["PrivateAurasCoTankHeight"] = 50,
                ["PrivateAurasCoTankGrowDirection"] = "LEFT",
                ["StripServerName"] = true,
                ["NoCombatScanningFeatures"] = false,
                ["SpecialWarningFont"] = "Interface\\AddOns\\GennUI\\media\\fonts\\GennUI.ttf",
                ["PrivateAurasCoTankLimit"] = 5,
                ["DontShowPTNoID"] = false,
                ["InfoFrameLocked"] = false,
                ["EventSoundMusicCombined"] = false,
                ["ReplaceMyConfigOnOverride"] = false,
            },
        }
        DBM_MinimapIcon = {
            ["hide"] = true,
        }
        DBM_AnnoyingPopupDisables = nil
        DBM_ModsToLoadWithFullTestSupport = {
            ["addonsWithTests"] = {
            },
            ["bossModsWithTests"] = {
            },
        }
        DBM_Keystones = {
            ["keys"] = {
            },
            ["resetTime"] = 1768968000,
        }
        DBT_AllPersistentOptions = {
            ["Default"] = {
                ["DBM"] = {
                    ["StartColorPR"] = 1,
                    ["Scale"] = 0.9,
                    ["HugeBarsEnabled"] = true,
                    ["EndColorPB"] = 0.285,
                    ["EndColorPR"] = 0.5,
                    ["Sort"] = "Sort",
                    ["ExpandUpwardsLarge"] = false,
                    ["ExpandUpwards"] = false,
                    ["TimerPoint"] = "TOP",
                    ["EndColorDR"] = 1,
                    ["EndColorDG"] = 0,
                    ["Alpha"] = 0.8,
                    ["EndColorI2G"] = 0.5058823823928833,
                    ["HugeTimerPoint"] = "CENTER",
                    ["ClickThrough"] = false,
                    ["StartColorIR"] = 0.47,
                    ["DisableRightClick"] = false,
                    ["StartColorUIR"] = 1,
                    ["TextColorG"] = 1,
                    ["StartColorB"] = 0,
                    ["HugeScale"] = 1.03,
                    ["BarYOffset"] = 0,
                    ["HiddenBarTime"] = 60,
                    ["StartColorIG"] = 0.97,
                    ["HugeBarXOffset"] = 0,
                    ["StartColorI2G"] = 0.6745098233222961,
                    ["InlineIcons"] = true,
                    ["EndColorI2R"] = 1,
                    ["StartColorRR"] = 0.5,
                    ["StartColorUIG"] = 1,
                    ["FillUpLargeBars"] = true,
                    ["IconRight"] = false,
                    ["Skin"] = "",
                    ["StartColorDG"] = 0.3,
                    ["StartColorAR"] = 0.375,
                    ["VarColorG"] = 1,
                    ["StartColorPB"] = 0.42,
                    ["VarianceAlpha"] = 0.5,
                    ["StartColorAEG"] = 0.466,
                    ["TextColorR"] = 1,
                    ["EndColorAER"] = 1,
                    ["StartColorIB"] = 1,
                    ["StartColorR"] = 1,
                    ["HideLongBars"] = false,
                    ["DesaturateValue"] = 1,
                    ["FontSize"] = 10,
                    ["Font"] = "standardFont",
                    ["VarianceEnabled2"] = false,
                    ["EndColorAEB"] = 0.247,
                    ["Height"] = 20,
                    ["HugeSort"] = "Sort",
                    ["BarXOffset"] = 0,
                    ["EndColorB"] = 0,
                    ["EndColorAR"] = 0.15,
                    ["EndColorG"] = 0,
                    ["EndColorRB"] = 0.3,
                    ["HugeWidth"] = 200,
                    ["StartColorI2R"] = 1,
                    ["FadeBars"] = true,
                    ["TextColorB"] = 1,
                    ["EndColorIB"] = 1,
                    ["EndColorI2B"] = 0,
                    ["DynamicColor"] = true,
                    ["JournalIcons"] = 2,
                    ["TimerX"] = -395.260498046875,
                    ["EndColorIR"] = 0.047,
                    ["Bar7ForceLarge"] = true,
                    ["EndColorRR"] = 0.11,
                    ["Texture"] = "Interface\\AddOns\\DBM-StatusBarTimers\\textures\\default.blp",
                    ["BarStyle"] = "NoAnim",
                    ["EnlargeBarTime"] = 9.9,
                    ["Spark"] = true,
                    ["StartColorPG"] = 0.776,
                    ["HugeTimerX"] = 385.0941162109375,
                    ["FontFlag"] = "None",
                    ["EndColorAB"] = 1,
                    ["Width"] = 183,
                    ["EndColorPG"] = 0.41,
                    ["HugeAlpha"] = 1,
                    ["EndColorIG"] = 0.88,
                    ["EndColorAEG"] = 0.043,
                    ["HugeHeight"] = 20,
                    ["StartColorAEB"] = 0.459,
                    ["HugeBarYOffset"] = 0,
                    ["VarianceEnabled"] = true,
                    ["KeepBars"] = true,
                    ["TimerY"] = -49.94851684570313,
                    ["HugeTimerY"] = -290.6668395996094,
                    ["VarColorB"] = 1,
                    ["ColorByType"] = true,
                    ["IconLeft"] = true,
                    ["NoBarFade"] = false,
                    ["StartColorRB"] = 0.5,
                    ["FillUpBars"] = true,
                    ["StartColorAB"] = 1,
                    ["Bar7CustomInline"] = true,
                    ["EndColorDB"] = 1,
                    ["EndColorUIB"] = 0.0117647058823529,
                    ["IconLocked"] = true,
                    ["StartColorDR"] = 0.9,
                    ["FlashBar"] = false,
                    ["EndColorUIR"] = 1,
                    ["EndColorRG"] = 1,
                    ["StartColorUIB"] = 0.0627450980392157,
                    ["StartColorG"] = 0.7,
                    ["EndColorUIG"] = 0.92156862745098,
                    ["VarianceBehavior"] = "ZeroAtMinTimerAndNeg",
                    ["EndColorR"] = 1,
                    ["StartColorRG"] = 1,
                    ["VarColorR"] = 1,
                    ["StartColorAER"] = 1,
                    ["EndColorAG"] = 0.385,
                    ["TDecimal"] = 11,
                    ["StartColorDB"] = 1,
                    ["StartColorI2B"] = 0,
                    ["StartColorAG"] = 0.545,
                    ["VarianceTexture"] = "Interface\\AddOns\\DBM-StatusBarTimers\\textures\\default.blp",
                },
            },
            ["GennUI"] = {
                ["DBM"] = {
                    ["StartColorPR"] = 1,
                    ["Scale"] = 0.9,
                    ["HugeBarsEnabled"] = true,
                    ["EndColorPB"] = 0.285,
                    ["EndColorPR"] = 0.5,
                    ["Sort"] = "Sort",
                    ["ExpandUpwardsLarge"] = false,
                    ["ExpandUpwards"] = false,
                    ["TimerPoint"] = "TOP",
                    ["ClickThrough"] = true,
                    ["EndColorDG"] = 0,
                    ["Alpha"] = 0.8,
                    ["EndColorI2G"] = 0.5058823823928833,
                    ["HugeTimerPoint"] = "CENTER",
                    ["StartColorIG"] = 0.97,
                    ["EndColorUIG"] = 0.92156862745098,
                    ["VarianceBehavior"] = "ZeroAtMinTimerAndNeg",
                    ["StartColorUIR"] = 1,
                    ["TDecimal"] = 11,
                    ["StartColorDB"] = 1,
                    ["IconRight"] = true,
                    ["BarYOffset"] = 1,
                    ["HiddenBarTime"] = 60,
                    ["TextColorG"] = 1,
                    ["HugeBarXOffset"] = 0,
                    ["StartColorI2G"] = 0.6745098233222961,
                    ["InlineIcons"] = true,
                    ["EndColorI2R"] = 1,
                    ["StartColorRR"] = 0.5,
                    ["StartColorUIG"] = 1,
                    ["FillUpLargeBars"] = true,
                    ["HugeScale"] = 1,
                    ["Skin"] = "",
                    ["StartColorDG"] = 0.3,
                    ["StartColorAR"] = 0.375,
                    ["VarColorR"] = 1,
                    ["StartColorRG"] = 1,
                    ["VarianceAlpha"] = 0.5,
                    ["EndColorDR"] = 1,
                    ["TextColorR"] = 1,
                    ["EndColorAER"] = 1,
                    ["StartColorIB"] = 1,
                    ["DisableRightClick"] = false,
                    ["StartColorIR"] = 0.47,
                    ["DesaturateValue"] = 1,
                    ["EndColorG"] = 0,
                    ["Font"] = "Interface\\AddOns\\GennUI\\media\\fonts\\GennUI.ttf",
                    ["VarianceEnabled2"] = false,
                    ["EndColorAEB"] = 0.247,
                    ["Height"] = 16,
                    ["HugeSort"] = "Sort",
                    ["BarXOffset"] = 0,
                    ["EndColorB"] = 0,
                    ["EndColorAR"] = 0.15,
                    ["FontSize"] = 10,
                    ["EndColorRB"] = 0.3,
                    ["HugeWidth"] = 160,
                    ["StartColorI2R"] = 1,
                    ["FadeBars"] = true,
                    ["TextColorB"] = 1,
                    ["EndColorIB"] = 1,
                    ["EndColorI2B"] = 0,
                    ["Texture"] = "Interface\\AddOns\\GennUI\\media\\textures\\GennUI_B.tga",
                    ["JournalIcons"] = 2,
                    ["TimerX"] = -394.1664733886719,
                    ["EndColorIR"] = 0.047,
                    ["StartColorDR"] = 0.9,
                    ["EndColorRR"] = 0.11,
                    ["Bar7ForceLarge"] = true,
                    ["BarStyle"] = "NoAnim",
                    ["EnlargeBarTime"] = 9.9,
                    ["Spark"] = true,
                    ["StartColorPG"] = 0.776,
                    ["IconLocked"] = true,
                    ["FontFlag"] = "OUTLINE",
                    ["EndColorAB"] = 1,
                    ["Width"] = 160,
                    ["EndColorPG"] = 0.41,
                    ["EndColorUIB"] = 0.0117647058823529,
                    ["EndColorIG"] = 0.88,
                    ["EndColorAEG"] = 0.043,
                    ["EndColorDB"] = 1,
                    ["StartColorAEB"] = 0.459,
                    ["Bar7CustomInline"] = true,
                    ["VarianceEnabled"] = true,
                    ["KeepBars"] = true,
                    ["FillUpBars"] = true,
                    ["HugeTimerY"] = -276.444580078125,
                    ["StartColorRB"] = 0.5,
                    ["NoBarFade"] = false,
                    ["ColorByType"] = true,
                    ["IconLeft"] = false,
                    ["VarColorB"] = 1,
                    ["TimerY"] = -30.25620460510254,
                    ["StartColorAB"] = 1,
                    ["HugeBarYOffset"] = 1,
                    ["HugeHeight"] = 16,
                    ["HugeAlpha"] = 1,
                    ["HugeTimerX"] = 346.8033447265625,
                    ["DynamicColor"] = true,
                    ["FlashBar"] = false,
                    ["EndColorUIR"] = 1,
                    ["EndColorRG"] = 1,
                    ["StartColorUIB"] = 0.0627450980392157,
                    ["StartColorG"] = 0.7,
                    ["HideLongBars"] = false,
                    ["StartColorR"] = 1,
                    ["EndColorR"] = 1,
                    ["StartColorPB"] = 0.42,
                    ["VarColorG"] = 1,
                    ["StartColorAEG"] = 0.466,
                    ["EndColorAG"] = 0.385,
                    ["StartColorAER"] = 1,
                    ["StartColorB"] = 0,
                    ["StartColorI2B"] = 0,
                    ["StartColorAG"] = 0.545,
                    ["VarianceTexture"] = "Interface\\AddOns\\GennUI\\media\\textures\\GennUI_B.tga",
                },
            },
        }
        DBM:ApplyProfile('GennUI')
    end
end
