local GennUI = ...
local LS = LibStub("AceAddon-3.0")
GennUI = LS:GetAddon("GennUI", "AceConsole-3.0", "AceHook-3.0")

function GennUI:LoadTTTRProfile()
    TinyTooltipRemakeDB = {
        ["spell"] = {
            ["background"] = {
                0,
                0,
                0,
                0.8,
            },
            ["showIcon"] = true,
            ["borderColor"] = {
                0.6,
                0.6,
                0.6,
                0.8,
            },
        },
        ["general"] = {
            ["SavedVariablesPerCharacter"] = false,
            ["statusbarFontSize"] = 12,
            ["statusbarFont"] = "GennUI",
            ["mask"] = false,
            ["scale"] = 1,
            ["bgfile"] = "dark",
            ["headerFont"] = "GennUI",
            ["borderSize"] = 1,
            ["bodyFontFlag"] = "default",
            ["borderColor"] = {
                0.6,
                0.6,
                0.6,
                0.8,
            },
            ["anchor"] = {
                ["p"] = "BOTTOMRIGHT",
                ["hiddenInCombat"] = false,
                ["returnInCombat"] = false,
                ["returnOnUnitFrame"] = false,
                ["cy"] = 0,
                ["position"] = "cursor",
                ["cp"] = "BOTTOMRIGHT",
                ["cx"] = 0,
            },
            ["background"] = {
                0,
                0,
                0,
                0.7,
            },
            ["statusbarTexture"] = "GennUI B",
            ["statusbarPosition"] = "top",
            ["statusbarOffsetX"] = 0,
            ["bodyFont"] = "GennUI",
            ["bodyFontSize"] = "default",
            ["headerFontSize"] = "default",
            ["borderCorner"] = "default",
            ["statusbarOffsetY"] = 0,
            ["skinMoreFrames"] = false,
            ["statusbarPercent"] = false,
            ["alwaysShowIdInfo"] = false,
            ["statusbarHeight"] = 4,
            ["statusbarHide"] = false,
            ["headerFontFlag"] = "default",
            ["statusbarText"] = true,
            ["statusbarColor"] = "auto",
            ["statusbarFontFlag"] = "OUTLINE",
            ["hideUnitFrameHint"] = true,
        },
        ["version"] = 2.8,
        ["variables"] = {
        },
        ["item"] = {
            ["coloredItemBorder"] = true,
            ["showItemIcon"] = false,
        },
        ["quest"] = {
            ["coloredQuestBorder"] = true,
        },
        ["unit"] = {
            ["player"] = {
                ["elements"] = {
                    {
                        "friendIcon",
                        "raidIcon",
                        "roleIcon",
                        "pvpIcon",
                        "factionIcon",
                        "classIcon",
                        "title",
                        "name",
                        "realm",
                        "statusAFK",
                        "statusDND",
                        "statusDC",
                    },
                    {
                        "guildName",
                        "guildIndex",
                        "guildRank",
                        "guildRealm",
                    },
                    {
                        "levelValue",
                        "factionName",
                        "gender",
                        "raceName",
                        "className",
                        "isPlayer",
                        "role",
                        "moveSpeed",
                    },
                    {
                        "mount",
                    },
                    {
                        "mplusScore",
                    },
                    {
                        "zone",
                    },
                    ["guildRank"] = {
                        ["enable"] = true,
                        ["color"] = "cc88ff",
                        ["wildcard"] = "(%s)",
                        ["filter"] = "none",
                    },
                    ["statusAFK"] = {
                        ["enable"] = true,
                        ["color"] = "ffd200",
                        ["wildcard"] = "(%s)",
                        ["filter"] = "none",
                    },
                    ["guildIndex"] = {
                        ["enable"] = false,
                        ["color"] = "cc88ff",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["zone"] = {
                        ["enable"] = false,
                        ["color"] = "ffffff",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["mount"] = {
                        ["enable"] = true,
                        ["color"] = "ffffff",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["statusDC"] = {
                        ["enable"] = true,
                        ["color"] = "999999",
                        ["wildcard"] = "(%s)",
                        ["filter"] = "none",
                    },
                    ["raceName"] = {
                        ["enable"] = true,
                        ["color"] = "cccccc",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["role"] = {
                        ["enable"] = false,
                        ["color"] = "ffffff",
                        ["wildcard"] = "(%s)",
                        ["filter"] = "none",
                    },
                    ["factionName"] = {
                        ["enable"] = false,
                        ["color"] = "faction",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["raidIcon"] = {
                        ["enable"] = true,
                        ["filter"] = "none",
                    },
                    ["levelValue"] = {
                        ["enable"] = true,
                        ["color"] = "level",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["realm"] = {
                        ["enable"] = true,
                        ["color"] = "00eeee",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["roleIcon"] = {
                        ["enable"] = false,
                        ["filter"] = "none",
                    },
                    ["isPlayer"] = {
                        ["enable"] = false,
                        ["color"] = "ffffff",
                        ["wildcard"] = "(%s)",
                        ["filter"] = "none",
                    },
                    ["name"] = {
                        ["enable"] = true,
                        ["color"] = "class",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["pvpIcon"] = {
                        ["enable"] = false,
                        ["filter"] = "none",
                    },
                    ["moveSpeed"] = {
                        ["enable"] = false,
                        ["color"] = "e8e7a8",
                        ["wildcard"] = "%d%%",
                        ["filter"] = "none",
                    },
                    ["gender"] = {
                        ["enable"] = false,
                        ["color"] = "999999",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["guildRealm"] = {
                        ["enable"] = false,
                        ["color"] = "00cccc",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["statusDND"] = {
                        ["enable"] = true,
                        ["color"] = "ffd200",
                        ["wildcard"] = "(%s)",
                        ["filter"] = "none",
                    },
                    ["mplusScore"] = {
                        ["enable"] = true,
                        ["color"] = "mplus",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["className"] = {
                        ["enable"] = true,
                        ["color"] = "class",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["factionBig"] = {
                        ["enable"] = true,
                        ["filter"] = "none",
                    },
                    ["guildName"] = {
                        ["enable"] = true,
                        ["color"] = "ff00ff",
                        ["wildcard"] = "<%s>",
                        ["filter"] = "none",
                    },
                    ["title"] = {
                        ["enable"] = true,
                        ["color"] = "ccffff",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["friendIcon"] = {
                        ["enable"] = false,
                        ["filter"] = "none",
                    },
                    ["factionIcon"] = {
                        ["enable"] = false,
                        ["filter"] = "none",
                    },
                    ["classIcon"] = {
                        ["enable"] = false,
                        ["filter"] = "none",
                    },
                },
                ["showModel"] = false,
                ["showTargetBy"] = true,
                ["coloredBorder"] = "class",
                ["anchor"] = {
                    ["returnOnUnitFrame"] = false,
                    ["position"] = "inherit",
                    ["hiddenInCombat"] = false,
                    ["cp"] = "BOTTOM",
                    ["p"] = "BOTTOMRIGHT",
                    ["returnInCombat"] = false,
                },
                ["background"] = {
                    ["colorfunc"] = "default",
                    ["alpha"] = 0.9,
                },
                ["showTarget"] = true,
                ["grayForDead"] = false,
            },
            ["npc"] = {
                ["elements"] = {
                    {
                        "raidIcon",
                        "classIcon",
                        "questIcon",
                        "name",
                    },
                    {
                        "levelValue",
                        "classifBoss",
                        "classifElite",
                        "classifRare",
                        "creature",
                        "reactionName",
                        "moveSpeed",
                    },
                    ["creature"] = {
                        ["enable"] = true,
                        ["color"] = "selection",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["classifElite"] = {
                        ["enable"] = true,
                        ["color"] = "ffff33",
                        ["wildcard"] = "(%s)",
                        ["filter"] = "none",
                    },
                    ["npcTitle"] = {
                        ["enable"] = true,
                        ["color"] = "99e8e8",
                        ["wildcard"] = "<%s>",
                        ["filter"] = "none",
                    },
                    ["questIcon"] = {
                        ["enable"] = true,
                        ["filter"] = "none",
                    },
                    ["classifBoss"] = {
                        ["enable"] = true,
                        ["color"] = "ff0000",
                        ["wildcard"] = "(%s)",
                        ["filter"] = "none",
                    },
                    ["moveSpeed"] = {
                        ["enable"] = false,
                        ["color"] = "e8e7a8",
                        ["wildcard"] = "%d%%",
                        ["filter"] = "none",
                    },
                    ["reactionName"] = {
                        ["enable"] = true,
                        ["color"] = "33ffff",
                        ["wildcard"] = "<%s>",
                        ["filter"] = "reaction6",
                    },
                    ["factionBig"] = {
                        ["enable"] = false,
                        ["filter"] = "none",
                    },
                    ["name"] = {
                        ["enable"] = true,
                        ["color"] = "default",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["classifRare"] = {
                        ["enable"] = true,
                        ["color"] = "ffaaff",
                        ["wildcard"] = "(%s)",
                        ["filter"] = "none",
                    },
                    ["raidIcon"] = {
                        ["enable"] = true,
                        ["filter"] = "none",
                    },
                    ["levelValue"] = {
                        ["enable"] = true,
                        ["color"] = "level",
                        ["wildcard"] = "%s",
                        ["filter"] = "none",
                    },
                    ["classIcon"] = {
                        ["enable"] = false,
                        ["filter"] = "none",
                    },
                },
                ["showModel"] = false,
                ["showTargetBy"] = true,
                ["coloredBorder"] = "reaction",
                ["showTarget"] = true,
                ["background"] = {
                    ["colorfunc"] = "default",
                    ["alpha"] = 0.9,
                },
                ["anchor"] = {
                    ["returnOnUnitFrame"] = false,
                    ["position"] = "inherit",
                    ["hiddenInCombat"] = false,
                    ["cp"] = "BOTTOM",
                    ["p"] = "BOTTOMRIGHT",
                    ["returnInCombat"] = false,
                },
                ["grayForDead"] = false,
            },
        },
    }
end
