local GennUI = ...
local LS = LibStub("AceAddon-3.0")
GennUI = LS:GetAddon("GennUI", "AceConsole-3.0", "AceHook-3.0")

function GennUI:LoadTTRProfile()
    TipTac_Config = {
        ["profileKeys"] = {
        },
        ["profiles"] = {
            ["Default"] = {
                ["hideTipsDuringInstanceInCombatActionTips"] = true,
                ["if_showItemId"] = true,
                ["if_showIconId"] = true,
                ["if_showAchievementIdAndCategoryId"] = true,
                ["version_TipTac_Config"] = "26.02.12",
                ["modifyFonts"] = true,
                ["hideTipsDuringChallengeModeInCombatFrameUnits"] = true,
                ["showMountIcon"] = false,
                ["showGuildOfficerNote"] = false,
                ["fontFlags"] = "OUTLINE",
                ["showMountSpeed"] = false,
                ["if_showTransmogIllusionId"] = true,
                ["left"] = 1242.333374023438,
                ["t_talentFormat"] = 2,
                ["top"] = 109,
                ["hideTipsDuringInstanceInCombatUnitTips"] = true,
                ["optionsLeft"] = 228.6453094482422,
                ["hideTipsInCombatUnitTips"] = true,
                ["anchorFrameTipType"] = "mouse",
                ["hideTipsInCombatActionTips"] = true,
                ["if_showExpansionName"] = true,
                ["showHiddenModifierKey"] = "ctrl",
                ["if_showTransmogSetId"] = true,
                ["if_showKeystoneAffixInfo"] = false,
                ["if_showNpcId"] = true,
                ["if_showKeystoneRewardLevel"] = false,
                ["gradientTip"] = false,
                ["showGuildMemberNote"] = false,
                ["showCurrentUnitSpeed"] = false,
                ["hideTipsDuringChallengeModeInCombatUnitTips"] = true,
                ["t_showRoleIcon"] = false,
                ["if_showRuneforgePowerId"] = true,
                ["showMinimapIcon"] = false,
                ["colorNameByClass"] = true,
                ["if_showQuestId"] = true,
                ["optionsBottom"] = 699.3419189453125,
                ["anchorFrameUnitType"] = "mouse",
                ["fontFace"] = "Interface\\AddOns\\GennUI\\media\\fonts\\GennUI.ttf",
                ["showDebuffs"] = false,
                ["if_showCurrencyId"] = true,
                ["if_showKeystoneTimeLimit"] = false,
                ["hideTipsDuringInstanceInCombatFrameUnits"] = true,
                ["barFontFace"] = "Interface\\AddOns\\GennUI\\media\\fonts\\GennUI.ttf",
                ["t_showTalentIcon"] = false,
                ["if_showSpellIdAndRank"] = true,
                ["tipBackdropBG"] = "Interface\\Tooltips\\UI-Tooltip-Background",
                ["healthBarText"] = "value",
                ["if_modifyKeystoneTips"] = false,
                ["if_showAuraSpellIdAndRank"] = true,
                ["if_showIcon"] = false,
                ["showGuildRealm"] = "asterisk",
                ["anchorWorldTipType"] = "mouse",
                ["showBuffs"] = false,
                ["hideTipsDuringChallengeModeInCombatActionTips"] = true,
                ["anchorWorldUnitType"] = "mouse",
                ["hideTipsInCombatFrameUnits"] = true,
                ["if_showItemLevel"] = true,
                ["barTexture"] = "Interface\\AddOns\\GennUI\\media\\textures\\GennUI_B.tga",
                ["if_showTransmogAppearanceItemId"] = true,
                ["if_showFlyoutId"] = true,
                ["guildRankFormat"] = "title",
            },
        },
    }
end
