local E, L, V, P, G = unpack(ElvUI);
local GNUI = E:GetModule("GennUI");

function GNUI:LoadDiminishProfile()
DiminishDB = {
	["profileKeys"] = {
	},
	["profiles"] = {
		["Default"] = {
			["categoryTextures"] = {
			},
			["timerColors"] = false,
			["categoryTextMaxLines"] = 2,
			["trackNPCs"] = true,
			["unitFrames"] = {
				["nameplate"] = {
					["enabled"] = false,
					["iconPadding"] = 10,
					["watchFriendly"] = false,
					["disabledCategories"] = {
						["Taunts"] = true,
					},
					["timerTextSize"] = 12,
					["offsetX"] = -33,
					["growDirection"] = "RIGHT",
					["iconSize"] = 22,
					["offsetY"] = 71,
					["zones"] = {
						["party"] = false,
						["scenario"] = true,
						["pvp"] = true,
						["raid"] = false,
						["arena"] = true,
						["none"] = true,
					},
					["isEnabledForZone"] = false,
				},
				["player"] = {
					["enabled"] = false,
					["anchorUIParent"] = false,
					["zones"] = {
						["party"] = false,
						["scenario"] = true,
						["pvp"] = true,
						["raid"] = false,
						["arena"] = true,
						["none"] = true,
					},
					["iconPadding"] = 10,
					["watchFriendly"] = true,
					["disabledCategories"] = {
						["Taunts"] = true,
					},
					["growDirection"] = "RIGHT",
					["offsetX"] = 144,
					["timerTextSize"] = 12,
					["iconSize"] = 21,
					["offsetY"] = 0,
					["usePersonalNameplate"] = false,
					["isEnabledForZone"] = false,
				},
				["focus"] = {
					["enabled"] = false,
					["anchorUIParent"] = false,
					["iconPadding"] = 10,
					["watchFriendly"] = false,
					["disabledCategories"] = {
						["Taunts"] = true,
					},
					["zones"] = {
						["party"] = false,
						["scenario"] = true,
						["none"] = true,
						["raid"] = false,
						["arena"] = false,
						["pvp"] = true,
					},
					["offsetX"] = -75,
					["growDirection"] = "RIGHT",
					["iconSize"] = 22,
					["offsetY"] = 2,
					["timerTextSize"] = 12,
					["isEnabledForZone"] = false,
				},
				["target"] = {
					["enabled"] = false,
					["anchorUIParent"] = false,
					["iconPadding"] = 10,
					["watchFriendly"] = false,
					["disabledCategories"] = {
						["Taunts"] = true,
					},
					["zones"] = {
						["party"] = false,
						["scenario"] = true,
						["none"] = true,
						["raid"] = false,
						["arena"] = false,
						["pvp"] = true,
					},
					["offsetX"] = 104,
					["growDirection"] = "RIGHT",
					["iconSize"] = 22,
					["offsetY"] = 23,
					["timerTextSize"] = 12,
					["isEnabledForZone"] = false,
				},
				["arena"] = {
					["enabled"] = true,
					["anchorUIParent"] = false,
					["iconPadding"] = 6,
					["disabledCategories"] = {
						["Taunts"] = true,
					},
					["timerTextSize"] = 12,
					["offsetX"] = 110,
					["growDirection"] = "RIGHT",
					["iconSize"] = 28,
					["offsetY"] = 0,
					["zones"] = {
						["party"] = false,
						["scenario"] = false,
						["pvp"] = false,
						["raid"] = false,
						["arena"] = true,
						["none"] = false,
					},
					["isEnabledForZone"] = false,
				},
				["party"] = {
					["enabled"] = false,
					["anchorUIParent"] = false,
					["iconPadding"] = 10,
					["watchFriendly"] = true,
					["disabledCategories"] = {
						["Taunts"] = true,
					},
					["timerTextSize"] = 12,
					["offsetX"] = 76,
					["growDirection"] = "RIGHT",
					["iconSize"] = 24,
					["offsetY"] = 7,
					["zones"] = {
						["party"] = false,
						["scenario"] = false,
						["pvp"] = false,
						["raid"] = false,
						["arena"] = true,
						["none"] = true,
					},
					["isEnabledForZone"] = false,
				},
			},
			["timerEdge"] = true,
			["border"] = {
				["edgeSize"] = 2.5,
				["layer"] = "BORDER",
				["name"] = "Default",
				["edgeFile"] = "Interface\\BUTTONS\\UI-Quickslot-Depress",
			},
			["announceDRs"] = false,
			["version"] = "1.11",
			["timerStartAuraEnd"] = false,
			["showCategoryText"] = true,
			["timerTextOutline"] = "NONE",
			["colorBlind"] = false,
			["timerText"] = true,
			["timerSwipe"] = true,
			["categoryFont"] = {
				["size"] = 9,
				["x"] = 0,
			},
		},
	},
}
end