local E, L, V, P, G = unpack(ElvUI);
local GNUI = E:GetModule("GennUI");

function GNUI:LoadOmniBarProfile()
OmniBarDB = {
        ["namespaces"] = {
        },
        ["global"] = {
            ["cooldowns"] = {
                [357170] = {
                    ["custom"] = true,
                    ["class"] = "EVOKER",
                    ["duration"] = {
                        ["default"] = 60,
                    },
                    ["icon"] = 4622478,
                    ["name"] = "Time Dilation",
                },
                [61336] = {
                    ["name"] = "Survival Instincts",
                    ["specID"] = {
                        103,
                        104,
                    },
                    ["duration"] = {
                        ["default"] = 180,
                        [104] = 120,
                    },
                    ["icon"] = 236169,
                    ["class"] = "DRUID",
                },
                [31661] = {
                    ["name"] = "Dragon's Breath",
                    ["duration"] = {
                        ["default"] = 32,
                    },
                    ["icon"] = 134153,
                    ["class"] = "MAGE",
                },
                [258860] = {
                    ["custom"] = true,
                    ["class"] = "DEMONHUNTER",
                    ["duration"] = {
                        ["default"] = 40,
                    },
                    ["specID"] = {
                        577,
                    },
                    ["icon"] = 136189,
                    ["name"] = "Essence Break",
                },
                [452930] = {
                    ["custom"] = true,
                    ["name"] = "Demonic Healthstone",
                    ["class"] = "WARLOCK",
                    ["icon"] = 538744,
                    ["duration"] = {
                        ["default"] = 60,
                    },
                },
                [267217] = {
                    ["custom"] = true,
                    ["class"] = "WARLOCK",
                    ["duration"] = {
                        ["default"] = 180,
                    },
                    ["specID"] = {
                        266,
                    },
                    ["icon"] = 2065615,
                    ["name"] = "Nether Portal",
                },
                [342245] = {
                    ["custom"] = true,
                    ["class"] = "MAGE",
                    ["duration"] = {
                        ["default"] = 60,
                    },
                    ["icon"] = 609811,
                    ["name"] = "Alter Time",
                },
                [391109] = {
                    ["custom"] = true,
                    ["name"] = "Dark Ascension",
                    ["specID"] = {
                        258,
                    },
                    ["duration"] = {
                        ["default"] = 60,
                    },
                    ["icon"] = 1445237,
                    ["class"] = "PRIEST",
                },
                [853] = {
                    ["duration"] = {
                        ["default"] = 60,
                        [70] = 30,
                    },
                    ["class"] = "PALADIN",
                    ["icon"] = 135963,
                    ["name"] = "Hammer of Justice",
                },
                [370960] = {
                    ["custom"] = true,
                    ["name"] = "Emerald Communion",
                    ["class"] = "EVOKER",
                    ["icon"] = 4630447,
                    ["duration"] = {
                        ["default"] = 180,
                    },
                },
                [365350] = {
                    ["custom"] = true,
                    ["class"] = "MAGE",
                    ["duration"] = {
                        ["default"] = 30,
                        [62] = 90,
                    },
                    ["specID"] = {
                        62,
                    },
                    ["icon"] = 4667417,
                    ["name"] = "Arcane Surge",
                },
                [409293] = {
                    ["duration"] = {
                        ["default"] = 120,
                    },
                    ["class"] = "SHAMAN",
                    ["icon"] = 136025,
                    ["name"] = "Burrow",
                },
                [378464] = {
                    ["custom"] = true,
                    ["class"] = "EVOKER",
                    ["duration"] = {
                        ["default"] = 90,
                    },
                    ["icon"] = 135752,
                    ["name"] = "Nullifying Shroud",
                },
                [473909] = {
                    ["custom"] = true,
                    ["name"] = "Ancient of Lore",
                    ["specID"] = {
                        105,
                    },
                    ["class"] = "DRUID",
                    ["icon"] = 874857,
                    ["duration"] = {
                        ["default"] = 90,
                    },
                },
                [47788] = {
                    ["name"] = "Guardian Spirit",
                    ["class"] = "PRIEST",
                    ["duration"] = {
                        ["default"] = 60,
                    },
                    ["icon"] = 237542,
                    ["specID"] = {
                        257,
                    },
                },
                [132158] = {
                    ["custom"] = true,
                    ["class"] = "DRUID",
                    ["duration"] = {
                        ["default"] = 60,
                    },
                    ["specID"] = {
                        105,
                    },
                    ["icon"] = 136076,
                    ["name"] = "Nature's Swiftness",
                },
                [360194] = {
                    ["custom"] = true,
                    ["class"] = "ROGUE",
                    ["duration"] = {
                        ["default"] = 120,
                    },
                    ["specID"] = {
                        259,
                    },
                    ["icon"] = 4667421,
                    ["name"] = "Deathmark",
                },
                [235219] = {
                    ["custom"] = true,
                    ["name"] = "Cold Snap",
                    ["specID"] = {
                        64,
                    },
                    ["class"] = "MAGE",
                    ["icon"] = 135865,
                    ["duration"] = {
                        ["default"] = 300,
                    },
                },
                [378081] = {
                    ["custom"] = true,
                    ["name"] = "Nature's Swiftness",
                    ["class"] = "SHAMAN",
                    ["icon"] = 136076,
                    ["duration"] = {
                        ["default"] = 60,
                    },
                },
                [288613] = {
                    ["custom"] = true,
                    ["class"] = "HUNTER",
                    ["duration"] = {
                        ["default"] = 120,
                    },
                    ["icon"] = 132329,
                    ["name"] = "Trueshot",
                },
                [351338] = {
                    ["custom"] = true,
                    ["class"] = "EVOKER",
                    ["duration"] = {
                        ["default"] = 40,
                        [1467] = 20,
                    },
                    ["icon"] = 4622469,
                    ["name"] = "Quell",
                },
                [357210] = {
                    ["duration"] = {
                        ["default"] = 60,
                        [1468] = 120,
                    },
                    ["class"] = "EVOKER",
                    ["icon"] = 4622450,
                    ["name"] = "Deep Breath",
                },
            },
        },
        ["profileKeys"] = {
        },
        ["profiles"] = {
            ["Default"] = {
                ["bars"] = {
                    ["OmniBar4"] = {
                        ["glow"] = true,
                        ["scenario"] = false,
                        ["border"] = true,
                        ["tooltips"] = false,
                        ["names"] = false,
                        ["multiple"] = true,
                        ["growUpward"] = true,
                        ["highlightFocus"] = false,
                        ["arena"] = true,
                        ["locked"] = true,
                        ["center"] = true,
                        ["ratedBattleground"] = true,
                        ["size"] = 40,
                        ["cooldownCount"] = true,
                        ["highlightTarget"] = true,
                        ["columns"] = 11,
                        ["unusedAlpha"] = 0.45,
                        ["align"] = "CENTER",
                        ["spells"] = {
                            [31661] = true,
                            [2094] = true,
                            [5211] = true,
                            [357210] = false,
                            [217832] = true,
                            [99] = true,
                            [853] = true,
                            [89766] = false,
                            [8122] = true,
                            [64044] = true,
                            [115750] = false,
                            [19577] = true,
                            [119381] = true,
                            [46968] = false,
                            [5484] = true,
                            [73325] = false,
                            [80240] = false,
                            [15487] = true,
                            [5246] = true,
                            [179057] = true,
                            [221562] = false,
                            [305483] = true,
                            [408] = true,
                            [6789] = true,
                            [187650] = true,
                            [207167] = true,
                            [107570] = true,
                        },
                        ["swipeAlpha"] = 0,
                        ["adaptive"] = false,
                        ["maxIcons"] = 11,
                        ["world"] = true,
                        ["name"] = "Crowd Control",
                        ["position"] = {
                            ["relativeTo"] = "UIParent",
                            ["point"] = "BOTTOM",
                            ["relativePoint"] = "BOTTOM",
                            ["yOfs"] = 166.4249420166016,
                            ["xOfs"] = -7.182414265116677e-05,
                            ["frameStrata"] = "MEDIUM",
                        },
                        ["trackUnit"] = "ENEMY",
                        ["padding"] = 2,
                        ["showUnused"] = false,
                        ["battleground"] = true,
                    },
                    ["OmniBar5"] = {
                        ["glow"] = true,
                        ["scenario"] = false,
                        ["border"] = true,
                        ["tooltips"] = true,
                        ["names"] = false,
                        ["multiple"] = true,
                        ["growUpward"] = true,
                        ["center"] = false,
                        ["arena"] = true,
                        ["locked"] = true,
                        ["highlightFocus"] = false,
                        ["highlightTarget"] = true,
                        ["world"] = false,
                        ["cooldownCount"] = true,
                        ["ratedBattleground"] = false,
                        ["columns"] = 8,
                        ["unusedAlpha"] = 0.45,
                        ["align"] = "LEFT",
                        ["spells"] = {
                            [383013] = false,
                            [212623] = true,
                            [212295] = true,
                            [586] = true,
                            [32375] = true,
                            [204336] = true,
                            [6940] = true,
                            [213610] = true,
                            [210256] = true,
                            [205604] = true,
                            [8143] = true,
                            [23920] = true,
                            [378081] = false,
                            [32379] = true,
                        },
                        ["trackUnit"] = "ENEMY",
                        ["adaptive"] = false,
                        ["maxIcons"] = 8,
                        ["size"] = 40,
                        ["name"] = "Misc",
                        ["position"] = {
                            ["relativeTo"] = "UIParent",
                            ["point"] = "CENTER",
                            ["relativePoint"] = "CENTER",
                            ["yOfs"] = 204.059814453125,
                            ["xOfs"] = 387.2821655273438,
                            ["frameStrata"] = "MEDIUM",
                        },
                        ["swipeAlpha"] = 0,
                        ["showUnused"] = false,
                        ["padding"] = 2,
                        ["battleground"] = false,
                    },
                    ["OmniBar1"] = {
                        ["glow"] = true,
                        ["scenario"] = false,
                        ["tooltips"] = true,
                        ["border"] = true,
                        ["names"] = false,
                        ["multiple"] = true,
                        ["highlightFocus"] = false,
                        ["center"] = true,
                        ["arena"] = true,
                        ["swipeAlpha"] = 0.65,
                        ["growUpward"] = true,
                        ["highlightTarget"] = true,
                        ["world"] = false,
                        ["cooldownCount"] = true,
                        ["ratedBattleground"] = false,
                        ["columns"] = 8,
                        ["unusedAlpha"] = 0.45,
                        ["align"] = "CENTER",
                        ["spells"] = {
                            [187707] = true,
                            [586] = false,
                            [96231] = true,
                            [106839] = true,
                            [57994] = true,
                            [1766] = true,
                            [116705] = true,
                            [183752] = true,
                            [147362] = true,
                            [351338] = true,
                            [119910] = true,
                            [47528] = true,
                            [23920] = false,
                            [31935] = true,
                            [32379] = false,
                            [212295] = false,
                            [2139] = true,
                            [61336] = false,
                            [78675] = true,
                            [204336] = false,
                            [6552] = true,
                        },
                        ["locked"] = true,
                        ["adaptive"] = false,
                        ["maxIcons"] = 8,
                        ["size"] = 45,
                        ["name"] = "Interrupts",
                        ["position"] = {
                            ["relativeTo"] = "UIParent",
                            ["point"] = "BOTTOM",
                            ["relativePoint"] = "BOTTOM",
                            ["yOfs"] = 213.7418975830078,
                            ["xOfs"] = -7.182414265116677e-05,
                            ["frameStrata"] = "MEDIUM",
                        },
                        ["trackUnit"] = "ENEMY",
                        ["showUnused"] = false,
                        ["padding"] = 2,
                        ["battleground"] = false,
                    },
                    ["OmniBar2"] = {
                        ["glow"] = true,
                        ["scenario"] = false,
                        ["border"] = true,
                        ["tooltips"] = true,
                        ["names"] = false,
                        ["multiple"] = true,
                        ["highlightFocus"] = false,
                        ["growUpward"] = true,
                        ["arena"] = true,
                        ["swipeAlpha"] = 0,
                        ["center"] = false,
                        ["ratedBattleground"] = false,
                        ["size"] = 40,
                        ["cooldownCount"] = true,
                        ["highlightTarget"] = true,
                        ["columns"] = 8,
                        ["unusedAlpha"] = 0.45,
                        ["align"] = "LEFT",
                        ["spells"] = {
                            [3411] = true,
                            [31224] = true,
                            [118038] = true,
                            [205604] = false,
                            [32375] = false,
                            [33891] = false,
                            [32379] = false,
                            [210256] = false,
                            [184364] = true,
                            [51052] = false,
                            [187698] = false,
                            [48020] = true,
                            [204018] = true,
                            [204336] = false,
                            [212623] = false,
                            [5277] = true,
                            [122278] = false,
                            [48707] = true,
                            [116849] = true,
                            [23920] = false,
                            [196718] = false,
                            [871] = false,
                            [633] = false,
                            [1022] = true,
                            [61336] = true,
                            [115310] = true,
                            [108968] = true,
                            [62618] = false,
                            [6940] = true,
                            [122470] = true,
                            [586] = false,
                            [642] = true,
                            [33206] = true,
                            [342245] = false,
                            [378441] = false,
                            [132158] = true,
                            [2983] = false,
                            [108271] = true,
                            [498] = false,
                            [357170] = false,
                            [98008] = true,
                            [102342] = true,
                            [116844] = false,
                            [452930] = true,
                            [48792] = true,
                            [47788] = true,
                            [109304] = true,
                            [119996] = false,
                            [473909] = true,
                            [215769] = true,
                            [115750] = false,
                            [363534] = true,
                            [213871] = false,
                            [11426] = false,
                            [108416] = true,
                            [45438] = true,
                            [122783] = true,
                            [186265] = true,
                            [212295] = false,
                            [104773] = true,
                            [184662] = false,
                            [36554] = false,
                            [53480] = false,
                            [235219] = false,
                            [370960] = true,
                            [363916] = false,
                            [22812] = true,
                            [198838] = false,
                            [212800] = true,
                            [47585] = true,
                            [197268] = false,
                            [97462] = true,
                            [2139] = false,
                            [5384] = false,
                            [196555] = true,
                            [213610] = false,
                            [414660] = false,
                            [1856] = true,
                            [198793] = false,
                            [409293] = true,
                            [8143] = false,
                        },
                        ["trackUnit"] = "ENEMY",
                        ["adaptive"] = false,
                        ["maxIcons"] = 16,
                        ["world"] = false,
                        ["name"] = "Defensives",
                        ["position"] = {
                            ["relativeTo"] = "UIParent",
                            ["point"] = "RIGHT",
                            ["relativePoint"] = "RIGHT",
                            ["yOfs"] = -202.4236755371094,
                            ["xOfs"] = -480.8676452636719,
                            ["frameStrata"] = "MEDIUM",
                        },
                        ["locked"] = true,
                        ["padding"] = 2,
                        ["showUnused"] = false,
                        ["battleground"] = false,
                    },
                },
            },
        },
    }
end