local E, L, V, P, G = unpack(ElvUI);
local GNUI = E:GetModule("GennUI");

function GNUI:LoadOmniCDProfile()

OmniCDDB = {
        ["profileKeys"] = {
        },
        ["namespaces"] = {
        },
        ["cooldowns"] = {
            [31661] = {
                ["type"] = "aoeCC",
                ["buff"] = 31661,
                ["class"] = "MAGE",
                ["name"] = "Dragon's Breath",
                ["charges"] = {
                    ["default"] = 1,
                },
                ["spec"] = {
                    31661,
                },
                ["duration"] = {
                    ["default"] = 32,
                },
                ["icon"] = 134153,
                ["spellID"] = 31661,
            },
            [1219201] = {
                ["type"] = "counterCC",
                ["buff"] = 1219209,
                ["class"] = "WARRIOR",
                ["spec"] = {
                    1219201,
                },
                ["name"] = "Berserker Roar",
                ["custom"] = true,
                ["duration"] = {
                    ["default"] = 60,
                },
                ["charges"] = {
                    ["default"] = 1,
                },
                ["icon"] = 136009,
                ["spellID"] = 1219201,
            },
            [633] = {
                ["type"] = "externalDefensive",
                ["buff"] = 633,
                ["class"] = "PALADIN",
                ["name"] = "Lay on Hands",
                ["charges"] = {
                    ["default"] = 1,
                },
                ["spec"] = {
                    633,
                },
                ["duration"] = {
                    ["default"] = 600,
                },
                ["icon"] = 135928,
                ["spellID"] = 633,
            },
            [473909] = {
                ["type"] = "immunity",
                ["buff"] = 473909,
                ["class"] = "DRUID",
                ["spec"] = {
                    473909,
                },
                ["name"] = "Ancient of Lore",
                ["custom"] = true,
                ["charges"] = {
                    ["default"] = 1,
                },
                ["duration"] = {
                    ["default"] = 90,
                },
                ["icon"] = 874857,
                ["spellID"] = 473909,
            },
            [370665] = {
                ["type"] = "externalDefensive",
                ["buff"] = 370665,
                ["class"] = "EVOKER",
                ["name"] = "Rescue",
                ["charges"] = {
                    ["default"] = 1,
                },
                ["spec"] = {
                    370665,
                },
                ["duration"] = {
                    ["default"] = 60,
                },
                ["icon"] = 4622460,
                ["spellID"] = 370665,
            },
            [452930] = {
                ["type"] = "heal",
                ["buff"] = 452930,
                ["class"] = "WARLOCK",
                ["name"] = "Demonic Healthstone",
                ["charges"] = {
                    ["default"] = 1,
                },
                ["spec"] = {
                    386689,
                },
                ["duration"] = {
                    ["default"] = 60,
                },
                ["icon"] = 538744,
                ["spellID"] = 452930,
            },
            [360823] = {
                ["type"] = "dispel",
                ["buff"] = 360823,
                ["duration"] = {
                    ["default"] = 8,
                },
                ["spec"] = {
                    1468,
                },
                ["custom"] = true,
                ["name"] = "Naturalize",
                ["charges"] = {
                    ["default"] = 1,
                },
                ["class"] = "EVOKER",
                ["icon"] = 4630445,
                ["spellID"] = 360823,
            },
            [374251] = {
                ["type"] = "externalDefensive",
                ["buff"] = 374251,
                ["class"] = "EVOKER",
                ["name"] = "Cauterizing Flame",
                ["charges"] = {
                    ["default"] = 1,
                },
                ["spec"] = {
                    374251,
                },
                ["duration"] = {
                    ["default"] = 60,
                },
                ["icon"] = 4630446,
                ["spellID"] = 374251,
            },
        },
        ["version"] = 4,
        ["profiles"] = {
            ["Default"] = {
                ["Party"] = {
                    ["party"] = {
                        ["extraBars"] = {
                            ["raidBar2"] = {
                                ["truncateIconName"] = 0,
                                ["progressBar"] = false,
                                ["statusBarWidth"] = 173,
                                ["anchor"] = "BOTTOMLEFT",
                                ["enabled"] = true,
                                ["paddingX"] = 0,
                                ["layout"] = "horizontal",
                                ["name"] = "CC",
                                ["growLeft"] = true,
                                ["growUpward"] = true,
                                ["locked"] = true,
                                ["columns"] = 4,
                                ["attach"] = "TOPRIGHT",
                                ["showName"] = false,
                                ["nameOfsY"] = -9,
                                ["scale"] = 1,
                                ["manualPos"] = {
                                    ["raidBar2"] = {
                                        ["y"] = 532.9780810364173,
                                        ["x"] = 313.955681538373,
                                    },
                                },
                            },
                            ["raidBar3"] = {
                                ["locked"] = true,
                                ["layout"] = "horizontal",
                                ["name"] = "Externals",
                                ["anchor"] = "TOPLEFT",
                                ["manualPos"] = {
                                    ["raidBar3"] = {
                                        ["y"] = 304.7113503490964,
                                        ["x"] = 344.8903982070679,
                                    },
                                },
                                ["attach"] = "BOTTOMLEFT",
                                ["scale"] = 0.8700000000000001,
                                ["columns"] = 4,
                            },
                            ["raidBar1"] = {
                                ["statusBarWidth"] = 173,
                                ["showRaidTargetMark"] = true,
                                ["growUpward"] = true,
                                ["scale"] = 0.6000000000000001,
                                ["locked"] = true,
                                ["manualPos"] = {
                                    ["raidBar1"] = {
                                        ["y"] = 524.4445699968855,
                                        ["x"] = 349.1555169782077,
                                    },
                                },
                            },
                        },
                        ["spells"] = {
                            ["633"] = true,
                            ["47481"] = true,
                            ["357210"] = true,
                            ["12975"] = true,
                            ["2094"] = true,
                            ["406732"] = true,
                            ["197721"] = true,
                            ["370960"] = true,
                            ["108416"] = true,
                            ["19577"] = true,
                            ["368412"] = false,
                            ["265221"] = true,
                            ["102793"] = true,
                            ["88625"] = true,
                            ["6262"] = true,
                            ["336126"] = true,
                            ["371032"] = false,
                            ["221562"] = true,
                            ["403876"] = true,
                            ["414664"] = true,
                            ["115078"] = true,
                            ["370665"] = true,
                            ["217832"] = true,
                            ["396286"] = false,
                            ["55233"] = true,
                            ["336135"] = true,
                            ["22570"] = true,
                            ["20594"] = true,
                            ["421453"] = true,
                            ["108281"] = true,
                            ["5211"] = true,
                            ["20549"] = true,
                            ["498"] = true,
                            ["1776"] = true,
                            ["204406"] = true,
                            ["49039"] = true,
                            ["51533"] = false,
                            ["324312"] = true,
                            ["385627"] = false,
                            ["327574"] = true,
                            ["389539"] = true,
                            ["443124"] = true,
                            ["200183"] = true,
                            ["1856"] = true,
                            ["198144"] = false,
                            ["408"] = true,
                            ["20066"] = true,
                            ["228920"] = true,
                            ["211881"] = true,
                            ["113724"] = true,
                            ["455395"] = true,
                            ["385059"] = true,
                            ["213691"] = true,
                            ["207399"] = true,
                            ["32375"] = true,
                            ["108238"] = true,
                            ["55342"] = true,
                            ["64044"] = true,
                            ["49206"] = true,
                            ["452930"] = true,
                            ["392966"] = true,
                            ["19574"] = true,
                            ["198103"] = true,
                            ["374251"] = true,
                            ["47476"] = true,
                            ["853"] = true,
                            ["48743"] = true,
                            ["6789"] = true,
                            ["109304"] = true,
                            ["305483"] = true,
                            ["360806"] = true,
                            ["264735"] = true,
                            ["227847"] = true,
                            ["383762"] = true,
                            ["236776"] = true,
                            ["374348"] = true,
                            ["184662"] = true,
                            ["198898"] = true,
                            ["109248"] = true,
                            ["200851"] = true,
                            ["108199"] = true,
                            ["275699"] = false,
                            ["200652"] = true,
                            ["107570"] = true,
                            ["108270"] = true,
                            ["322507"] = true,
                            ["384631"] = false,
                            ["192249"] = true,
                            ["29166"] = true,
                            ["110959"] = true,
                            ["343721"] = false,
                            ["31850"] = true,
                            ["19236"] = true,
                        },
                        ["icons"] = {
                            ["scale"] = 0.75,
                            ["swipeAlpha"] = 0,
                        },
                        ["general"] = {
                            ["showPlayer"] = true,
                            ["showRange"] = true,
                        },
                        ["position"] = {
                            ["offsetX"] = 1,
                            ["anchor"] = "TOPRIGHT",
                            ["paddingY"] = 1,
                            ["paddingX"] = 1,
                            ["attach"] = "TOPLEFT",
                            ["maxNumIcons"] = 12,
                            ["preset"] = "TOPLEFT",
                        },
                        ["frame"] = {
                            ["disarm"] = 2,
                            ["cc"] = 2,
                            ["externalDefensive"] = 0,
                            ["raidDefensive"] = 0,
                        },
                        ["priority"] = {
                            ["taunt"] = 2,
                            ["freedom"] = 10,
                            ["racial"] = 17,
                            ["disarm"] = 4,
                            ["aoeCC"] = 5,
                            ["pvptrinket"] = 18,
                            ["dispel"] = 16,
                            ["cc"] = 3,
                            ["counterCC"] = 16,
                            ["externalDefensive"] = 11,
                            ["immunity"] = 14,
                            ["essence"] = 15,
                            ["interrupt"] = 1,
                            ["trinket"] = 15,
                            ["defensive"] = 13,
                            ["heal"] = 12,
                            ["covenant"] = 14,
                            ["consumable"] = 15,
                            ["movement"] = 8,
                            ["raidMovement"] = 9,
                            ["offensive"] = 1,
                            ["raidDefensive"] = 11,
                            ["tankDefensive"] = 13,
                            ["other"] = 6,
                        },
                    },
                    ["arena"] = {
                        ["extraBars"] = {
                            ["raidBar2"] = {
                                ["truncateIconName"] = 0,
                                ["progressBar"] = false,
                                ["statusBarWidth"] = 173,
                                ["locked"] = true,
                                ["enabled"] = true,
                                ["paddingX"] = 0,
                                ["layout"] = "horizontal",
                                ["name"] = "CC",
                                ["growLeft"] = true,
                                ["growUpward"] = true,
                                ["manualPos"] = {
                                    ["raidBar2"] = {
                                        ["y"] = 532.9780810364173,
                                        ["x"] = 313.955681538373,
                                    },
                                },
                                ["anchor"] = "BOTTOMLEFT",
                                ["scale"] = 1,
                                ["columns"] = 4,
                                ["nameOfsY"] = -9,
                                ["attach"] = "TOPRIGHT",
                                ["showName"] = false,
                            },
                            ["raidBar3"] = {
                                ["anchor"] = "TOPLEFT",
                                ["layout"] = "horizontal",
                                ["name"] = "Externals",
                                ["columns"] = 4,
                                ["scale"] = 0.8700000000000001,
                                ["manualPos"] = {
                                    ["raidBar3"] = {
                                        ["y"] = 304.7113503490964,
                                        ["x"] = 344.8903982070679,
                                    },
                                },
                                ["attach"] = "BOTTOMLEFT",
                                ["locked"] = true,
                            },
                            ["raidBar1"] = {
                                ["statusBarWidth"] = 173,
                                ["showRaidTargetMark"] = true,
                                ["enabled"] = true,
                                ["growUpward"] = true,
                                ["manualPos"] = {
                                    ["raidBar1"] = {
                                        ["y"] = 524.4445699968855,
                                        ["x"] = 349.1555169782077,
                                    },
                                },
                                ["locked"] = true,
                                ["scale"] = 0.6000000000000001,
                            },
                        },
                        ["spells"] = {
                            ["327574"] = true,
                            ["47481"] = true,
                            ["357210"] = true,
                            ["8143"] = false,
                            ["384100"] = false,
                            ["12975"] = true,
                            ["406732"] = true,
                            ["197721"] = true,
                            ["202138"] = true,
                            ["187827"] = true,
                            ["368970"] = true,
                            ["370388"] = false,
                            ["48020"] = false,
                            ["386071"] = true,
                            ["59752"] = false,
                            ["7744"] = false,
                            ["414664"] = true,
                            ["55233"] = true,
                            ["209258"] = true,
                            ["*"] = false,
                            ["20594"] = true,
                            ["378279"] = true,
                            ["108281"] = true,
                            ["198067"] = true,
                            ["1776"] = true,
                            ["53480"] = false,
                            ["204406"] = true,
                            ["462031"] = true,
                            ["23920"] = true,
                            ["200183"] = true,
                            ["204336"] = false,
                            ["377509"] = false,
                            ["193876"] = false,
                            ["455395"] = true,
                            ["123904"] = true,
                            ["1044"] = false,
                            ["198838"] = false,
                            ["262161"] = true,
                            ["414660"] = true,
                            ["452930"] = true,
                            ["392966"] = true,
                            ["192058"] = true,
                            ["50334"] = true,
                            ["48743"] = true,
                            ["386394"] = true,
                            ["64843"] = true,
                            ["360806"] = true,
                            ["49028"] = true,
                            ["116844"] = true,
                            ["374227"] = true,
                            ["31661"] = true,
                            ["114018"] = true,
                            ["51490"] = true,
                            ["212182"] = false,
                            ["383121"] = true,
                            ["200851"] = true,
                            ["108199"] = true,
                            ["368412"] = false,
                            ["108270"] = true,
                            ["265221"] = true,
                            ["102793"] = true,
                            ["322507"] = true,
                            ["157980"] = true,
                            ["167105"] = true,
                            ["6262"] = true,
                            ["200733"] = true,
                            ["119996"] = false,
                            ["179057"] = true,
                            ["20549"] = true,
                            ["271466"] = true,
                            ["391124"] = false,
                            ["386997"] = true,
                            ["324312"] = true,
                            ["102558"] = true,
                            ["389539"] = true,
                            ["443124"] = true,
                            ["116841"] = false,
                            ["378779"] = true,
                            ["152279"] = true,
                            ["31935"] = true,
                            ["20066"] = true,
                            ["228920"] = true,
                            ["187650"] = false,
                            ["132469"] = true,
                            ["199448"] = false,
                            ["210256"] = false,
                            ["449700"] = true,
                            ["109248"] = true,
                            ["385059"] = true,
                            ["213691"] = true,
                            ["408234"] = false,
                            ["207399"] = true,
                            ["73325"] = false,
                            ["186387"] = true,
                            ["205604"] = false,
                            ["409293"] = false,
                            ["202137"] = true,
                            ["55342"] = true,
                            ["215982"] = false,
                            ["31850"] = true,
                            ["19236"] = true,
                            ["408"] = true,
                            ["86659"] = true,
                            ["157981"] = true,
                            ["30283"] = true,
                            ["119381"] = true,
                            ["19574"] = true,
                            ["198103"] = true,
                            ["197268"] = false,
                            ["46968"] = true,
                            ["204021"] = true,
                            ["357214"] = true,
                            ["192249"] = true,
                            ["22570"] = true,
                            ["42650"] = true,
                            ["99"] = true,
                            ["29166"] = true,
                            ["378441"] = false,
                            ["871"] = true,
                            ["114556"] = true,
                            ["200652"] = true,
                            ["421453"] = true,
                            ["227847"] = true,
                            ["383762"] = true,
                            ["49039"] = true,
                            ["58875"] = false,
                            ["236776"] = true,
                            ["198144"] = false,
                            ["258860"] = true,
                            ["372048"] = false,
                            ["132578"] = true,
                            ["473909"] = false,
                            ["359053"] = false,
                            ["113942"] = false,
                            ["49206"] = true,
                            ["110959"] = true,
                        },
                        ["icons"] = {
                            ["scale"] = 0.75,
                            ["swipeAlpha"] = 0,
                        },
                        ["priority"] = {
                            ["taunt"] = 2,
                            ["freedom"] = 10,
                            ["racial"] = 17,
                            ["disarm"] = 4,
                            ["pvptrinket"] = 18,
                            ["dispel"] = 16,
                            ["cc"] = 3,
                            ["counterCC"] = 16,
                            ["externalDefensive"] = 11,
                            ["other"] = 6,
                            ["interrupt"] = 1,
                            ["aoeCC"] = 5,
                            ["essence"] = 15,
                            ["trinket"] = 15,
                            ["defensive"] = 13,
                            ["consumable"] = 15,
                            ["covenant"] = 14,
                            ["heal"] = 12,
                            ["movement"] = 8,
                            ["raidMovement"] = 9,
                            ["offensive"] = 1,
                            ["raidDefensive"] = 11,
                            ["tankDefensive"] = 13,
                            ["immunity"] = 14,
                        },
                        ["position"] = {
                            ["offsetX"] = 1,
                            ["anchor"] = "TOPRIGHT",
                            ["paddingY"] = 1,
                            ["preset"] = "TOPLEFT",
                            ["paddingX"] = 1,
                            ["attach"] = "TOPLEFT",
                            ["maxNumIcons"] = 12,
                        },
                        ["frame"] = {
                            ["disarm"] = 2,
                            ["cc"] = 2,
                            ["aoeCC"] = 2,
                        },
                        ["general"] = {
                            ["showPlayer"] = true,
                            ["zoneSelected"] = "party",
                            ["showRange"] = true,
                        },
                    },
                },
                ["General"] = {
                    ["textures"] = {
                        ["statusBar"] = {
                            ["BG"] = "GennUI B",
                            ["bar"] = "GennUI B",
                        },
                    },
                    ["fonts"] = {
                        ["statusBar"] = {
                            ["font"] = "GennUI",
                            ["ofsX"] = 0,
                            ["flag"] = "OUTLINE",
                        },
                        ["icon"] = {
                            ["font"] = "GennUI",
                        },
                        ["anchor"] = {
                            ["font"] = "GennUI",
                            ["ofsX"] = 0,
                            ["flag"] = "OUTLINE",
                        },
                    },
                },
            },
        },
    }

end