local E, L, V, P, G = unpack(ElvUI);
local GNUI = E:GetModule("GennUI");

function GNUI:LoadSkadaProfile()
SkadaDB = {
	["namespaces"] = {
		["LibDualSpec-1.0"] = {
		},
	},
	["profileKeys"] = {
	},
	["profiles"] = {
		["Default"] = {
			["modeclicks"] = {
				["Healing"] = 1,
				["Damage"] = 2,
			},
			["themes"] = {
				{
					["titleset"] = true,
					["barheight"] = 18,
					["color"] = {
						["a"] = 0.6,
						["r"] = 0.3,
						["g"] = 0.3,
						["b"] = 0.3,
					},
					["issolidbackdrop"] = false,
					["classicons"] = true,
					["barslocked"] = true,
					["useframe"] = true,
					["clickthrough"] = false,
					["wipemode"] = "",
					["set"] = "current",
					["hidden"] = false,
					["y"] = 7.778419494628906,
					["barfont"] = "GennUI",
					["name"] = "GennUI",
					["display"] = "bar",
					["showself"] = true,
					["barfontflags"] = "OUTLINE",
					["isusingelvuiskin"] = true,
					["title"] = {
						["textcolor"] = {
							["a"] = 1,
							["r"] = 0.9,
							["g"] = 0.9,
							["b"] = 0.9,
						},
						["color"] = {
							["a"] = 0,
							["r"] = 0.3019607843137255,
							["g"] = 0.3019607843137255,
							["b"] = 0.3019607843137255,
						},
						["bordercolor"] = {
							["a"] = 0,
							["r"] = 0,
							["g"] = 0,
							["b"] = 0,
						},
						["font"] = "GennUI",
						["fontsize"] = 12,
						["height"] = 20,
						["fontflags"] = "OUTLINE",
						["bordertexture"] = "None",
						["borderthickness"] = 0,
						["texture"] = "GennUI",
					},
					["strata"] = "LOW",
					["point"] = "BOTTOMRIGHT",
					["spellschoolcolors"] = true,
					["barbgcolor"] = {
						["a"] = 0.6,
						["r"] = 0.3,
						["g"] = 0.3,
						["b"] = 0.3,
					},
					["barcolor"] = {
						["a"] = 1,
						["r"] = 0.3,
						["g"] = 0.3,
						["b"] = 0.8,
					},
					["isonnewline"] = false,
					["returnaftercombat"] = false,
					["height"] = 30,
					["background"] = {
						["height"] = 133.3330993652344,
						["bordercolor"] = {
							["a"] = 0,
							["r"] = 0,
							["g"] = 0,
							["b"] = 0,
						},
						["borderthickness"] = 1,
						["tile"] = false,
						["color"] = {
							["a"] = 0,
							["r"] = 0,
							["g"] = 0,
							["b"] = 0,
						},
						["bordertexture"] = "None",
						["tilesize"] = 0,
						["texture"] = "None",
					},
					["reversegrowth"] = false,
					["roleicons"] = false,
					["barorientation"] = 1,
					["mode"] = "Damage",
					["bartexture"] = "GennUI",
					["modeincombat"] = "",
					["width"] = 600,
					["textcolor"] = {
						["r"] = 0.9,
						["g"] = 0.9,
						["b"] = 0.9,
					},
					["fixedbarwidth"] = false,
					["buttons"] = {
						["segment"] = true,
						["menu"] = true,
						["mode"] = true,
						["report"] = true,
						["reset"] = true,
					},
					["barwidth"] = 284.4442443847656,
					["barspacing"] = 0,
					["enabletitle"] = true,
					["smoothing"] = true,
					["version"] = 1,
					["scale"] = 1,
					["snapto"] = true,
					["classcolorbars"] = true,
					["isusingclasscolors"] = true,
					["barfontsize"] = 12,
					["x"] = -6.66845703125,
					["classcolortext"] = false,
				}, -- [1]
			},
			["windows"] = {
				{
					["barslocked"] = true,
					["y"] = 7.778419494628906,
					["barfont"] = "GennUI",
					["name"] = "Damage",
					["mode"] = "Damage",
					["barfontflags"] = "OUTLINE",
					["point"] = "BOTTOMRIGHT",
					["x"] = -6.66845703125,
					["barfontsize"] = 12,
					["background"] = {
						["color"] = {
							["a"] = 0,
						},
						["bordertexture"] = "None",
						["height"] = 133.3330993652344,
						["bordercolor"] = {
							["a"] = 0,
						},
						["texture"] = "None",
					},
					["barwidth"] = 284.4442443847656,
					["smoothing"] = true,
					["bartexture"] = "GennUI",
					["title"] = {
						["color"] = {
							["a"] = 0,
							["b"] = 0.3019607843137255,
							["g"] = 0.3019607843137255,
							["r"] = 0.3019607843137255,
						},
						["bordercolor"] = {
							["a"] = 0,
						},
						["font"] = "GennUI",
						["fontsize"] = 12,
						["fontflags"] = "OUTLINE",
						["borderthickness"] = 0,
						["texture"] = "GennUI",
					},
				}, -- [1]
				{
					["titleset"] = true,
					["barheight"] = 18,
					["color"] = {
						["a"] = 0.6,
						["b"] = 0.3,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["issolidbackdrop"] = false,
					["classicons"] = true,
					["barslocked"] = true,
					["useframe"] = true,
					["clickthrough"] = false,
					["wipemode"] = "",
					["set"] = "current",
					["hidden"] = false,
					["y"] = 168.889404296875,
					["barfont"] = "GennUI",
					["name"] = "Heaaling",
					["display"] = "bar",
					["point"] = "BOTTOMRIGHT",
					["barfontflags"] = "OUTLINE",
					["isusingelvuiskin"] = true,
					["x"] = -6.667724609375,
					["strata"] = "LOW",
					["classcolortext"] = false,
					["spellschoolcolors"] = true,
					["barbgcolor"] = {
						["a"] = 0.6,
						["b"] = 0.3,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["barcolor"] = {
						["a"] = 1,
						["b"] = 0.8,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["mode"] = "Healing",
					["returnaftercombat"] = false,
					["showself"] = true,
					["buttons"] = {
						["segment"] = true,
						["report"] = true,
						["menu"] = true,
						["reset"] = true,
					},
					["title"] = {
						["textcolor"] = {
							["a"] = 1,
							["b"] = 0.9,
							["g"] = 0.9,
							["r"] = 0.9,
						},
						["color"] = {
							["a"] = 0,
							["b"] = 0.3019607843137255,
							["g"] = 0.3019607843137255,
							["r"] = 0.3019607843137255,
						},
						["bordercolor"] = {
							["a"] = 0,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["font"] = "GennUI",
						["fontsize"] = 12,
						["fontflags"] = "OUTLINE",
						["height"] = 20,
						["borderthickness"] = 0,
						["bordertexture"] = "None",
						["texture"] = "GennUI",
					},
					["roleicons"] = false,
					["barorientation"] = 1,
					["snapto"] = true,
					["isonnewline"] = false,
					["fixedbarwidth"] = false,
					["scale"] = 1,
					["textcolor"] = {
						["b"] = 0.9,
						["g"] = 0.9,
						["r"] = 0.9,
					},
					["reversegrowth"] = false,
					["bartexture"] = "GennUI",
					["barwidth"] = 284.4442443847656,
					["barspacing"] = 0,
					["modeincombat"] = "",
					["width"] = 600,
					["smoothing"] = true,
					["enabletitle"] = true,
					["version"] = 1,
					["classcolorbars"] = true,
					["isusingclasscolors"] = true,
					["background"] = {
						["color"] = {
							["a"] = 0,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["bordertexture"] = "None",
						["borderthickness"] = 1,
						["tile"] = false,
						["height"] = 57.77749633789063,
						["bordercolor"] = {
							["a"] = 0,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["tilesize"] = 0,
						["texture"] = "None",
					},
					["height"] = 30,
					["barfontsize"] = 12,
				}, -- [2]
			},
			["versions"] = {
				["1.6.3"] = true,
				["1.8.0"] = true,
				["1.6.4"] = true,
				["1.6.7"] = true,
			},
		},
	},
}
end