local E, L, V, P, G = unpack(ElvUI)
local IsAddOnLoaded = IsAddOnLoaded
local format = string.format
local MyPluginName = "GennUI"
local GNUI = E:GetModule("GennUI");
local classColor = E:ClassColor(E.myclass, true)

function GNUI:LoadWTProfile()
if IsAddOnLoaded('ElvUI_WindTools') then

E.db["movers"]["WTExtraItemsBar1Mover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-312,20"
E.db["movers"]["WTExtraItemsBar2Mover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-312,54"
E.db["movers"]["WTExtraItemsBar3Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-207,98"
E.db["movers"]["WTExtraItemsBar4Mover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-466,136"
E.db["movers"]["WTExtraItemsBar5Mover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-465,178"
E.db["movers"]["WTMinimapButtonBarAnchor"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-3,-203"
E.db["movers"]["WTRaidMarkersBarAnchor"] = "BOTTOM,ElvUIParent,BOTTOM,-340,376"
E.db["movers"]["WTParagonReputationToastFrameMover"] = "TOP,UIParent,TOP,0,-468"
E.db["WT"]["announcement"]["combatResurrection"]["enable"] = false
E.db["WT"]["announcement"]["goodbye"]["enable"] = false
E.db["WT"]["announcement"]["interrupt"]["enable"] = false
E.db["WT"]["announcement"]["interrupt"]["player"]["enable"] = false
E.db["WT"]["announcement"]["keystone"]["text"] = "New keystone is %keystone%."
E.db["WT"]["announcement"]["thanksForResurrection"]["normalText"] = "%target%, thanks for the RES !"
E.db["WT"]["announcement"]["thanksForResurrection"]["soulstoneText"] = "Thanks for the soulstone. :)"
E.db["WT"]["announcement"]["threatTransfer"]["enable"] = false
E.db["WT"]["announcement"]["utility"]["spells"]["190336"]["text"] = "%player% is making a table !"
E.db["WT"]["announcement"]["utility"]["spells"]["195782"]["enable"] = false
E.db["WT"]["announcement"]["utility"]["spells"]["261602"]["enable"] = false
E.db["WT"]["announcement"]["utility"]["spells"]["29893"]["text"] = "%player% is handing out stones!"
E.db["WT"]["announcement"]["utility"]["spells"]["54710"]["enable"] = false
E.db["WT"]["combat"]["combatAlert"]["animationSize"] = 0.7
E.db["WT"]["combat"]["combatAlert"]["enterText"] = "Combat ++"
E.db["WT"]["combat"]["combatAlert"]["leaveText"] = "Combat --"
E.db["WT"]["combat"]["combatAlert"]["speed"] = 1.2
E.db["WT"]["combat"]["raidMarkers"]["backdrop"] = false
E.db["WT"]["combat"]["raidMarkers"]["buttonSize"] = 20
E.db["WT"]["combat"]["raidMarkers"]["mouseOver"] = true
E.db["WT"]["combat"]["raidMarkers"]["spacing"] = 1
E.db["WT"]["item"]["delete"]["enable"] = false
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["backdrop"] = false
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["bindFont"]["name"] = "GennUI"
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["buttonHeight"] = 28
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["buttonWidth"] = 28
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["countFont"]["name"] = "GennUI"
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["include"] = "QUEST,TORGHAST,UTILITY"
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["mouseOver"] = false
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["numButtons"] = 6
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["spacing"] = 1
E.db["WT"]["item"]["extraItemsBar"]["bar2"]["backdrop"] = false
E.db["WT"]["item"]["extraItemsBar"]["bar2"]["bindFont"]["name"] = "GennUI"
E.db["WT"]["item"]["extraItemsBar"]["bar2"]["buttonHeight"] = 28
E.db["WT"]["item"]["extraItemsBar"]["bar2"]["buttonWidth"] = 28
E.db["WT"]["item"]["extraItemsBar"]["bar2"]["countFont"]["name"] = "GennUI"
E.db["WT"]["item"]["extraItemsBar"]["bar2"]["include"] = "POTIONSL,FLASKSL,FOODSL,FOODVENDOR,FOODMAGE"
E.db["WT"]["item"]["extraItemsBar"]["bar2"]["mouseOver"] = false
E.db["WT"]["item"]["extraItemsBar"]["bar2"]["numButtons"] = 6
E.db["WT"]["item"]["extraItemsBar"]["bar2"]["spacing"] = 1
E.db["WT"]["item"]["extraItemsBar"]["bar3"]["enable"] = false
E.db["WT"]["item"]["inspect"]["equipText"]["size"] = 10
E.db["WT"]["item"]["inspect"]["levelText"]["name"] = "GennUI"
E.db["WT"]["item"]["inspect"]["levelText"]["size"] = 10
E.db["WT"]["item"]["inspect"]["statsText"]["size"] = 10
E.db["WT"]["misc"]["gameBar"]["additionalText"]["font"]["name"] = "GennUI"
E.db["WT"]["misc"]["gameBar"]["backdropSpacing"] = 1
E.db["WT"]["misc"]["gameBar"]["buttonSize"] = 20
E.db["WT"]["misc"]["gameBar"]["home"]["right"] = "140192"
E.db["WT"]["misc"]["gameBar"]["mouseOver"] = true
E.db["WT"]["misc"]["gameBar"]["time"]["font"]["name"] = "GennUI"
E.db["WT"]["misc"]["gameBar"]["time"]["font"]["size"] = 24
E.db["WT"]["misc"]["gameBar"]["time"]["localTime"] = false
E.db["WT"]["misc"]["gameBar"]["timeAreaHeight"] = 24
E.db["WT"]["misc"]["gameBar"]["timeAreaWidth"] = 200
E.db["WT"]["quest"]["switchButtons"]["enable"] = false
E.db["WT"]["quest"]["turnIn"]["enable"] = false
E.db["WT"]["skins"]["vignetting"]["enable"] = false
E.db["WT"]["social"]["chatBar"]["enable"] = false
E.db["WT"]["social"]["chatLink"]["enable"] = false
E.db["WT"]["social"]["chatText"]["removeRealm"] = false
E.db["WT"]["social"]["friendList"]["nameFont"]["size"] = 12
E.db["WT"]["social"]["friendList"]["textures"]["factionIcon"] = true
E.db["WT"]["social"]["friendList"]["textures"]["game"] = "Default"
E.db["WT"]["social"]["friendList"]["textures"]["status"] = "Default"
E.db["WT"]["social"]["smartTab"]["enable"] = false
E.private["WT"]["combat"]["talentManager"]["enable"] = false
E.private["WT"]["maps"]["minimapButtons"]["backdrop"] = false
E.private["WT"]["maps"]["minimapButtons"]["buttonSize"] = 22
E.private["WT"]["maps"]["minimapButtons"]["spacing"] = 1
E.private["WT"]["maps"]["superTracker"]["noLimit"] = true
E.private["WT"]["maps"]["worldMap"]["scale"]["enable"] = false
E.private["WT"]["maps"]["worldMap"]["scale"]["size"] = 1.25
E.private["WT"]["misc"]["lfgList"]["line"]["tex"] = "GennUI"
E.private["WT"]["quest"]["objectiveTracker"]["titleColor"]["classColor"] = true
E.private["WT"]["skins"]["ime"]["label"]["name"] = "GennUI"
E.private["WT"]["skins"]["ime"]["label"]["size"] = 12
E.private["WT"]["skins"]["shadow"] = false
E.private["WT"]["tooltips"]["icon"] = false
E.private["WT"]["unitFrames"]["quickFocus"]["button"] = "BUTTON3"
E.private["WT"]["unitFrames"]["quickFocus"]["modifier"] = "alt"

end
end