local E, L, V, P, G = unpack(ElvUI)
local IsAddOnLoaded = C_AddOns.IsAddOnLoaded
local format = string.format
local MyPluginName = "GennUI"
local GNUI = E:GetModule("GennUI");
local classColor = E:ClassColor(E.myclass, true)

function GNUI:SetupUnitframes()

-- Colors & Stuff
E.db["unitframe"]["colors"]["classResources"]["chargedComboPoint"]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["chargedComboPoint"]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["chargedComboPoint"]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][1]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][1]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][1]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][2]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][2]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][2]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][3]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][3]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][3]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][4]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][4]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][4]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][5]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][5]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][5]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][6]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][6]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][6]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][7]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][7]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["comboPoints"][7]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["DEATHKNIGHT"]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["DEATHKNIGHT"]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["DEATHKNIGHT"]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][1]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][1]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][1]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][2]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][2]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][2]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][3]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][3]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][3]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][4]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][4]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][4]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][5]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][5]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][5]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][6]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][6]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["EVOKER"][6]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["PALADIN"]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["PALADIN"]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["PALADIN"]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["MAGE"]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["MAGE"]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["MAGE"]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["WARLOCK"]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["WARLOCK"]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["WARLOCK"]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["MONK"][1]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["MONK"][1]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["MONK"][1]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["MONK"][2]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["MONK"][2]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["MONK"][2]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["MONK"][3]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["MONK"][3]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["MONK"][3]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["MONK"][4]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["MONK"][4]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["MONK"][4]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["MONK"][5]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["MONK"][5]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["MONK"][5]["b"] = classColor.b
E.db["unitframe"]["colors"]["classResources"]["MONK"][6]["r"] = classColor.r
E.db["unitframe"]["colors"]["classResources"]["MONK"][6]["g"] = classColor.g
E.db["unitframe"]["colors"]["classResources"]["MONK"][6]["b"] = classColor.b
E.db["unitframe"]["colors"]["power"]["MANA"]["b"] = 2551 / 255
E.db["unitframe"]["colors"]["power"]["MANA"]["g"] = 209 / 255
E.db["unitframe"]["colors"]["power"]["MANA"]["r"] = 0 / 255
E.db["unitframe"]["colors"]["power"]["FURY"]["r"] = 255 / 255
E.db["unitframe"]["colors"]["power"]["FURY"]["g"] = 142 / 255
E.db["unitframe"]["colors"]["power"]["FURY"]["b"] = 15 / 255
E.db["unitframe"]["colors"]["power"]["FOCUS"]["b"] = 15 / 255
E.db["unitframe"]["colors"]["power"]["FOCUS"]["g"] = 142 / 255
E.db["unitframe"]["colors"]["power"]["FOCUS"]["r"] = 255 / 255
E.db["unitframe"]["colors"]["power"]["RUNIC_POWER"]["r"] = 0 / 255
E.db["unitframe"]["colors"]["power"]["RUNIC_POWER"]["g"] = 209 / 255
E.db["unitframe"]["colors"]["power"]["RUNIC_POWER"]["b"] = 255 / 255
E.db["unitframe"]["colors"]["power"]["ENERGY"]["b"] = 31 / 255
E.db["unitframe"]["colors"]["power"]["ENERGY"]["g"] = 219 / 255
E.db["unitframe"]["colors"]["power"]["ENERGY"]["r"] = 230 / 255
E.db["unitframe"]["colors"]["power"]["MAELSTROM"]["r"] = 0 / 255
E.db["unitframe"]["colors"]["power"]["MAELSTROM"]["g"] = 128 / 255
E.db["unitframe"]["colors"]["power"]["MAELSTROM"]["b"] = 255 / 255
E.db["unitframe"]["colors"]["power"]["PAIN"]["r"] = 225 / 255
E.db["unitframe"]["colors"]["power"]["PAIN"]["g"] = 225 / 255
E.db["unitframe"]["colors"]["power"]["PAIN"]["b"] = 225 / 255
E.db["unitframe"]["colors"]["power"]["LUNAR_POWER"]["b"] = 31 / 255
E.db["unitframe"]["colors"]["power"]["LUNAR_POWER"]["g"] = 219 / 255
E.db["unitframe"]["colors"]["power"]["LUNAR_POWER"]["r"] = 230 / 255
E.db["unitframe"]["colors"]["power"]["INSANITY"]["b"] = 176 / 255
E.db["unitframe"]["colors"]["power"]["INSANITY"]["g"] = 36 / 255
E.db["unitframe"]["colors"]["power"]["INSANITY"]["r"] = 140 / 255
E.db["unitframe"]["colors"]["power"]["RAGE"]["b"] = 31 / 255
E.db["unitframe"]["colors"]["power"]["RAGE"]["g"] = 31 / 255
E.db["unitframe"]["colors"]["power"]["RAGE"]["r"] = 199 / 255
E.db["unitframe"]["colors"]["runeBySpec"] = false
E.db["unitframe"]["colors"]["chargingRunes"] = false
E.db["unitframe"]["colors"]["auraBarDebuff"]["r"] = 79 / 255
E.db["unitframe"]["colors"]["auraBarDebuff"]["g"] = 79 / 255
E.db["unitframe"]["colors"]["auraBarDebuff"]["b"] = 79 / 255
E.db["unitframe"]["colors"]["health"]["r"] = 20 / 255
E.db["unitframe"]["colors"]["health"]["g"] = 20 / 255
E.db["unitframe"]["colors"]["health"]["b"] = 20 / 255
E.db["unitframe"]["colors"]["health_backdrop"]["r"] = 20 / 255
E.db["unitframe"]["colors"]["health_backdrop"]["g"] = 20 / 255
E.db["unitframe"]["colors"]["health_backdrop"]["b"] = 20 / 255
E.db["unitframe"]["colors"]["castColor"]["r"] = 0 / 255
E.db["unitframe"]["colors"]["castColor"]["g"] = 128 / 255
E.db["unitframe"]["colors"]["castColor"]["b"] = 255 / 255
E.db["unitframe"]["colors"]["castNoInterrupt"]["r"] = 200 / 255
E.db["unitframe"]["colors"]["castNoInterrupt"]["g"] = 20 / 255
E.db["unitframe"]["colors"]["castNoInterrupt"]["b"] = 20 / 255
E.db["unitframe"]["colors"]["castbar_backdrop"]["r"] = 20 / 255
E.db["unitframe"]["colors"]["castbar_backdrop"]["g"] = 20 / 255
E.db["unitframe"]["colors"]["castbar_backdrop"]["b"] = 20 / 255
E.db["unitframe"]["colors"]["healthMultiplier"] = 1
E.db["unitframe"]["colors"]["colorhealthbyvalue"] = false
E.db["unitframe"]["colors"]["debuffHighlight"]["Curse"]["a"] = 0.45
E.db["unitframe"]["colors"]["debuffHighlight"]["Disease"]["a"] = 0.45
E.db["unitframe"]["colors"]["debuffHighlight"]["Magic"]["a"] = 0.45
E.db["unitframe"]["colors"]["debuffHighlight"]["Poison"]["a"] = 0.45
E.db["unitframe"]["colors"]["debuffHighlight"]["Bleed"]["a"] = 0.45
E.db["unitframe"]["colors"]["debuffHighlight"]["blendMode"] = "ADD"
E.db["unitframe"]["debuffHighlighting"] = "FILL"
E.db["unitframe"]["colors"]["frameGlow"]["mouseoverGlow"]["enable"] = false
E.db["unitframe"]["colors"]["frameGlow"]["targetGlow"]["enable"] = false
E.db["unitframe"]["colors"]["healthclass"] = true
E.db["unitframe"]["colors"]["classbackdrop"] = false
E.db["unitframe"]["colors"]["customhealthbackdrop"] = true
E.db["unitframe"]["font"] = "GennUI"
E.db["unitframe"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["fontSize"] = 12
E.db["unitframe"]["smartRaidFilter"] = false
E.db["unitframe"]["maxAllowedGroups"] = false
E.db["unitframe"]["smoothbars"] = true
E.db["unitframe"]["statusbar"] = "GennUI B"

--- Custom Texts
E.db["unitframe"]["units"]["player"]["customTexts"] = E.db["unitframe"]["units"]["player"]["customTexts"] or {}
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"] = {}
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"] = {}
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"] = {}
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"] = {}
E.db["unitframe"]["units"]["target"]["customTexts"] = E.db["unitframe"]["units"]["target"]["customTexts"] or {}
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"] = {}
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"] = {}
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"] = {}
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"] = {}
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"] = {}	
E.db["unitframe"]["units"]["boss"]["customTexts"] = E.db["unitframe"]["units"]["boss"]["customTexts"] or {}
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"] = {}
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"] = {}
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"] = {}
E.db["unitframe"]["units"]["arena"]["customTexts"] = E.db["unitframe"]["units"]["arena"]["customTexts"] or {}
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"] = {}
E.db["unitframe"]["units"]["party"]["customTexts"] = E.db["unitframe"]["units"]["party"]["customTexts"] or {}
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"] = {}
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"] = {}
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"] = {}

-- Arena
E.db["unitframe"]["units"]["arena"]["enable"] = true
E.db["unitframe"]["units"]["arena"]["buffs"]["anchorPoint"] = "LEFT"
E.db["unitframe"]["units"]["arena"]["buffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["arena"]["buffs"]["maxDuration"] = 0
E.db["unitframe"]["units"]["arena"]["buffs"]["perrow"] = 1
E.db["unitframe"]["units"]["arena"]["buffs"]["priority"] = "Blacklist,TurtleBuffs,Dispellable"
E.db["unitframe"]["units"]["arena"]["buffs"]["sizeOverride"] = 24
E.db["unitframe"]["units"]["arena"]["buffs"]["xOffset"] = 70
E.db["unitframe"]["units"]["arena"]["buffs"]["yOffset"] = 12
E.db["unitframe"]["units"]["arena"]["castbar"]["height"] = 14
E.db["unitframe"]["units"]["arena"]["castbar"]["iconAttached"] = false
E.db["unitframe"]["units"]["arena"]["castbar"]["iconAttachedTo"] = "Castbar"
E.db["unitframe"]["units"]["arena"]["castbar"]["iconPosition"] = "RIGHT"
E.db["unitframe"]["units"]["arena"]["castbar"]["iconSize"] = 28
E.db["unitframe"]["units"]["arena"]["castbar"]["iconXOffset"] = 2
E.db["unitframe"]["units"]["arena"]["castbar"]["iconYOffset"] = 8
E.db["unitframe"]["units"]["arena"]["castbar"]["width"] = 180
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"]["enable"] = true
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"]["font"] = "GennUI"
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"]["size"] = 16
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"]["xOffset"] = 0
E.db["unitframe"]["units"]["arena"]["customTexts"]["gName"]["yOffset"] = 16
E.db["unitframe"]["units"]["arena"]["debuffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["arena"]["debuffs"]["desaturate"] = true
E.db["unitframe"]["units"]["arena"]["debuffs"]["maxDuration"] = 0
E.db["unitframe"]["units"]["arena"]["debuffs"]["perrow"] = 1
E.db["unitframe"]["units"]["arena"]["debuffs"]["priority"] = "Blacklist,blockNoDuration,CCDebuffs,Whitelist"
E.db["unitframe"]["units"]["arena"]["debuffs"]["sizeOverride"] = 36
E.db["unitframe"]["units"]["arena"]["debuffs"]["xOffset"] = 35
E.db["unitframe"]["units"]["arena"]["debuffs"]["yOffset"] = 0
E.db["unitframe"]["units"]["arena"]["growthDirection"] = "UP"
E.db["unitframe"]["units"]["arena"]["health"]["position"] = "RIGHT"
E.db["unitframe"]["units"]["arena"]["health"]["text_format"] = "[health:current:shortvalue]"
E.db["unitframe"]["units"]["arena"]["health"]["xOffset"] = 0
E.db["unitframe"]["units"]["arena"]["health"]["yOffset"] = -8
E.db["unitframe"]["units"]["arena"]["height"] = 35
E.db["unitframe"]["units"]["arena"]["infoPanel"]["height"] = 16
E.db["unitframe"]["units"]["arena"]["middleClickFocus"] = true
E.db["unitframe"]["units"]["arena"]["name"]["text_format"] = ""
E.db["unitframe"]["units"]["arena"]["power"]["height"] = 3
E.db["unitframe"]["units"]["arena"]["power"]["position"] = "BOTTOMLEFT"
E.db["unitframe"]["units"]["arena"]["power"]["text_format"] = ""
E.db["unitframe"]["units"]["arena"]["power"]["width"] = "spaced"
E.db["unitframe"]["units"]["arena"]["power"]["xOffset"] = 60
E.db["unitframe"]["units"]["arena"]["power"]["yOffset"] = -6
E.db["unitframe"]["units"]["arena"]["pvpTrinket"]["position"] = "LEFT"
E.db["unitframe"]["units"]["arena"]["pvpTrinket"]["size"] = 34
E.db["unitframe"]["units"]["arena"]["pvpTrinket"]["xOffset"] = -1
E.db["unitframe"]["units"]["arena"]["pvpTrinket"]["yOffset"] = 1
E.db["unitframe"]["units"]["arena"]["spacing"] = 8
E.db["unitframe"]["units"]["arena"]["width"] = 180

-- Assist
E.db["unitframe"]["units"]["assist"]["buffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["assist"]["debuffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["assist"]["name"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["assist"]["rdebuffs"]["font"] = "GennUI"
E.db["unitframe"]["units"]["assist"]["rdebuffs"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["assist"]["rdebuffs"]["onlyMatchSpellID"] = false
E.db["unitframe"]["units"]["assist"]["targetsGroup"]["name"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["assist"]["threatStyle"] = "NONE"

-- Boss
E.db["unitframe"]["units"]["boss"]["buffs"]["anchorPoint"] = "LEFT"
E.db["unitframe"]["units"]["boss"]["buffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["boss"]["buffs"]["perrow"] = 1
E.db["unitframe"]["units"]["boss"]["buffs"]["sizeOverride"] = 24
E.db["unitframe"]["units"]["boss"]["buffs"]["xOffset"] = 50
E.db["unitframe"]["units"]["boss"]["buffs"]["yOffset"] = 12
E.db["unitframe"]["units"]["boss"]["castbar"]["height"] = 14
E.db["unitframe"]["units"]["boss"]["castbar"]["iconAttached"] = false
E.db["unitframe"]["units"]["boss"]["castbar"]["iconAttachedTo"] = "Castbar"
E.db["unitframe"]["units"]["boss"]["castbar"]["iconPosition"] = "RIGHT"
E.db["unitframe"]["units"]["boss"]["castbar"]["iconSize"] = 28
E.db["unitframe"]["units"]["boss"]["castbar"]["iconXOffset"] = 2
E.db["unitframe"]["units"]["boss"]["castbar"]["iconYOffset"] = 8
E.db["unitframe"]["units"]["boss"]["castbar"]["width"] = 160
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"]["enable"] = true
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"]["font"] = "GennUI"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"]["size"] = 16
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"]["text_format"] = "[name:abbrev:medium]"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"]["xOffset"] = 0
E.db["unitframe"]["units"]["boss"]["customTexts"]["gName"]["yOffset"] = 16
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"]["enable"] = true
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"]["font"] = "GennUI"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"]["justifyH"] = "LEFT"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"]["size"] = 10
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"]["text_format"] = "[perhp<%]"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"]["xOffset"] = 0
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPercent"]["yOffset"] = -8
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"]["attachTextTo"] = "Power"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"]["enable"] = true
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"]["font"] = "GennUI"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"]["justifyH"] = "CENTER"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"]["size"] = 10
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"]["text_format"] = "[powercolor][power:current:shortvalue]"
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"]["xOffset"] = 50
E.db["unitframe"]["units"]["boss"]["customTexts"]["gPower"]["yOffset"] = 0
E.db["unitframe"]["units"]["boss"]["debuffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["boss"]["debuffs"]["sizeOverride"] = 36
E.db["unitframe"]["units"]["boss"]["debuffs"]["xOffset"] = -1
E.db["unitframe"]["units"]["boss"]["debuffs"]["yOffset"] = 0
E.db["unitframe"]["units"]["boss"]["growthDirection"] = "UP"
E.db["unitframe"]["units"]["boss"]["health"]["position"] = "RIGHT"
E.db["unitframe"]["units"]["boss"]["health"]["text_format"] = "[health:current:shortvalue]"
E.db["unitframe"]["units"]["boss"]["health"]["xOffset"] = 0
E.db["unitframe"]["units"]["boss"]["health"]["yOffset"] = -8
E.db["unitframe"]["units"]["boss"]["height"] = 35
E.db["unitframe"]["units"]["boss"]["middleClickFocus"] = true
E.db["unitframe"]["units"]["boss"]["name"]["text_format"] = ""
E.db["unitframe"]["units"]["boss"]["power"]["height"] = 3
E.db["unitframe"]["units"]["boss"]["power"]["position"] = "BOTTOMLEFT"
E.db["unitframe"]["units"]["boss"]["power"]["text_format"] = ""
E.db["unitframe"]["units"]["boss"]["power"]["width"] = "spaced"
E.db["unitframe"]["units"]["boss"]["power"]["xOffset"] = 85
E.db["unitframe"]["units"]["boss"]["power"]["yOffset"] = -6
E.db["unitframe"]["units"]["boss"]["spacing"] = 8
E.db["unitframe"]["units"]["boss"]["width"] = 160

-- Focus
E.db["unitframe"]["units"]["focus"]["aurabar"]["attachTo"] = "FRAME"
E.db["unitframe"]["units"]["focus"]["aurabar"]["detachedWidth"] = 130
E.db["unitframe"]["units"]["focus"]["aurabar"]["maxBars"] = 6
E.db["unitframe"]["units"]["focus"]["aurabar"]["priority"] = ""
E.db["unitframe"]["units"]["focus"]["aurabar"]["spacing"] = 2
E.db["unitframe"]["units"]["focus"]["aurabar"]["yOffset"] = 2
E.db["unitframe"]["units"]["focus"]["buffs"]["anchorPoint"] = "LEFT"
E.db["unitframe"]["units"]["focus"]["buffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["focus"]["buffs"]["enable"] = true
E.db["unitframe"]["units"]["focus"]["buffs"]["growthY"] = "DOWN"
E.db["unitframe"]["units"]["focus"]["buffs"]["perrow"] = 1
E.db["unitframe"]["units"]["focus"]["buffs"]["priority"] = "Blacklist,blockNoDuration,TurtleBuffs,Personal,PlayerBuffs,CastByUnit,Dispellable,RaidBuffsElvUI"
E.db["unitframe"]["units"]["focus"]["buffs"]["sizeOverride"] = 24
E.db["unitframe"]["units"]["focus"]["buffs"]["xOffset"] = 36
E.db["unitframe"]["units"]["focus"]["buffs"]["yOffset"] = 8
E.db["unitframe"]["units"]["focus"]["castbar"]["enable"] = false
E.db["unitframe"]["units"]["focus"]["castbar"]["width"] = 270
E.db["unitframe"]["units"]["focus"]["debuffs"]["anchorPoint"] = "RIGHT"
E.db["unitframe"]["units"]["focus"]["debuffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["focus"]["debuffs"]["growthY"] = "DOWN"
E.db["unitframe"]["units"]["focus"]["debuffs"]["perrow"] = 1
E.db["unitframe"]["units"]["focus"]["debuffs"]["priority"] = "Blacklist,CCDebuffs,Personal,Boss,RaidDebuffs,Dispellable,Whitelist"
E.db["unitframe"]["units"]["focus"]["debuffs"]["sizeOverride"] = 32
E.db["unitframe"]["units"]["focus"]["debuffs"]["xOffset"] = 2
E.db["unitframe"]["units"]["focus"]["disableTargetGlow"] = true
E.db["unitframe"]["units"]["focus"]["height"] = 20
E.db["unitframe"]["units"]["focus"]["infoPanel"]["height"] = 12
E.db["unitframe"]["units"]["focus"]["name"]["position"] = "RIGHT"
E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["focus"]["name"]["yOffset"] = 8
E.db["unitframe"]["units"]["focus"]["orientation"] = "RIGHT"
E.db["unitframe"]["units"]["focus"]["power"]["enable"] = false
E.db["unitframe"]["units"]["focus"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["focus"]["width"] = 105

-- Party
E.db["unitframe"]["units"]["party"]["buffs"]["anchorPoint"] = "RIGHT"
E.db["unitframe"]["units"]["party"]["buffs"]["clickThrough"] = true
E.db["unitframe"]["units"]["party"]["buffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["party"]["buffs"]["enable"] = true
E.db["unitframe"]["units"]["party"]["buffs"]["perrow"] = 1
E.db["unitframe"]["units"]["party"]["buffs"]["sizeOverride"] = 24
E.db["unitframe"]["units"]["party"]["buffs"]["xOffset"] = -42
E.db["unitframe"]["units"]["party"]["buffs"]["yOffset"] = 12
E.db["unitframe"]["units"]["party"]["classbar"]["altPowerTextFormat"] = ""
E.db["unitframe"]["units"]["party"]["classbar"]["fill"] = "spaced"
E.db["unitframe"]["units"]["party"]["classbar"]["height"] = 3
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"]["enable"] = true
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"]["font"] = "GennUI"
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"]["size"] = 12
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"]["text_format"] = "[health:current:shortvalue]"
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"]["xOffset"] = -10
E.db["unitframe"]["units"]["party"]["customTexts"]["gHealth"]["yOffset"] = -8
if GNUI.Retail then
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"]["enable"] = true
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"]["font"] = "GennUI"
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"]["justifyH"] = "LEFT"
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"]["size"] = 12
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"]["text_format"] = "[manacolor][gnuihmana]"
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"]["xOffset"] = 32
E.db["unitframe"]["units"]["party"]["customTexts"]["gMana"]["yOffset"] = -16
end
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"]["enable"] = true
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"]["font"] = "GennUI"
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"]["justifyH"] = "LEFT"
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"]["size"] = 16
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"]["xOffset"] = 0
E.db["unitframe"]["units"]["party"]["customTexts"]["gName"]["yOffset"] = 16
E.db["unitframe"]["units"]["party"]["debuffs"]["clickThrough"] = true
E.db["unitframe"]["units"]["party"]["debuffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["party"]["debuffs"]["perrow"] = 1
E.db["unitframe"]["units"]["party"]["debuffs"]["priority"] = "Blacklist,Boss,CCDebuffs,RaidDebuffs,Dispellable,Whitelist,nonPersonal"
E.db["unitframe"]["units"]["party"]["debuffs"]["sizeOverride"] = 32
E.db["unitframe"]["units"]["party"]["debuffs"]["xOffset"] = 1
E.db["unitframe"]["units"]["party"]["healPrediction"]["enable"] = true
E.db["unitframe"]["units"]["party"]["health"]["text_format"] = ""
E.db["unitframe"]["units"]["party"]["height"] = 35
E.db["unitframe"]["units"]["party"]["name"]["text_format"] = ""
E.db["unitframe"]["units"]["party"]["petsGroup"]["anchorPoint"] = "BOTTOMRIGHT"
E.db["unitframe"]["units"]["party"]["petsGroup"]["enable"] = true
E.db["unitframe"]["units"]["party"]["petsGroup"]["healPrediction"]["enable"] = true
E.db["unitframe"]["units"]["party"]["petsGroup"]["height"] = 8
E.db["unitframe"]["units"]["party"]["petsGroup"]["name"]["text_format"] = ""
E.db["unitframe"]["units"]["party"]["petsGroup"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["party"]["petsGroup"]["width"] = 80
E.db["unitframe"]["units"]["party"]["petsGroup"]["xOffset"] = -5
if GNUI.Retail then
E.db["unitframe"]["units"]["party"]["power"]["enable"] = false
end
E.db["unitframe"]["units"]["party"]["power"]["height"] = 3
E.db["unitframe"]["units"]["party"]["power"]["text_format"] = ""
E.db["unitframe"]["units"]["party"]["power"]["width"] = "spaced"
E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["xOffset"] = -2
E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["yOffset"] = 0
E.db["unitframe"]["units"]["party"]["rdebuffs"]["font"] = "GennUI"
E.db["unitframe"]["units"]["party"]["rdebuffs"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["party"]["rdebuffs"]["onlyMatchSpellID"] = false
E.db["unitframe"]["units"]["party"]["rdebuffs"]["yOffset"] = 4
E.db["unitframe"]["units"]["party"]["roleIcon"]["damager"] = false
E.db["unitframe"]["units"]["party"]["roleIcon"]["size"] = 12
E.db["unitframe"]["units"]["party"]["threatStyle"] = "GLOW"
E.db["unitframe"]["units"]["party"]["verticalSpacing"] = 8
E.db["unitframe"]["units"]["party"]["width"] = 160

-- Pet
E.db["unitframe"]["units"]["pet"]["buffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["pet"]["castbar"]["enable"] = false
E.db["unitframe"]["units"]["pet"]["debuffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["pet"]["height"] = 20
E.db["unitframe"]["units"]["pet"]["name"]["position"] = "LEFT"
E.db["unitframe"]["units"]["pet"]["name"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["pet"]["name"]["yOffset"] = 8
E.db["unitframe"]["units"]["pet"]["orientation"] = "LEFT"
E.db["unitframe"]["units"]["pet"]["power"]["enable"] = false
E.db["unitframe"]["units"]["pet"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["pet"]["width"] = 105

-- Player
E.db["unitframe"]["units"]["player"]["CombatIcon"]["size"] = 24
E.db["unitframe"]["units"]["player"]["RestIcon"]["anchorPoint"] = "LEFT"
E.db["unitframe"]["units"]["player"]["RestIcon"]["texture"] = "Resting1"
E.db["unitframe"]["units"]["player"]["RestIcon"]["xOffset"] = 0
E.db["unitframe"]["units"]["player"]["RestIcon"]["yOffset"] = 0
E.db["unitframe"]["units"]["player"]["aurabar"]["enable"] = false
E.db["unitframe"]["units"]["player"]["castbar"]["iconAttached"] = false
E.db["unitframe"]["units"]["player"]["castbar"]["iconAttachedTo"] = "Castbar"
E.db["unitframe"]["units"]["player"]["castbar"]["iconSize"] = 32
E.db["unitframe"]["units"]["player"]["castbar"]["iconXOffset"] = -2
E.db["unitframe"]["units"]["player"]["castbar"]["width"] = 250
E.db["unitframe"]["units"]["player"]["classbar"]["autoHide"] = true
E.db["unitframe"]["units"]["player"]["classbar"]["detachFromFrame"] = true
E.db["unitframe"]["units"]["player"]["classbar"]["detachedWidth"] = 120
E.db["unitframe"]["units"]["player"]["classbar"]["fill"] = "spaced"
E.db["unitframe"]["units"]["player"]["classbar"]["height"] = 3
E.db["unitframe"]["units"]["player"]["classbar"]["spacing"] = 2
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"]["enable"] = true
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"]["font"] = "GennUI"
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"]["size"] = 16
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"]["text_format"] = "[health:current:shortvalue]"
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"]["xOffset"] = 0
E.db["unitframe"]["units"]["player"]["customTexts"]["gHealth"]["yOffset"] = -14
if GNUI.Retail then
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"]["attachTextTo"] = "Power"
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"]["enable"] = true
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"]["font"] = "GennUI"
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"]["size"] = 12
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"]["text_format"] = "[manacolor][gnuihmana]"
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"]["xOffset"] = 32
E.db["unitframe"]["units"]["player"]["customTexts"]["gMana"]["yOffset"] = 2
end
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"]["enable"] = true
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"]["font"] = "GennUI"
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"]["justifyH"] = "LEFT"
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"]["size"] = 14
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"]["xOffset"] = 0
E.db["unitframe"]["units"]["player"]["customTexts"]["gName"]["yOffset"] = 14
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"]["attachTextTo"] = "Power"
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"]["enable"] = true
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"]["font"] = "GennUI"
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"]["justifyH"] = "LEFT"
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"]["size"] = 12
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"]["text_format"] = "[powercolor][power:current:shortvalue]"
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"]["xOffset"] = -36
E.db["unitframe"]["units"]["player"]["customTexts"]["gPower"]["yOffset"] = 2
E.db["unitframe"]["units"]["player"]["debuffs"]["enable"] = false
E.db["unitframe"]["units"]["player"]["health"]["text_format"] = ""
E.db["unitframe"]["units"]["player"]["height"] = 30
E.db["unitframe"]["units"]["player"]["power"]["detachFromFrame"] = true
E.db["unitframe"]["units"]["player"]["power"]["detachedWidth"] = 100
E.db["unitframe"]["units"]["player"]["power"]["height"] = 3
E.db["unitframe"]["units"]["player"]["power"]["text_format"] = ""
E.db["unitframe"]["units"]["player"]["power"]["width"] = "spaced"
E.db["unitframe"]["units"]["player"]["pvp"]["text_format"] = ""
E.db["unitframe"]["units"]["player"]["raidRoleIcons"]["xOffset"] = -2
E.db["unitframe"]["units"]["player"]["raidRoleIcons"]["yOffset"] = 0
E.db["unitframe"]["units"]["player"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["player"]["width"] = 250

-- Raid 1
E.db["unitframe"]["units"]["raid1"]["classbar"]["altPowerTextFormat"] = ""
E.db["unitframe"]["units"]["raid1"]["classbar"]["fill"] = "spaced"
E.db["unitframe"]["units"]["raid1"]["classbar"]["height"] = 3
E.db["unitframe"]["units"]["raid1"]["healPrediction"]["enable"] = true
E.db["unitframe"]["units"]["raid1"]["health"]["text_format"] = ""
E.db["unitframe"]["units"]["raid1"]["height"] = 28
E.db["unitframe"]["units"]["raid1"]["horizontalSpacing"] = 0
E.db["unitframe"]["units"]["raid1"]["name"]["text_format"] = "[name:veryshort]"
E.db["unitframe"]["units"]["raid1"]["numGroups"] = 5
E.db["unitframe"]["units"]["raid1"]["power"]["enable"] = false
E.db["unitframe"]["units"]["raid1"]["power"]["height"] = 3
E.db["unitframe"]["units"]["raid1"]["raidWideSorting"] = true
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["enable"] = true
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["font"] = "GennUI"
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["onlyMatchSpellID"] = false
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["size"] = 24
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["yOffset"] = 5
E.db["unitframe"]["units"]["raid1"]["roleIcon"]["damager"] = false
E.db["unitframe"]["units"]["raid1"]["roleIcon"]["enable"] = true
E.db["unitframe"]["units"]["raid1"]["roleIcon"]["size"] = 12
E.db["unitframe"]["units"]["raid1"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["raid1"]["verticalSpacing"] = 0

-- Raid 2
E.db["unitframe"]["units"]["raid2"]["classbar"]["altPowerTextFormat"] = ""
E.db["unitframe"]["units"]["raid2"]["classbar"]["fill"] = "spaced"
E.db["unitframe"]["units"]["raid2"]["classbar"]["height"] = 3
E.db["unitframe"]["units"]["raid2"]["healPrediction"]["enable"] = true
E.db["unitframe"]["units"]["raid2"]["health"]["text_format"] = ""
E.db["unitframe"]["units"]["raid2"]["height"] = 24
E.db["unitframe"]["units"]["raid2"]["horizontalSpacing"] = 0
E.db["unitframe"]["units"]["raid2"]["name"]["text_format"] = "[name:veryshort]"
E.db["unitframe"]["units"]["raid2"]["numGroups"] = 6
E.db["unitframe"]["units"]["raid2"]["power"]["enable"] = false
E.db["unitframe"]["units"]["raid2"]["power"]["height"] = 3
E.db["unitframe"]["units"]["raid2"]["raidWideSorting"] = true
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["enable"] = true
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["font"] = "GennUI"
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["onlyMatchSpellID"] = false
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["size"] = 22
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["yOffset"] = 1
E.db["unitframe"]["units"]["raid2"]["roleIcon"]["damager"] = false
E.db["unitframe"]["units"]["raid2"]["roleIcon"]["enable"] = true
E.db["unitframe"]["units"]["raid2"]["roleIcon"]["size"] = 12
E.db["unitframe"]["units"]["raid2"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["raid2"]["verticalSpacing"] = 0

-- Raid 3
E.db["unitframe"]["units"]["raid3"]["classbar"]["altPowerTextFormat"] = ""
E.db["unitframe"]["units"]["raid3"]["classbar"]["enable"] = false
E.db["unitframe"]["units"]["raid3"]["classbar"]["fill"] = "spaced"
E.db["unitframe"]["units"]["raid3"]["classbar"]["height"] = 3
E.db["unitframe"]["units"]["raid3"]["healPrediction"]["enable"] = true
E.db["unitframe"]["units"]["raid3"]["health"]["text_format"] = ""
E.db["unitframe"]["units"]["raid3"]["height"] = 17
E.db["unitframe"]["units"]["raid3"]["horizontalSpacing"] = 0
E.db["unitframe"]["units"]["raid3"]["name"]["text_format"] = "[name:veryshort]"
E.db["unitframe"]["units"]["raid3"]["raidWideSorting"] = true
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["enable"] = true
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["font"] = "GennUI"
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["onlyMatchSpellID"] = false
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["size"] = 16
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["yOffset"] = 1
E.db["unitframe"]["units"]["raid3"]["roleIcon"]["damager"] = false
E.db["unitframe"]["units"]["raid3"]["roleIcon"]["enable"] = true
E.db["unitframe"]["units"]["raid3"]["roleIcon"]["size"] = 12
E.db["unitframe"]["units"]["raid3"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["raid3"]["verticalSpacing"] = 0

-- Tank
E.db["unitframe"]["units"]["tank"]["buffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["tank"]["debuffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["tank"]["name"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["tank"]["rdebuffs"]["font"] = "GennUI"
E.db["unitframe"]["units"]["tank"]["rdebuffs"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["tank"]["rdebuffs"]["onlyMatchSpellID"] = false
E.db["unitframe"]["units"]["tank"]["targetsGroup"]["name"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["tank"]["threatStyle"] = "NONE"

-- Target
E.db["unitframe"]["units"]["target"]["CombatIcon"]["size"] = 24
E.db["unitframe"]["units"]["target"]["aurabar"]["enable"] = true
E.db["unitframe"]["units"]["target"]["aurabar"]["attachTo"] = "FRAME"
E.db["unitframe"]["units"]["target"]["aurabar"]["height"] = 13
E.db["unitframe"]["units"]["target"]["aurabar"]["maxBars"] = 5
E.db["unitframe"]["units"]["target"]["aurabar"]["priority"] = "Blacklist,blockNoDuration,CCDebuffs,Personal,Boss,RaidDebuffs,PlayerBuffs"
E.db["unitframe"]["units"]["target"]["aurabar"]["yOffset"] = 32
E.db["unitframe"]["units"]["target"]["buffs"]["anchorPoint"] = "TOPLEFT"
E.db["unitframe"]["units"]["target"]["buffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["target"]["buffs"]["countFontSize"] = 11
E.db["unitframe"]["units"]["target"]["buffs"]["growthX"] = "RIGHT"
E.db["unitframe"]["units"]["target"]["buffs"]["perrow"] = 5
E.db["unitframe"]["units"]["target"]["buffs"]["priority"] = "Blacklist,Dispellable,TurtleBuffs,Personal,nonPersonal"
E.db["unitframe"]["units"]["target"]["buffs"]["sizeOverride"] = 24
E.db["unitframe"]["units"]["target"]["buffs"]["yOffset"] = 4
E.db["unitframe"]["units"]["target"]["castbar"]["iconAttached"] = false
E.db["unitframe"]["units"]["target"]["castbar"]["iconAttachedTo"] = "Castbar"
E.db["unitframe"]["units"]["target"]["castbar"]["iconPosition"] = "RIGHT"
E.db["unitframe"]["units"]["target"]["castbar"]["iconSize"] = 32
E.db["unitframe"]["units"]["target"]["castbar"]["iconXOffset"] = 2
E.db["unitframe"]["units"]["target"]["castbar"]["width"] = 250
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"]["enable"] = true
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"]["font"] = "GennUI"
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"]["justifyH"] = "LEFT"
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"]["size"] = 16
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"]["text_format"] = "[health:current:shortvalue]"
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"]["xOffset"] = 0
E.db["unitframe"]["units"]["target"]["customTexts"]["gHealth"]["yOffset"] = -14
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"]["enable"] = true
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"]["font"] = "GennUI"
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"]["justifyH"] = "CENTER"
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"]["size"] = 10
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"]["text_format"] = "||cffffffff LvL [difficultycolor][level] [classification] [namecolor][smartclass]"
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"]["xOffset"] = 0
E.db["unitframe"]["units"]["target"]["customTexts"]["gInfo"]["yOffset"] = -24
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"]["enable"] = true
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"]["font"] = "GennUI"
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"]["size"] = 14
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"]["text_format"] = "[name:abbrev:medium]"
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"]["xOffset"] = 1
E.db["unitframe"]["units"]["target"]["customTexts"]["gName"]["yOffset"] = 14
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"]["enable"] = true
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"]["font"] = "GennUI"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"]["justifyH"] = "LEFT"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"]["size"] = 10
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"]["text_format"] = "[perhp<%]"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"]["xOffset"] = 0
E.db["unitframe"]["units"]["target"]["customTexts"]["gPercent"]["yOffset"] = 6
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"]["attachTextTo"] = "Power"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"]["enable"] = true
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"]["font"] = "GennUI"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"]["fontOutline"] = "OUTLINE"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"]["size"] = 12
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"]["text_format"] = "[powercolor][power:current:shortvalue]"
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"]["xOffset"] = 36
E.db["unitframe"]["units"]["target"]["customTexts"]["gPower"]["yOffset"] = 2
E.db["unitframe"]["units"]["target"]["debuffs"]["attachTo"] = "FRAME"
E.db["unitframe"]["units"]["target"]["debuffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["target"]["debuffs"]["countFontSize"] = 11
E.db["unitframe"]["units"]["target"]["debuffs"]["maxDuration"] = 0
E.db["unitframe"]["units"]["target"]["debuffs"]["perrow"] = 5
E.db["unitframe"]["units"]["target"]["debuffs"]["priority"] = "Blacklist,CCDebuffs,Personal,RaidDebuffs,Friendly:Dispellable,nonPersonal"
E.db["unitframe"]["units"]["target"]["debuffs"]["sizeOverride"] = 24
E.db["unitframe"]["units"]["target"]["debuffs"]["yOffset"] = 4
E.db["unitframe"]["units"]["target"]["health"]["position"] = "LEFT"
E.db["unitframe"]["units"]["target"]["health"]["text_format"] = ""
E.db["unitframe"]["units"]["target"]["health"]["xOffset"] = 2
E.db["unitframe"]["units"]["target"]["height"] = 30
E.db["unitframe"]["units"]["target"]["middleClickFocus"] = true
E.db["unitframe"]["units"]["target"]["name"]["text_format"] = ""
E.db["unitframe"]["units"]["target"]["power"]["detachFromFrame"] = true
E.db["unitframe"]["units"]["target"]["power"]["detachedWidth"] = 100
E.db["unitframe"]["units"]["target"]["power"]["height"] = 3
E.db["unitframe"]["units"]["target"]["power"]["position"] = "RIGHT"
E.db["unitframe"]["units"]["target"]["power"]["text_format"] = ""
E.db["unitframe"]["units"]["target"]["power"]["width"] = "spaced"
E.db["unitframe"]["units"]["target"]["power"]["xOffset"] = -2
E.db["unitframe"]["units"]["target"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["target"]["width"] = 250

-- Target's Target
E.db["unitframe"]["units"]["targettarget"]["buffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["targettarget"]["buffs"]["enable"] = true
E.db["unitframe"]["units"]["targettarget"]["buffs"]["growthY"] = "DOWN"
E.db["unitframe"]["units"]["targettarget"]["buffs"]["perrow"] = 2
E.db["unitframe"]["units"]["targettarget"]["buffs"]["sizeOverride"] = 20
E.db["unitframe"]["units"]["targettarget"]["debuffs"]["attachTo"] = "FRAME"
E.db["unitframe"]["units"]["targettarget"]["debuffs"]["countFont"] = "GennUI"
E.db["unitframe"]["units"]["targettarget"]["debuffs"]["growthY"] = "DOWN"
E.db["unitframe"]["units"]["targettarget"]["debuffs"]["perrow"] = 3
E.db["unitframe"]["units"]["targettarget"]["debuffs"]["sizeOverride"] = 20
E.db["unitframe"]["units"]["targettarget"]["height"] = 20
E.db["unitframe"]["units"]["targettarget"]["infoPanel"]["height"] = 12
E.db["unitframe"]["units"]["targettarget"]["name"]["position"] = "RIGHT"
E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = "[name:medium]"
E.db["unitframe"]["units"]["targettarget"]["name"]["yOffset"] = 8
E.db["unitframe"]["units"]["targettarget"]["orientation"] = "RIGHT"
E.db["unitframe"]["units"]["targettarget"]["power"]["enable"] = false
E.db["unitframe"]["units"]["targettarget"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["targettarget"]["width"] = 105

end